// Generated by vuetify-ext bootstrap app
import { createApp, defineComponent, h } from 'vue';
import { createVuetify } from 'vuetify';
import * as components from 'vuetify/components';
import * as directives from 'vuetify/directives';
import '@mdi/font/css/materialdesignicons.css';
import 'vuetify/styles';
import 'vuetify-extended/lib/esm/css/index.css';
import { initializeBootstrap } from './bootstrap';
import { bindVuetifyThemeMode, createVuetifyThemeOptions } from "./bootstrap/theme";

const vuetify = createVuetify({
  components,
  directives,
  theme: createVuetifyThemeOptions(),

});
bindVuetifyThemeMode(vuetify);

const bootstrap = initializeBootstrap();

const Root = defineComponent({
  name: 'VuetifyExtendedHostApp',
  setup() {
    return () => [
      h(bootstrap.component),
      h(bootstrap.dialogs),
      h(bootstrap.notifications),
    ];
  },
});

const app = createApp(Root);
app.use(vuetify);
app.use(bootstrap.plugin);

app.mount('#app');
bootstrap.validate({ warn: true, requireApi: false });
