// Generated by vuetify-ext bootstrap app
import { EnvironmentTag, StatusBadge, type AppMain, type AppShellContent } from 'vuetify-extended';

export function buildFooterStart(_app: AppMain): AppShellContent[] {
  return [
    new StatusBadge({
      text: 'vuetify-extended Starter',
      icon: 'mdi-flask-outline',
      color: 'primary',
      variant: 'outlined',
    }),
  ];
}

export function buildFooterCenter(_app: AppMain): AppShellContent[] {
  return [
    new EnvironmentTag({
      text: 'Bootstrap + Pages + Menu',
      color: 'secondary',
      variant: 'outlined',
    }),
  ];
}

export function buildFooterEnd(_app: AppMain): AppShellContent[] {
  return [
    new StatusBadge({
      text: 'Home Page Ready',
      icon: 'mdi-home-outline',
      color: 'success',
      variant: 'tonal',
    }),
  ];
}
