// Generated by vuetify-ext bootstrap app
import { AppTitleBlock, EnvironmentTag, StatusBadge, type AppMain, type AppShellContent, $ATB, $ENV, $SIA, $STB, $USR } from 'vuetify-extended';
import { Dialogs } from 'vuetify-extended';
// vuetify-ext:header-imports

export function buildHeaderStart(app: AppMain): AppShellContent[] {
  return [
    // vuetify-ext:header-start
    new AppTitleBlock({
      title: app.$params.title || 'My Workspace',
      subtitle: 'Built with vuetify-extended',
      overline: 'Workspace',
      icon: 'mdi-view-dashboard-outline',
      color: 'primary',
    }),
  ];
}

export function buildHeaderCenter(_app: AppMain): AppShellContent[] {
  return [
    // vuetify-ext:header-center
    new EnvironmentTag({
      text: 'Starter',
      color: 'info',
      variant: 'outlined',
    }),
  ];
}

export function buildHeaderEnd(_app: AppMain): AppShellContent[] {
  return [
    // vuetify-ext:header-end
    // vuetify-ext:header-item:end:user:workspace-user
    $USR({
      name: "Workspace User",
      subtitle: "CLI Demo User",
      email: 'user@example.com',
      avatarColor: "primary",
    }),
    // vuetify-ext:header-item:end:action:toggle-language
    $SIA(
      {
        icon: "mdi-translate",
        title: "Toggle Language",
        color: "secondary",
      },
      {
        onClicked: () => {
          Dialogs.$info("Toggle Language clicked.");
        },
      },
    ),
    new StatusBadge({
      text: 'Ready',
      icon: 'mdi-check-circle-outline',
      color: 'success',
      variant: 'tonal',
    }),
  ];
}
