// Generated by vuetify-ext bootstrap app
import { AppMain, createVuetifyExtendedApp, type VuetifyExtendedAppFactoryOptions } from 'vuetify-extended';
import { createApiConfig } from '../api';
import { createMainMenu } from '../menu';
import { buildHeaderCenter, buildHeaderEnd, buildHeaderStart } from './header';
import { buildFooterCenter, buildFooterEnd, buildFooterStart } from './footer';

export interface InitializeBootstrapOptions {
  bootstrap?: Partial<VuetifyExtendedAppFactoryOptions>;
}

export function createMainApp(): AppMain {
  return new AppMain(
    {
      ref: 'main-app',
      title: 'My Workspace',
      showHeader: true,
      showFooter: true,
      showFab: false,
    },
    {
      menu: async () => createMainMenu(),
      headerStart: buildHeaderStart,
      headerCenter: buildHeaderCenter,
      headerEnd: buildHeaderEnd,
      footerStart: buildFooterStart,
      footerCenter: buildFooterCenter,
      footerEnd: buildFooterEnd,
    },
  );
}

export function initializeBootstrap(options: InitializeBootstrapOptions = {}) {
  const api = createApiConfig();

  return createVuetifyExtendedApp({
    requireApi: false,
    ...(api ? { api } : {}),
    app: createMainApp(),
    dialogs: {
      progressSize: 96,
      progressWidth: 10,
      successTimeout: 2400,
      warningTimeout: 3200,
      errorTimeout: 4200,
    },
    notifications: {
      location: 'top-right',
      maxVisible: 4,
      defaultTimeout: 3600,
    },
    ...(options.bootstrap || {}),
  });
}
