// Generated by vuetify-ext bootstrap theme
export type AppThemeMode = 'light' | 'dark';

export const APP_THEME_STORAGE_KEY = 'vuetify-extended-theme-mode';

export function getThemeMode(): AppThemeMode {
  if (typeof window === 'undefined') {
    return "light";
  }

  const stored = window.localStorage.getItem(APP_THEME_STORAGE_KEY);
  if (stored === 'light' || stored === 'dark') {
    return stored;
  }

  return "light";
}

export function setThemeMode(mode: AppThemeMode) {
  if (typeof window !== 'undefined') {
    window.localStorage.setItem(APP_THEME_STORAGE_KEY, mode);
  }
  return mode;
}

export function toggleThemeMode(): AppThemeMode {
  const nextMode = getThemeMode() === 'dark' ? 'light' : 'dark';
  return setThemeMode(nextMode);
}

export function createVuetifyThemeOptions() {
  return {
    defaultTheme: getThemeMode(),
    themes: {
      light: {
        dark: false,
        colors: {
          primary: '#1867c0',
          secondary: '#5cbbf6',
          success: '#2e7d32',
          info: '#0288d1',
          warning: '#ed6c02',
          error: '#d32f2f',
          background: '#f5f7fb',
          surface: '#ffffff',
        },
      },
      dark: {
        dark: true,
        colors: {
          primary: '#90caf9',
          secondary: '#80cbc4',
          success: '#81c784',
          info: '#4fc3f7',
          warning: '#ffb74d',
          error: '#ef9a9a',
          background: '#0f172a',
          surface: '#111827',
        },
      },
    },
  };
}
