// Generated by vuetify-ext create report
import { $FD, $FM, $PT, type ReportMode } from 'vuetify-extended';

export function createPeopleForm(mode: ReportMode = 'display') {
  return $FM(
    {
      title: "People Workspace Form",
      mode,
      width: 920,
    },
    {
      children: () => [
        // vuetify-ext:form-parts
        $PT(
          { cols: 12, dense: true },
          {
            children: () => [
              // vuetify-ext:part:2:fields
              $FD({
                type: 'label',
                label: "Profile Notes",
                cols: 12,
              }),
              $FD({
                label: "Profile Notes Notes",
                storage: "profile-notesNotes",
                type: 'textarea',
                cols: 12,
              }),
            ],
          },
        ),
        $PT(
          { cols: 12, dense: true },
          {
            children: () => [
              // vuetify-ext:part:1:fields
              // vuetify-ext:field:email
              $FD({
                label: "Email",
                storage: "email",
                cols: 6,
                required: true,
              }),
              $FD({
                label: 'Name',
                storage: 'name',
                cols: 6,
                required: true,
              }),
              $FD({
                label: 'Code',
                storage: 'code',
                cols: 6,
              }),
              $FD({
                label: 'Description',
                storage: 'description',
                type: 'textarea',
                cols: 12,
              }),
              $FD({
                type: 'label',
                label: 'Replace these starter fields with the real form schema for this page.',
                cols: 12,
              }),
            ],
          },
        ),
      ],
    },
  );
}
