// Generated by vuetify-ext create trigger
import { $FD, $TG, type NavigationEntry, type ReportMode, $BN } from 'vuetify-extended';

const PEOPLE_HEADERS = [
  { title: 'Name', key: 'name' },
  { title: 'Description', key: 'description' },
  { title: 'Status', key: 'status' },
];

const PEOPLE_ROWS = [
  { _id: 'finder-1', name: 'Finder Example 1', description: 'Starter row one', status: 'active' },
  { _id: 'finder-2', name: 'Finder Example 2', description: 'Starter row two', status: 'draft' },
  { _id: 'finder-3', name: 'Finder Example 3', description: 'Starter row three', status: 'archived' },
];

export function createFinderTrigger(mode: ReportMode = "edit") {
  return (entry?: NavigationEntry) => {
    const resolvedMode = (entry?.mode as ReportMode | undefined) || mode;
    return $TG(
      {
        title: "Finder Trigger Trigger",
        subtitle: 'Starter trigger generated by vuetify-ext.',
        objectType: "people",
        idField: "_id",
        multiple: false,
        mode: resolvedMode,
        queryFields: ['name', 'description', 'status'],
        headers: PEOPLE_HEADERS,
        fluid: true,
        canPrint: false,
        canExport: false,
      },
      {
        headers: async () => PEOPLE_HEADERS,
        load: async (searchText) => {
          const search = String(searchText || '').trim().toLowerCase();
          if (!search) {
            return PEOPLE_ROWS;
          }

          return PEOPLE_ROWS.filter((item) =>
            ['name', 'description', 'status'].some((key) =>
              String((item as Record<string, any>)[key] || '').toLowerCase().includes(search),
            ),
          );
        },
              searchFields: async () => ({
        fields: [
          // vuetify-ext:trigger-search-fields
          // vuetify-ext:trigger-field:status
          $FD({
            label: "Status",
            storage: "status",
            type: "select",
            cols: 6,
          }),
        ],
      }),
      topChildren: () => [
          $FD({
            type: 'label',
            label: 'Replace the in-memory load() function with your API-backed query when ready.',
            cols: 12,
          }),
        ],
      sideButtons: (_props, _context, trigger) => [
        // vuetify-ext:trigger-side-actions
        // vuetify-ext:trigger-action:bulk-approve
        $BN(
          {
            text: "Bulk Approve",
            icon: "mdi-check",
            color: "success",
            variant: "outlined",
          },
          {
            onClicked: () => {
              trigger.emit('side-action', "bulk-approve");
              Dialogs.$success("Bulk Approve clicked.");
            },
          },
        ),
      ],
      },
    );
  };
}
