// Generated by vuetify-ext bootstrap app
import { $RP, type NavigationEntry, type ReportMode } from 'vuetify-extended';
import { createHomeForm } from './form';

export function createHomeReport(mode: ReportMode = 'display') {
  return (entry?: NavigationEntry) => {
    const resolvedMode = (entry?.mode as ReportMode | undefined) || mode;
    return $RP(
      {
        title: 'Home',
        forms: 1,
        mode: resolvedMode,
        horizontalAlign: 'center',
        verticalAlign: 'start',
        fluid: true,
      },
      {
        form: async () => createHomeForm(),
      },
    );
  };
}
