// Generated by vuetify-ext create dialog form
import { $DF, $FD, $FM, $PT, type ReportMode } from 'vuetify-extended';

export function createQuickEditDialogForm(mode: ReportMode = "create") {
  return $DF(
    {
      ref: "quick-edit",
      closeOnSave: true,
      mode,
    },
    {
      form: async () =>
        $FM(
          {
            title: "Quick Edit",
            mode,
            width: 760,
          },
          {
            children: () => [
              $PT(
                { cols: 12, dense: true },
                {
                  children: () => [
                    $FD({
                      label: 'Title',
                      storage: 'title',
                      cols: 6,
                      required: true,
                    }),
                    $FD({
                      label: 'Owner',
                      storage: 'owner',
                      cols: 6,
                    }),
                    $FD({
                      label: 'Summary',
                      storage: 'summary',
                      type: 'textarea',
                      cols: 12,
                    }),
                  ],
                },
              ),
            ],
          },
        ),
    },
  );
}
