import fs from 'node:fs';
import path from 'node:path';
import * as readline from 'node:readline';
import {
  CreateCommandOptions,
  runCreateCollectionCommand,
  runCreateMenuItemCommand,
  runCreateReportCommand,
  runCreateTriggerCommand,
} from './create-ui';

type ScriptExt = '.ts' | '.js';
type ReportMode = 'create' | 'edit' | 'display';
type PageKind = 'report' | 'trigger' | 'collection' | 'dashboard';
type DashboardTheme = 'light' | 'dark';
type DashboardSection = 'top' | 'main' | 'bottom';
type DashboardWidgetKind =
  | 'metric'
  | 'table'
  | 'list'
  | 'progress'
  | 'chart'
  | 'trend'
  | 'timeline'
  | 'action-list'
  | 'alert'
  | 'empty-state'
  | 'stat-grid'
  | 'map'
  | 'calendar'
  | 'tabs';

interface DashboardAnswers {
  name: string;
  title: string;
  theme: DashboardTheme;
  withMenuItem: boolean;
}

interface PageAnswers {
  type: PageKind;
  name: string;
  title: string;
  objectType?: string;
  mode?: ReportMode;
  forms?: number;
  idField?: string;
  multiple?: boolean;
  withReport?: boolean;
  withTrigger?: boolean;
  theme?: DashboardTheme;
  withMenuItem: boolean;
}

interface FieldAnswers {
  page: string;
  step: number;
  part: number;
  label: string;
  storage: string;
  type: string;
  cols: number;
  required: boolean;
}

interface PartAnswers {
  page: string;
  step: number;
  title: string;
  cols: number;
}

interface DashboardWidgetAnswers {
  page: string;
  widgetType: DashboardWidgetKind;
  section: DashboardSection;
  title: string;
  subtitle?: string;
}

interface ServiceAnswers {
  name: string;
  path: string;
}

interface ValidatorAnswers {
  name: string;
  kind: 'field' | 'rule-array';
}

interface FileWrite {
  file: string;
  content: string;
}

const GENERATED_MARKER = '// Generated by vuetify-ext';
const FORM_PARTS_MARKER = '// vuetify-ext:form-parts';
const FORM_FIELDS_MARKER_PREFIX = '// vuetify-ext:part:';
const DASHBOARD_IMPORT_MARKER = '// vuetify-ext:dashboard-imports';
const DASHBOARD_TOP_MARKER = '// vuetify-ext:dashboard-top-widgets';
const DASHBOARD_MAIN_MARKER = '// vuetify-ext:dashboard-widgets';
const DASHBOARD_BOTTOM_MARKER = '// vuetify-ext:dashboard-bottom-widgets';

export async function runCreateDashboardCommand(options: CreateCommandOptions): Promise<number> {
  const ext = resolveProjectScriptExtension(options.cwd);
  const answers = await resolveDashboardAnswers(options);
  if (!answers) {
    return 1;
  }

  const pageDir = path.join(options.cwd, 'src/pages', answers.name);
  const pascalName = toPascalCase(answers.name);
  const writes: FileWrite[] = [
    {
      file: path.join(pageDir, `dashboard${ext}`),
      content: buildDashboardFileSource(ext, answers, pascalName),
    },
  ];

  const prepare = prepareWrites(options, writes);
  if (prepare === 'error') {
    return 1;
  }
  if (prepare === 'dry-run') {
    options.stdout.write(`- ${relativeToCwd(options.cwd, path.join(pageDir, `index${ext}`))}\n`);
    return 0;
  }

  writeFiles(writes);
  ensureIndexExports(pageDir, ext, [`export { create${pascalName}Dashboard } from './dashboard';`]);

  if (answers.withMenuItem) {
    const menuStatus = await runCreateMenuItemCommand(withValues(options, {
      page: answers.name,
      target: 'dashboard',
      mode: 'display',
      text: answers.title,
      'sub-text': `Open the ${answers.title} dashboard.`,
      icon: 'mdi-view-dashboard-outline',
      color: 'primary',
    }));
    if (menuStatus !== 0) {
      return menuStatus;
    }
  }

  writeSuccess(options, 'Dashboard scaffolding created successfully', [
    ...writes.map((entry) => entry.file),
    path.join(pageDir, `index${ext}`),
  ]);
  return 0;
}

export async function runCreatePageCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolvePageAnswers(options);
  if (!answers) {
    return 1;
  }

  if (answers.type === 'dashboard') {
    return runCreateDashboardCommand(withValues(options, {
      name: answers.name,
      title: answers.title,
      theme: answers.theme || 'dark',
      'with-menu-item': String(answers.withMenuItem),
    }));
  }

  if (answers.type === 'report') {
    const status = await runCreateReportCommand(withValues(options, {
      name: answers.name,
      title: answers.title,
      'object-type': answers.objectType || answers.name,
      mode: answers.mode || 'display',
      forms: String(answers.forms || 1),
    }));
    if (status !== 0 || !answers.withMenuItem) {
      return status;
    }
    return runCreateMenuItemCommand(withValues(options, {
      page: answers.name,
      target: 'report',
      mode: answers.mode || 'display',
      text: answers.title,
    }));
  }

  if (answers.type === 'trigger') {
    const status = await runCreateTriggerCommand(withValues(options, {
      name: answers.name,
      title: answers.title,
      'object-type': answers.objectType || answers.name,
      'id-field': answers.idField || '_id',
      mode: answers.mode || 'edit',
      multiple: String(answers.multiple === true),
    }));
    if (status !== 0 || !answers.withMenuItem) {
      return status;
    }
    return runCreateMenuItemCommand(withValues(options, {
      page: answers.name,
      target: 'trigger',
      mode: answers.mode || 'edit',
      text: answers.title,
    }));
  }

  const status = await runCreateCollectionCommand(withValues(options, {
    name: answers.name,
    title: answers.title,
    'object-type': answers.objectType || answers.name,
    'id-field': answers.idField || '_id',
    mode: answers.mode || 'edit',
    multiple: String(answers.multiple === true),
    'with-report': String(answers.withReport !== false),
    'with-trigger': String(answers.withTrigger !== false),
  }));
  if (status !== 0 || !answers.withMenuItem) {
    return status;
  }
  return runCreateMenuItemCommand(withValues(options, {
    page: answers.name,
    target: 'collection',
    mode: answers.mode || 'edit',
    text: answers.title,
  }));
}

export async function runCreateFieldCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveFieldAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveExistingPageScriptExtension(options.cwd, answers.page) || resolveProjectScriptExtension(options.cwd);
  const formFile = resolveFormFile(options.cwd, answers.page, answers.step, ext);
  if (!fileExists(formFile)) {
    options.stderr.write(`[vuetify-ext] Form file not found: ${relativeToCwd(options.cwd, formFile)}\n`);
    return 1;
  }

  const fieldMarker = `// vuetify-ext:field:${answers.storage}`;
  let source = fs.readFileSync(formFile, 'utf8');
  if (source.includes(fieldMarker)) {
    writeSuccess(options, 'Field already present', [formFile]);
    return 0;
  }

  source = ensureFormScaffoldMarkers(source) || source;
  const partMarker = `${FORM_FIELDS_MARKER_PREFIX}${answers.part}:fields`;
  if (!source.includes(partMarker)) {
    options.stderr.write(
      `[vuetify-ext] Could not find part ${answers.part} in ${relativeToCwd(options.cwd, formFile)}.\n` +
        'Create the part first or run "vuetify-ext migrate --apply" to normalize scaffold markers.\n',
    );
    return 1;
  }

  const fieldBlock = buildFieldBlock(answers, fieldMarker);
  const next = source.replace(partMarker, `${partMarker}\n              ${fieldMarker}\n${fieldBlock}`);

  if (options.dryRun) {
    options.stdout.write(`[vuetify-ext] Dry run only. The following file would be updated:\n- ${relativeToCwd(options.cwd, formFile)}\n`);
    return 0;
  }

  fs.writeFileSync(formFile, next, 'utf8');
  writeSuccess(options, 'Field added successfully', [formFile]);
  return 0;
}

export async function runCreatePartCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolvePartAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveExistingPageScriptExtension(options.cwd, answers.page) || resolveProjectScriptExtension(options.cwd);
  const formFile = resolveFormFile(options.cwd, answers.page, answers.step, ext);
  if (!fileExists(formFile)) {
    options.stderr.write(`[vuetify-ext] Form file not found: ${relativeToCwd(options.cwd, formFile)}\n`);
    return 1;
  }

  let source = fs.readFileSync(formFile, 'utf8');
  source = ensureFormScaffoldMarkers(source) || source;
  if (!source.includes(FORM_PARTS_MARKER)) {
    options.stderr.write(`[vuetify-ext] Could not locate the form parts marker in ${relativeToCwd(options.cwd, formFile)}.\n`);
    return 1;
  }

  const nextPart = extractFormPartIndices(source).reduce((max, value) => Math.max(max, value), 0) + 1;
  const next = source.replace(FORM_PARTS_MARKER, `${FORM_PARTS_MARKER}\n${buildPartBlock(answers, nextPart)}`);

  if (options.dryRun) {
    options.stdout.write(`[vuetify-ext] Dry run only. The following file would be updated:\n- ${relativeToCwd(options.cwd, formFile)}\n`);
    return 0;
  }

  fs.writeFileSync(formFile, next, 'utf8');
  writeSuccess(options, 'Part added successfully', [formFile]);
  return 0;
}

export async function runCreateDashboardWidgetCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveDashboardWidgetAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveExistingPageScriptExtension(options.cwd, answers.page) || resolveProjectScriptExtension(options.cwd);
  const pageDir = path.join(options.cwd, 'src/pages', answers.page);
  const pascalName = toPascalCase(answers.page);
  const dashboardFile = path.join(pageDir, `dashboard${ext}`);
  const exportName = `create${pascalName}Dashboard`;

  if (!verifyExpectedPageExport(dashboardFile, exportName)) {
    options.stderr.write(
      `[vuetify-ext] ${relativeToCwd(options.cwd, dashboardFile)} is missing the expected export ${exportName}.\n`,
    );
    return 1;
  }

  const template = buildDashboardWidgetTemplate(answers);
  const normalizedSource = ensureDashboardMarkers(fs.readFileSync(dashboardFile, 'utf8'));
  if (!normalizedSource) {
    options.stderr.write(`[vuetify-ext] Could not normalize dashboard markers in ${relativeToCwd(options.cwd, dashboardFile)}.\n`);
    return 1;
  }
  let source = normalizedSource;

  const widgetMarker = `// vuetify-ext:dashboard-widget:${answers.section}:${answers.widgetType}:${slugifyName(answers.title)}`;
  if (source.includes(widgetMarker)) {
    writeSuccess(options, 'Dashboard widget already present', [dashboardFile]);
    return 0;
  }

  for (const importLine of template.imports) {
    if (!source.includes(importLine)) {
      source = source.replace(DASHBOARD_IMPORT_MARKER, `${DASHBOARD_IMPORT_MARKER}\n${importLine}`);
    }
  }

  const sectionMarker = answers.section === 'top' ? DASHBOARD_TOP_MARKER : answers.section === 'bottom' ? DASHBOARD_BOTTOM_MARKER : DASHBOARD_MAIN_MARKER;
  source = source.replace(sectionMarker, `${sectionMarker}\n        ${widgetMarker}\n${template.block}`);

  if (options.dryRun) {
    options.stdout.write(`[vuetify-ext] Dry run only. The following file would be updated:\n- ${relativeToCwd(options.cwd, dashboardFile)}\n`);
    return 0;
  }

  fs.writeFileSync(dashboardFile, source, 'utf8');
  writeSuccess(options, 'Dashboard widget added successfully', [dashboardFile]);
  return 0;
}

export async function runCreateServiceCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveServiceAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveProjectScriptExtension(options.cwd);
  const apiDir = path.join(options.cwd, 'src/api');
  const file = path.join(apiDir, `${answers.name}${ext}`);
  const indexFile = path.join(apiDir, `index${ext}`);
  const write = prepareWrites(options, [{ file, content: buildServiceFileSource(ext, answers) }]);
  if (write === 'error') {
    return 1;
  }
  if (write === 'dry-run') {
    options.stdout.write(`- ${relativeToCwd(options.cwd, indexFile)}\n`);
    return 0;
  }

  writeFiles([{ file, content: buildServiceFileSource(ext, answers) }]);
  ensureSimpleExport(indexFile, `export * from './${answers.name}';`);
  writeSuccess(options, 'Service scaffolding created successfully', [file, indexFile]);
  return 0;
}

export async function runCreateValidatorCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveValidatorAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveProjectScriptExtension(options.cwd);
  const validatorDir = path.join(options.cwd, 'src/validators');
  const file = path.join(validatorDir, `${answers.name}${ext}`);
  const indexFile = path.join(validatorDir, `index${ext}`);
  const write = prepareWrites(options, [{ file, content: buildValidatorFileSource(ext, answers) }]);
  if (write === 'error') {
    return 1;
  }
  if (write === 'dry-run') {
    options.stdout.write(`- ${relativeToCwd(options.cwd, indexFile)}\n`);
    return 0;
  }

  writeFiles([{ file, content: buildValidatorFileSource(ext, answers) }]);
  ensureSimpleExport(indexFile, `export * from './${answers.name}';`);
  writeSuccess(options, 'Validator scaffolding created successfully', [file, indexFile]);
  return 0;
}

export async function runDoctorCommand(options: CreateCommandOptions): Promise<number> {
  const issues: string[] = [];
  const fixes: string[] = [];

  const pagesDir = path.join(options.cwd, 'src/pages');
  if (!fs.existsSync(pagesDir)) {
    issues.push('Missing src/pages directory.');
  }
  if (!findExistingFile(options.cwd, ['src/menu/index.ts', 'src/menu/index.js'])) {
    issues.push('Missing src/menu/index.ts or src/menu/index.js.');
  }
  if (!findExistingFile(options.cwd, ['src/bootstrap/index.ts', 'src/bootstrap/index.js'])) {
    issues.push('Missing src/bootstrap/index.ts or src/bootstrap/index.js.');
  }
  if (!findExistingFile(options.cwd, ['src/api/index.ts', 'src/api/index.js'])) {
    issues.push('Missing src/api/index.ts or src/api/index.js.');
  }

  for (const page of listPageNames(options.cwd)) {
    const ext = resolveExistingPageScriptExtension(options.cwd, page) || resolveProjectScriptExtension(options.cwd);
    const pageDir = path.join(options.cwd, 'src/pages', page);
    const reportFile = path.join(pageDir, `report${ext}`);
    const formFile = path.join(pageDir, `form${ext}`);
    const dashboardFile = path.join(pageDir, `dashboard${ext}`);
    const indexFile = path.join(pageDir, `index${ext}`);
    const pascalName = toPascalCase(page);

    if (fileExists(reportFile)) {
      if (!verifyExpectedPageExport(reportFile, `create${pascalName}Report`)) {
        issues.push(`${relativeToCwd(options.cwd, reportFile)} is missing create${pascalName}Report.`);
      }
      const source = fs.readFileSync(reportFile, 'utf8');
      if (!source.includes('// vuetify-ext:report-form-imports') || !source.includes('// vuetify-ext:report-form-resolver')) {
        fixes.push(`${relativeToCwd(options.cwd, reportFile)} can be migrated to add report form markers.`);
      }
    }

    if (fileExists(formFile)) {
      const source = fs.readFileSync(formFile, 'utf8');
      if (!source.includes(FORM_PARTS_MARKER) || !source.includes(`${FORM_FIELDS_MARKER_PREFIX}1:fields`)) {
        fixes.push(`${relativeToCwd(options.cwd, formFile)} can be migrated to add form markers.`);
      }
    }

    if (fileExists(dashboardFile)) {
      const source = fs.readFileSync(dashboardFile, 'utf8');
      if (!source.includes(DASHBOARD_MAIN_MARKER)) {
        fixes.push(`${relativeToCwd(options.cwd, dashboardFile)} can be migrated to add dashboard markers.`);
      }
    }

    if (fileExists(indexFile)) {
      const source = fs.readFileSync(indexFile, 'utf8');
      const expectedExports = [
        fileExists(formFile) ? `create${pascalName}Form` : undefined,
        fileExists(reportFile) ? `create${pascalName}Report` : undefined,
        fileExists(path.join(pageDir, `trigger${ext}`)) ? `create${pascalName}Trigger` : undefined,
        fileExists(path.join(pageDir, `collection${ext}`)) ? `create${pascalName}Collection` : undefined,
        fileExists(dashboardFile) ? `create${pascalName}Dashboard` : undefined,
      ].filter(Boolean) as string[];

      for (const exportName of expectedExports) {
        if (!sourceIncludesNamedExport(source, exportName)) {
          fixes.push(`${relativeToCwd(options.cwd, indexFile)} is missing export ${exportName}.`);
        }
      }
    }
  }

  if (issues.length === 0 && fixes.length === 0) {
    options.stdout.write('[vuetify-ext] Doctor found no issues.\n');
    return 0;
  }

  if (issues.length > 0) {
    options.stdout.write('[vuetify-ext] Structural issues:\n');
    for (const issue of issues) {
      options.stdout.write(`- ${issue}\n`);
    }
  }
  if (fixes.length > 0) {
    options.stdout.write('[vuetify-ext] Recommended migrations:\n');
    for (const fix of fixes) {
      options.stdout.write(`- ${fix}\n`);
    }
  }

  return 1;
}

export async function runMigrateCommand(options: CreateCommandOptions): Promise<number> {
  const apply = parseOptionalBoolean(options.values?.apply) === true;
  const writes: FileWrite[] = [];

  for (const sourceFile of listSourceFiles(path.join(options.cwd, 'src'))) {
    const source = fs.readFileSync(sourceFile, 'utf8');
    const next = source.replace(/AppManager\.showUI\(([^)]+)\)/g, 'AppManager.showTrigger($1)');
    if (next !== source) {
      writes.push({ file: sourceFile, content: next });
    }
  }

  for (const page of listPageNames(options.cwd)) {
    const ext = resolveExistingPageScriptExtension(options.cwd, page) || resolveProjectScriptExtension(options.cwd);
    const pageDir = path.join(options.cwd, 'src/pages', page);
    const pascalName = toPascalCase(page);
    const reportFile = path.join(pageDir, `report${ext}`);
    const formFile = path.join(pageDir, `form${ext}`);
    const dashboardFile = path.join(pageDir, `dashboard${ext}`);
    const indexFile = path.join(pageDir, `index${ext}`);

    if (fileExists(reportFile)) {
      const source = fs.readFileSync(reportFile, 'utf8');
      const next = ensureReportMarkers(source, pascalName);
      if (next && next !== source) {
        writes.push({ file: reportFile, content: next });
      }
    }

    if (fileExists(formFile)) {
      const source = fs.readFileSync(formFile, 'utf8');
      const next = ensureFormScaffoldMarkers(source);
      if (next && next !== source) {
        writes.push({ file: formFile, content: next });
      }
    }

    if (fileExists(dashboardFile)) {
      const source = fs.readFileSync(dashboardFile, 'utf8');
      const next = ensureDashboardMarkers(source);
      if (next && next !== source) {
        writes.push({ file: dashboardFile, content: next });
      }
    }

    const exports: string[] = [];
    if (fileExists(formFile)) exports.push(`export { create${pascalName}Form } from './form';`);
    if (fileExists(reportFile)) exports.push(`export { create${pascalName}Report } from './report';`);
    if (fileExists(path.join(pageDir, `trigger${ext}`))) exports.push(`export { create${pascalName}Trigger } from './trigger';`);
    if (fileExists(path.join(pageDir, `collection${ext}`))) exports.push(`export { create${pascalName}Collection } from './collection';`);
    if (fileExists(dashboardFile)) exports.push(`export { create${pascalName}Dashboard } from './dashboard';`);

    for (const fileName of fs.readdirSync(pageDir).filter((entry) => /^form-\d+\.(ts|js)$/.test(entry))) {
      const step = Number(fileName.match(/^form-(\d+)\./)?.[1] || 0);
      if (step > 1) {
        exports.push(`export { create${pascalName}Form${step} } from './form-${step}';`);
      }
    }

    const nextIndex = appendLines(fileExists(indexFile) ? fs.readFileSync(indexFile, 'utf8') : `${GENERATED_MARKER} page index\n`, exports);
    if (!fileExists(indexFile) || nextIndex !== fs.readFileSync(indexFile, 'utf8')) {
      writes.push({ file: indexFile, content: nextIndex });
    }
  }

  if (writes.length === 0) {
    options.stdout.write('[vuetify-ext] No migrations were needed.\n');
    return 0;
  }

  if (!apply || options.dryRun) {
    options.stdout.write('[vuetify-ext] The following files would be updated:\n');
    for (const write of uniqueWrites(writes)) {
      options.stdout.write(`- ${relativeToCwd(options.cwd, write.file)}\n`);
    }
    options.stdout.write('Re-run with --apply to write the changes.\n');
    return 0;
  }

  writeFiles(uniqueWrites(writes));
  writeSuccess(options, 'Migration completed successfully', uniqueWrites(writes).map((entry) => entry.file));
  return 0;
}

function buildDashboardFileSource(ext: ScriptExt, answers: DashboardAnswers, pascalName: string) {
  const typeImport = ext === '.ts' ? ', type NavigationEntry' : '';
  const entrySignature = ext === '.ts' ? '_entry?: NavigationEntry' : '_entry';
  const keyBase = pageTextKey(answers.name, 'dashboard');
  return `${GENERATED_MARKER} create dashboard
import { $DB, $DLW, $DMW, $MI, Dialogs${typeImport} } from 'vuetify-extended';
${DASHBOARD_IMPORT_MARKER}

export function create${pascalName}Dashboard() {
  return (${entrySignature}) =>
    $DB(
      {
        title: ${serializeUITextDescriptor(`${keyBase}.title`, answers.title)},
        subtitle: ${serializeUITextDescriptor(`${keyBase}.subtitle`, 'Starter dashboard generated by vuetify-ext.')},
        fluid: true,
        theme: ${serializeString(answers.theme)},
      },
      {
        menuItems: async () => [
          $MI(
            {
              action: 'function',
              text: ${serializeUITextDescriptor(`${keyBase}.menu.action.text`, 'Dashboard Action')},
              subText: ${serializeUITextDescriptor(`${keyBase}.menu.action.subText`, 'Starter dashboard menu item.')},
              icon: 'mdi-dots-horizontal-circle-outline',
              color: 'primary',
            },
            {
              callback: async () => {
                Dialogs.$success(${serializeUITextDescriptor(`${keyBase}.menu.action.success`, 'Dashboard action clicked.')});
              },
            },
          ),
        ],
        topChildren: () => [
          ${DASHBOARD_TOP_MARKER}
          $DMW({
            title: ${serializeUITextDescriptor(`${keyBase}.widgets.activeUsers.title`, 'Active Users')},
            value: 128,
            caption: 'Last 24 hours',
            icon: 'mdi-account-group-outline',
            cols: 12,
            sm: 6,
            lg: 3,
          }),
          $DMW({
            title: ${serializeUITextDescriptor(`${keyBase}.widgets.revenue.title`, 'Revenue')},
            value: '$12,450',
            caption: 'Starter metric',
            icon: 'mdi-cash-multiple',
            cols: 12,
            sm: 6,
            lg: 3,
          }),
        ],
        children: () => [
          ${DASHBOARD_MAIN_MARKER}
          $DLW({
            title: ${serializeUITextDescriptor(`${keyBase}.widgets.recentActivity.title`, 'Recent Activity')},
            cols: 12,
            lg: 6,
            items: [
              { title: 'Replace this widget', subtitle: 'Use "vuetify-ext create dashboard-widget" to add more cards.' },
              { title: 'Connect data', subtitle: 'Swap starter items for real API-backed values.' },
            ],
          }),
        ],
        bottomChildren: () => [
          ${DASHBOARD_BOTTOM_MARKER}
        ],
      },
    );
}
`;
}

function buildFieldBlock(answers: FieldAnswers, marker: string) {
  const lines = [
    `              $FD({`,
    `                label: ${serializeUITextDescriptor(pageTextKey(answers.page, 'form', 'fields', answers.storage, 'label'), answers.label)},`,
    `                storage: ${serializeString(answers.storage)},`,
  ];
  if (answers.type !== 'text') {
    lines.push(`                type: ${serializeString(answers.type)},`);
  }
  lines.push(`                cols: ${answers.cols},`);
  if (answers.required) {
    lines.push(`                required: true,`);
  }
  lines.push(`              }),`);
  return `${lines.join('\n')}`;
}

function buildPartBlock(answers: PartAnswers, partNumber: number) {
  const storage = `${slugifyName(answers.title)}Notes`;
  const keyBase = pageTextKey(answers.page, 'form', 'parts', `part${partNumber}`);
  return `        $PT(
          { cols: ${answers.cols}, dense: true },
          {
            children: () => [
              ${FORM_FIELDS_MARKER_PREFIX}${partNumber}:fields
              $FD({
                type: 'label',
                label: ${serializeUITextDescriptor(`${keyBase}.title`, answers.title)},
                cols: 12,
              }),
              $FD({
                label: ${serializeUITextDescriptor(`${keyBase}.notes.label`, `${answers.title} Notes`)},
                storage: ${serializeString(storage)},
                type: 'textarea',
                cols: 12,
              }),
            ],
          },
        ),`;
}

function buildDashboardWidgetTemplate(answers: DashboardWidgetAnswers): { imports: string[]; block: string } {
  const keyBase = pageTextKey(answers.page, 'dashboard', 'widgets', slugifyName(answers.title));
  const title = serializeUITextDescriptor(`${keyBase}.title`, answers.title);
  const subtitleLine = answers.subtitle ? `\n          subtitle: ${serializeUITextDescriptor(`${keyBase}.subtitle`, answers.subtitle)},` : '';
  const baseCols = `          cols: 12,\n          lg: 4,`;
  const templates: Record<DashboardWidgetKind, { imports: string[]; block: string }> = {
    metric: {
      imports: [`import { $DMW } from 'vuetify-extended';`],
      block: `        $DMW({\n          title: ${title},${subtitleLine}\n          value: 128,\n          caption: 'Starter metric',\n          icon: 'mdi-chart-box-outline',\n${baseCols}\n        }),`,
    },
    table: {
      imports: [`import { $DTW } from 'vuetify-extended';`],
      block: `        $DTW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          headers: [\n            { key: 'name', title: 'Name' },\n            { key: 'status', title: 'Status' },\n          ],\n          items: [\n            { name: 'Starter Row 1', status: 'active' },\n            { name: 'Starter Row 2', status: 'draft' },\n          ],\n          pagination: true,\n          pageSize: 5,\n          showSearch: true,\n        }),`,
    },
    list: {
      imports: [`import { $DLW } from 'vuetify-extended';`],
      block: `        $DLW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          items: [\n            { title: 'Starter item', subtitle: 'Replace with real list data' },\n            { title: 'Another item', subtitle: 'List widgets are good for compact summaries' },\n          ],\n        }),`,
    },
    progress: {
      imports: [`import { $DPW } from 'vuetify-extended';`],
      block: `        $DPW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          items: [\n            { label: 'North Region', value: '$12k', amount: 72, color: 'primary' },\n            { label: 'South Region', value: '$8k', amount: 48, color: 'success' },\n          ],\n        }),`,
    },
    chart: {
      imports: [`import { $DCHW } from 'vuetify-extended';`],
      block: `        $DCHW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          chartType: 'bar',\n          chartHeight: 220,\n          items: [\n            { label: 'Jan', value: 12 },\n            { label: 'Feb', value: 18 },\n            { label: 'Mar', value: 9 },\n          ],\n        }),`,
    },
    trend: {
      imports: [`import { $DTrW } from 'vuetify-extended';`],
      block: `        $DTrW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          value: '18.4%',\n          delta: '+4.6% MoM',\n          trend: 'up',\n          caption: 'Starter trend widget',\n          sparklineValues: [8, 12, 9, 15, 18, 16, 20],\n        }),`,
    },
    timeline: {
      imports: [`import { $DTLW } from 'vuetify-extended';`],
      block: `        $DTLW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          items: [\n            { title: 'Order approved', time: '08:45', description: 'Starter timeline entry', color: 'success' },\n            { title: 'Shipment prepared', time: '10:15', description: 'Replace with real events', color: 'primary' },\n          ],\n        }),`,
    },
    'action-list': {
      imports: [`import { $DALW } from 'vuetify-extended';`],
      block: `        $DALW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          items: [\n            { title: 'Review backlog', subtitle: '12 open tasks', actionText: 'Open' },\n            { title: 'Approve invoices', subtitle: '3 pending approvals', actionText: 'Review' },\n          ],\n        }),`,
    },
    alert: {
      imports: [`import { $DAW } from 'vuetify-extended';`],
      block: `        $DAW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          items: [\n            { severity: 'warning', title: 'Low inventory', message: 'Warehouse stock is below threshold' },\n            { severity: 'info', title: 'Planned maintenance', message: 'Starter alert item' },\n          ],\n        }),`,
    },
    'empty-state': {
      imports: [`import { $DESW } from 'vuetify-extended';`],
      block: `        $DESW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          titleText: 'No records connected',\n          message: 'Replace this empty state with your real onboarding or no-data copy.',\n          icon: 'mdi-database-off-outline',\n          buttonText: 'Connect Source',\n        }),`,
    },
    'stat-grid': {
      imports: [`import { $DSGW } from 'vuetify-extended';`],
      block: `        $DSGW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          columns: 2,\n          items: [\n            { label: 'MRR', value: '$12.4k' },\n            { label: 'Churn', value: '3.1%' },\n            { label: 'CSAT', value: '92%' },\n            { label: 'NPS', value: 44 },\n          ],\n        }),`,
    },
    map: {
      imports: [`import { $DMaW } from 'vuetify-extended';`],
      block: `        $DMaW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          mapHeight: 220,\n          data: {\n            center: { lat: 51.5074, lng: -0.1278 },\n            markers: [\n              { lat: 51.5074, lng: -0.1278, label: 'HQ' },\n              { lat: 48.8566, lng: 2.3522, label: 'Paris' },\n            ],\n          },\n        }),`,
    },
    calendar: {
      imports: [`import { $DCaW } from 'vuetify-extended';`],
      block: `        $DCaW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          year: 2026,\n          month: 3,\n          items: [\n            { date: '2026-03-10', title: 'Planning' },\n            { date: '2026-03-14', title: 'Review' },\n          ],\n        }),`,
    },
    tabs: {
      imports: [`import { $DTabW } from 'vuetify-extended';`],
      block: `        $DTabW({\n          title: ${title},${subtitleLine}\n${baseCols}\n          tabs: [\n            { label: 'Overview' },\n            { label: 'Notes' },\n            { label: 'Archive' },\n          ],\n        }),`,
    },
  };

  return templates[answers.widgetType];
}

function buildServiceFileSource(ext: ScriptExt, answers: ServiceAnswers) {
  const pascalName = toPascalCase(answers.name);
  const constantName = `${sanitizeIdentifier(answers.name).toUpperCase()}_SERVICE_PATH`;
  if (ext === '.ts') {
    return `${GENERATED_MARKER} create service
import { Api } from 'vuetify-extended';

export const ${constantName} = ${serializeString(answers.path)};

export type ${pascalName}Id = string | number;

export interface ${pascalName}Entity {
  [key: string]: any;
}

export interface ${pascalName}CreateData extends Partial<${pascalName}Entity> {}

export interface ${pascalName}PatchData extends Partial<${pascalName}Entity> {}

export interface ${pascalName}Query {
  [key: string]: any;
}

export interface ${pascalName}Params {
  query?: ${pascalName}Query;
  [key: string]: any;
}

export function get${pascalName}Service() {
  return Api.instance.service(${constantName});
}

export async function find${pascalName}(params?: ${pascalName}Params): Promise<any> {
  return get${pascalName}Service().find(params);
}

export async function get${pascalName}(id: ${pascalName}Id, params?: ${pascalName}Params): Promise<${pascalName}Entity> {
  return get${pascalName}Service().get(id, params);
}

export async function create${pascalName}(data: ${pascalName}CreateData, params?: ${pascalName}Params): Promise<${pascalName}Entity> {
  return get${pascalName}Service().create(data, params);
}

export async function patch${pascalName}(id: ${pascalName}Id, data: ${pascalName}PatchData, params?: ${pascalName}Params): Promise<${pascalName}Entity> {
  return get${pascalName}Service().patch(id, data, params);
}

export async function remove${pascalName}(id: ${pascalName}Id, params?: ${pascalName}Params): Promise<${pascalName}Entity> {
  return get${pascalName}Service().remove(id, params);
}
`;
  }

  return `${GENERATED_MARKER} create service
import { Api } from 'vuetify-extended';

export const ${constantName} = ${serializeString(answers.path)};

export function get${pascalName}Service() {
  return Api.instance.service(${constantName});
}

export async function find${pascalName}(params) {
  return get${pascalName}Service().find(params);
}

export async function get${pascalName}(id, params) {
  return get${pascalName}Service().get(id, params);
}

export async function create${pascalName}(data, params) {
  return get${pascalName}Service().create(data, params);
}

export async function patch${pascalName}(id, data, params) {
  return get${pascalName}Service().patch(id, data, params);
}

export async function remove${pascalName}(id, params) {
  return get${pascalName}Service().remove(id, params);
}
`;
}

function buildValidatorFileSource(ext: ScriptExt, answers: ValidatorAnswers) {
  const pascalName = toPascalCase(answers.name);
  return `${GENERATED_MARKER} create validator
import { $v } from 'vuetify-extended';

export const ${sanitizeIdentifier(answers.name)}Rules = [
  $v.isRequired(),
  $v.maxLen(120),
];

export function validate${pascalName}(value${ext === '.ts' ? ': any' : ''}) {
  for (const rule of ${sanitizeIdentifier(answers.name)}Rules) {
    const result = rule(value);
    if (result !== true) {
      return result;
    }
  }
  return true;
}
`;
}

async function resolveDashboardAnswers(options: CreateCommandOptions): Promise<DashboardAnswers | undefined> {
  const values = options.values || {};
  const input = {
    name: values.name || options.positionals?.[0],
    title: values.title,
    theme: values.theme as DashboardTheme | undefined,
    withMenuItem: parseOptionalBoolean(values['with-menu-item']),
  };

  if (!options.interactive) {
    if (!input.name || !input.title) {
      options.stderr.write('[vuetify-ext] Missing required flags for create dashboard:\n- --name\n- --title\n');
      return undefined;
    }
    return {
      name: slugifyName(input.name),
      title: input.title,
      theme: input.theme || 'dark',
      withMenuItem: input.withMenuItem === true,
    };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const name = slugifyName(await promptText(rl, 'Dashboard page/folder', input.name || 'operations-dashboard'));
    const title = await promptText(rl, 'Dashboard title', input.title || humanizeName(name));
    const theme = await promptChoice(rl, 'Dashboard theme (light/dark)', ['light', 'dark'], input.theme || 'dark') as DashboardTheme;
    const withMenuItem = await promptBoolean(rl, 'Add dashboard to the main menu', input.withMenuItem === true);
    return { name, title, theme, withMenuItem };
  } finally {
    rl.close();
  }
}

async function resolvePageAnswers(options: CreateCommandOptions): Promise<PageAnswers | undefined> {
  const values = options.values || {};
  const input = {
    type: (values.type || values.target || options.positionals?.[0]) as PageKind | undefined,
    name: values.name || options.positionals?.[1],
    title: values.title,
    objectType: values['object-type'],
    mode: values.mode as ReportMode | undefined,
    forms: normalizePositiveInt(values.forms, 1),
    idField: values['id-field'],
    multiple: parseOptionalBoolean(values.multiple),
    withReport: parseOptionalBoolean(values['with-report']),
    withTrigger: parseOptionalBoolean(values['with-trigger']),
    theme: values.theme as DashboardTheme | undefined,
    withMenuItem: parseOptionalBoolean(values['with-menu-item']),
  };

  if (!options.interactive) {
    if (!input.type || !input.name || !input.title) {
      options.stderr.write('[vuetify-ext] Missing required flags for create page:\n- --type\n- --name\n- --title\n');
      return undefined;
    }
    return {
      type: input.type,
      name: slugifyName(input.name),
      title: input.title,
      objectType: input.objectType,
      mode: input.mode,
      forms: input.forms,
      idField: input.idField,
      multiple: input.multiple === true,
      withReport: input.withReport !== false,
      withTrigger: input.withTrigger !== false,
      theme: input.theme || 'dark',
      withMenuItem: input.withMenuItem === true,
    };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const type = await promptChoice(rl, 'Page type (report/trigger/collection/dashboard)', ['report', 'trigger', 'collection', 'dashboard'], input.type || 'report') as PageKind;
    const name = slugifyName(await promptText(rl, 'Page name/folder', input.name || `sample-${type}`));
    const title = await promptText(rl, 'Page title', input.title || humanizeName(name));
    const withMenuItem = await promptBoolean(rl, 'Add page to the main menu', input.withMenuItem === true);

    if (type === 'dashboard') {
      const theme = await promptChoice(rl, 'Dashboard theme (light/dark)', ['light', 'dark'], input.theme || 'dark') as DashboardTheme;
      return { type, name, title, theme, withMenuItem };
    }

    const objectType = await promptText(rl, 'Object type', input.objectType || slugifyName(name));
    const mode = await promptChoice(rl, 'Default mode (create/edit/display)', ['create', 'edit', 'display'], input.mode || (type === 'report' ? 'display' : 'edit')) as ReportMode;
    if (type === 'report') {
      const forms = await promptNumber(rl, 'Number of forms/steps', input.forms || 1, 1);
      return { type, name, title, objectType, mode, forms, withMenuItem };
    }

    const idField = await promptText(rl, 'ID field', input.idField || '_id');
    const multiple = await promptBoolean(rl, 'Allow multiple selection', input.multiple === true);
    if (type === 'trigger') {
      return { type, name, title, objectType, mode, idField, multiple, withMenuItem };
    }

    const withReport = await promptBoolean(rl, 'Scaffold a companion report', input.withReport !== false);
    const withTrigger = await promptBoolean(rl, 'Scaffold a companion trigger', input.withTrigger !== false);
    return { type, name, title, objectType, mode, idField, multiple, withReport, withTrigger, withMenuItem };
  } finally {
    rl.close();
  }
}

async function resolveFieldAnswers(options: CreateCommandOptions): Promise<FieldAnswers | undefined> {
  const values = options.values || {};
  const input = {
    page: values.page || options.positionals?.[0],
    step: normalizePositiveInt(values.step, 1),
    part: normalizePositiveInt(values.part, 1),
    label: values.label,
    storage: values.storage,
    type: values.type || 'text',
    cols: normalizePositiveInt(values.cols, 12),
    required: parseOptionalBoolean(values.required),
  };

  if (!options.interactive) {
    if (!input.page || !input.label || !input.storage) {
      options.stderr.write('[vuetify-ext] Missing required flags for create field:\n- --page\n- --label\n- --storage\n');
      return undefined;
    }
    return {
      page: slugifyName(input.page),
      step: input.step,
      part: input.part,
      label: input.label,
      storage: input.storage,
      type: input.type,
      cols: input.cols,
      required: input.required === true,
    };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const page = slugifyName(await promptText(rl, 'Page folder name', input.page || 'sample-report'));
    const step = await promptNumber(rl, 'Form step number', input.step, 1);
    const part = await promptNumber(rl, 'Part number', input.part, 1);
    const label = await promptText(rl, 'Field label', input.label || 'New Field');
    const storage = await promptText(rl, 'Field storage key', input.storage || slugifyName(label));
    const type = await promptText(rl, 'Field type', input.type || 'text');
    const cols = await promptNumber(rl, 'Grid columns', input.cols, 1);
    const required = await promptBoolean(rl, 'Required field', input.required === true);
    return { page, step, part, label, storage, type, cols, required };
  } finally {
    rl.close();
  }
}

async function resolvePartAnswers(options: CreateCommandOptions): Promise<PartAnswers | undefined> {
  const values = options.values || {};
  const input = {
    page: values.page || options.positionals?.[0],
    step: normalizePositiveInt(values.step, 1),
    title: values.title,
    cols: normalizePositiveInt(values.cols, 12),
  };

  if (!options.interactive) {
    if (!input.page || !input.title) {
      options.stderr.write('[vuetify-ext] Missing required flags for create part:\n- --page\n- --title\n');
      return undefined;
    }
    return { page: slugifyName(input.page), step: input.step, title: input.title, cols: input.cols };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const page = slugifyName(await promptText(rl, 'Page folder name', input.page || 'sample-report'));
    const step = await promptNumber(rl, 'Form step number', input.step, 1);
    const title = await promptText(rl, 'Part section title', input.title || 'New Section');
    const cols = await promptNumber(rl, 'Part columns', input.cols, 1);
    return { page, step, title, cols };
  } finally {
    rl.close();
  }
}

async function resolveDashboardWidgetAnswers(options: CreateCommandOptions): Promise<DashboardWidgetAnswers | undefined> {
  const values = options.values || {};
  const input = {
    page: values.page || options.positionals?.[0],
    widgetType: (values.type || values.widget || options.positionals?.[1]) as DashboardWidgetKind | undefined,
    section: (values.section || 'main') as DashboardSection,
    title: values.title,
    subtitle: values.subtitle,
  };

  const widgetTypes = ['metric', 'table', 'list', 'progress', 'chart', 'trend', 'timeline', 'action-list', 'alert', 'empty-state', 'stat-grid', 'map', 'calendar', 'tabs'];

  if (!options.interactive) {
    if (!input.page || !input.widgetType || !input.title) {
      options.stderr.write('[vuetify-ext] Missing required flags for create dashboard-widget:\n- --page\n- --type\n- --title\n');
      return undefined;
    }
    return {
      page: slugifyName(input.page),
      widgetType: input.widgetType,
      section: input.section || 'main',
      title: input.title,
      subtitle: input.subtitle,
    };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const page = slugifyName(await promptText(rl, 'Dashboard page/folder', input.page || 'operations-dashboard'));
    const widgetType = await promptChoice(rl, `Widget type (${widgetTypes.join('/')})`, widgetTypes, input.widgetType || 'metric') as DashboardWidgetKind;
    const section = await promptChoice(rl, 'Dashboard section (top/main/bottom)', ['top', 'main', 'bottom'], input.section || 'main') as DashboardSection;
    const title = await promptText(rl, 'Widget title', input.title || `${humanizeName(widgetType)} Widget`);
    const subtitle = await promptText(rl, 'Widget subtitle', input.subtitle || '', true);
    return { page, widgetType, section, title, subtitle: subtitle || undefined };
  } finally {
    rl.close();
  }
}

async function resolveServiceAnswers(options: CreateCommandOptions): Promise<ServiceAnswers | undefined> {
  const values = options.values || {};
  const input = {
    name: values.name || options.positionals?.[0],
    path: values.path || values['service-path'],
  };

  if (!options.interactive) {
    if (!input.name) {
      options.stderr.write('[vuetify-ext] Missing required flags for create service:\n- --name\n');
      return undefined;
    }
    return { name: slugifyName(input.name), path: input.path || slugifyName(input.name) };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const name = slugifyName(await promptText(rl, 'Service file name', input.name || 'users'));
    const servicePath = await promptText(rl, 'Service path', input.path || name);
    return { name, path: servicePath };
  } finally {
    rl.close();
  }
}

async function resolveValidatorAnswers(options: CreateCommandOptions): Promise<ValidatorAnswers | undefined> {
  const values = options.values || {};
  const input = {
    name: values.name || options.positionals?.[0],
    kind: (values.kind || 'field') as ValidatorAnswers['kind'],
  };

  if (!options.interactive) {
    if (!input.name) {
      options.stderr.write('[vuetify-ext] Missing required flags for create validator:\n- --name\n');
      return undefined;
    }
    return { name: slugifyName(input.name), kind: input.kind || 'field' };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const name = slugifyName(await promptText(rl, 'Validator file name', input.name || 'order-code'));
    const kind = await promptChoice(rl, 'Validator kind (field/rule-array)', ['field', 'rule-array'], input.kind || 'field') as ValidatorAnswers['kind'];
    return { name, kind };
  } finally {
    rl.close();
  }
}

function ensureFormScaffoldMarkers(source: string): string | undefined {
  let next = source;
  const childPattern = /children:\s*\(\)\s*=>\s*\[/g;
  const matches = Array.from(next.matchAll(childPattern));
  if (!next.includes(FORM_PARTS_MARKER)) {
    if (!matches[0]?.index) {
      return undefined;
    }
    const rootInsertAt = matches[0].index + matches[0][0].length;
    next = `${next.slice(0, rootInsertAt)}\n        ${FORM_PARTS_MARKER}${next.slice(rootInsertAt)}`;
  }
  if (!next.includes(`${FORM_FIELDS_MARKER_PREFIX}1:fields`)) {
    const rematches = Array.from(next.matchAll(childPattern));
    if (!rematches[1]?.index) {
      return undefined;
    }
    const partInsertAt = rematches[1].index + rematches[1][0].length;
    next = `${next.slice(0, partInsertAt)}\n              ${FORM_FIELDS_MARKER_PREFIX}1:fields${next.slice(partInsertAt)}`;
  }
  return next;
}

function ensureDashboardMarkers(source: string): string | undefined {
  let next = source;
  if (!next.includes(DASHBOARD_IMPORT_MARKER)) {
    const importMatches = Array.from(next.matchAll(/^import .*$/gm));
    const lastImport = importMatches[importMatches.length - 1];
    if (!lastImport) {
      return undefined;
    }
    const insertAt = (lastImport.index || 0) + lastImport[0].length;
    next = `${next.slice(0, insertAt)}\n${DASHBOARD_IMPORT_MARKER}${next.slice(insertAt)}`;
  }
  const markers: Array<{ key: string; pattern: RegExp }> = [
    { key: DASHBOARD_TOP_MARKER, pattern: /topChildren:\s*\(\)\s*=>\s*\[/ },
    { key: DASHBOARD_MAIN_MARKER, pattern: /children:\s*\(\)\s*=>\s*\[/ },
    { key: DASHBOARD_BOTTOM_MARKER, pattern: /bottomChildren:\s*\(\)\s*=>\s*\[/ },
  ];
  for (const marker of markers) {
    if (next.includes(marker.key)) {
      continue;
    }
    if (!marker.pattern.test(next)) {
      return undefined;
    }
    next = next.replace(marker.pattern, (match) => `${match}\n        ${marker.key}`);
  }
  return next;
}

function ensureReportMarkers(source: string, pascalName: string): string | undefined {
  if (source.includes('// vuetify-ext:report-form-imports') && source.includes('// vuetify-ext:report-form-resolver')) {
    return source;
  }
  let next = source;
  const baseImportPattern = new RegExp(`import\\s*\\{\\s*create${pascalName}Form\\s*\\}\\s*from\\s*['"]\\.\\/form['"];?`);
  const baseImportMatch = next.match(baseImportPattern);
  if (!baseImportMatch) {
    return undefined;
  }
  if (!next.includes('// vuetify-ext:report-form-imports')) {
    next = next.replace(baseImportMatch[0], `${baseImportMatch[0]}\n// vuetify-ext:report-form-imports`);
  }
  if (!next.includes('// vuetify-ext:report-form-resolver')) {
    const usesMode = next.includes(`create${pascalName}Form(mode)`);
    const resolverCall = usesMode ? `create${pascalName}Form(mode)` : `create${pascalName}Form()`;
    const resolverReplacement = `form: async (_props, _context, index) => {\n        // vuetify-ext:report-form-resolver\n        if (index === 0) return ${resolverCall};\n        return undefined;\n      },`;
    next = next.replace(
      new RegExp(`form:\\s*async\\s*\\([^)]*\\)\\s*=>\\s*create${pascalName}Form\\((?:mode)?\\)\\s*,?`),
      resolverReplacement,
    );
  }
  return next;
}

function extractFormPartIndices(source: string) {
  return Array.from(source.matchAll(/\/\/ vuetify-ext:part:(\d+):fields/g)).map((match) => Number(match[1]));
}

function resolveFormFile(cwd: string, page: string, step: number, ext: ScriptExt) {
  return path.join(cwd, 'src/pages', page, step <= 1 ? `form${ext}` : `form-${step}${ext}`);
}

function prepareWrites(options: CreateCommandOptions, writes: FileWrite[]): 'ok' | 'dry-run' | 'error' {
  const existing = writes.filter((entry) => !options.force && fileExists(entry.file));
  if (existing.length > 0) {
    options.stderr.write(
      `[vuetify-ext] The following files already exist:\n- ${existing.map((entry) => relativeToCwd(options.cwd, entry.file)).join('\n- ')}\nUse --force to overwrite them.\n`,
    );
    return 'error';
  }
  if (options.dryRun) {
    options.stdout.write('[vuetify-ext] Dry run only. The following files would be written:\n');
    for (const write of writes) {
      options.stdout.write(`- ${relativeToCwd(options.cwd, write.file)}\n`);
    }
    return 'dry-run';
  }
  return 'ok';
}

function writeFiles(writes: FileWrite[]) {
  for (const write of uniqueWrites(writes)) {
    fs.mkdirSync(path.dirname(write.file), { recursive: true });
    fs.writeFileSync(write.file, write.content, 'utf8');
  }
}

function uniqueWrites(writes: FileWrite[]) {
  const seen = new Set<string>();
  return writes.filter((write) => {
    if (seen.has(write.file)) {
      return false;
    }
    seen.add(write.file);
    return true;
  });
}

function ensureIndexExports(pageDir: string, ext: ScriptExt, exportLines: string[]) {
  const file = path.join(pageDir, `index${ext}`);
  ensureSimpleExport(file, exportLines);
}

function ensureSimpleExport(file: string, exportLineOrLines: string | string[]) {
  const lines = Array.isArray(exportLineOrLines) ? exportLineOrLines : [exportLineOrLines];
  const next = appendLines(fileExists(file) ? fs.readFileSync(file, 'utf8') : `${GENERATED_MARKER} page index\n`, lines);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, next, 'utf8');
}

function appendLines(source: string, linesToAdd: string[]) {
  const lines = source.trimEnd().split('\n').filter(Boolean);
  for (const line of linesToAdd) {
    if (!lines.includes(line)) {
      lines.push(line);
    }
  }
  return `${lines.join('\n')}\n`;
}

function writeSuccess(options: CreateCommandOptions, heading: string, files: string[]) {
  options.stdout.write(`[vuetify-ext] ${heading}:\n`);
  for (const file of Array.from(new Set(files))) {
    options.stdout.write(`- ${relativeToCwd(options.cwd, file)}\n`);
  }
}

function withValues(options: CreateCommandOptions, values: Record<string, string>) {
  return {
    ...options,
    interactive: false,
    values,
    positionals: [],
  };
}

function findExistingFile(cwd: string, files: string[]) {
  return files.map((file) => path.join(cwd, file)).find((file) => fileExists(file));
}

function listPageNames(cwd: string) {
  const pagesDir = path.join(cwd, 'src/pages');
  if (!fs.existsSync(pagesDir)) {
    return [];
  }
  return fs.readdirSync(pagesDir).filter((entry) => fs.statSync(path.join(pagesDir, entry)).isDirectory());
}

function listSourceFiles(root: string): string[] {
  if (!fs.existsSync(root)) {
    return [];
  }
  const entries = fs.readdirSync(root, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const fullPath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...listSourceFiles(fullPath));
      continue;
    }
    if (/\.(ts|js)$/.test(entry.name)) {
      files.push(fullPath);
    }
  }
  return files;
}

function resolveProjectScriptExtension(cwd: string): ScriptExt {
  if (findExistingFile(cwd, ['src/main.ts', 'src/menu/index.ts'])) {
    return '.ts';
  }
  return fileExists(path.join(cwd, 'tsconfig.json')) ? '.ts' : '.js';
}

function resolveExistingPageScriptExtension(cwd: string, page: string): ScriptExt | undefined {
  const tsFiles = ['report.ts', 'form.ts', 'trigger.ts', 'collection.ts', 'dashboard.ts', 'index.ts'];
  if (tsFiles.some((file) => fileExists(path.join(cwd, 'src/pages', page, file)))) {
    return '.ts';
  }
  const jsFiles = ['report.js', 'form.js', 'trigger.js', 'collection.js', 'dashboard.js', 'index.js'];
  if (jsFiles.some((file) => fileExists(path.join(cwd, 'src/pages', page, file)))) {
    return '.js';
  }
  return undefined;
}

function verifyExpectedPageExport(file: string, exportName: string) {
  if (!fileExists(file)) {
    return false;
  }
  return sourceIncludesNamedExport(fs.readFileSync(file, 'utf8'), exportName);
}

function sourceIncludesNamedExport(source: string, exportName: string) {
  const escaped = escapeRegExp(exportName);
  return [
    new RegExp(`export\\s+function\\s+${escaped}\\s*\\(`),
    new RegExp(`export\\s+(?:const|let|var)\\s+${escaped}\\s*=`),
    new RegExp(`export\\s*\\{[^}]*\\b${escaped}\\b[^}]*\\}`),
  ].some((pattern) => pattern.test(source));
}

function fileExists(file: string) {
  return fs.existsSync(file);
}

function relativeToCwd(cwd: string, file: string) {
  return path.relative(cwd, file) || '.';
}

function humanizeName(value: string) {
  return value
    .replace(/[-_]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (match) => match.toUpperCase());
}

function slugifyName(value: string) {
  return value
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
}

function toPascalCase(value: string) {
  return slugifyName(value)
    .split('-')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function sanitizeIdentifier(value: string) {
  let identifier = toPascalCase(value);
  if (!identifier) {
    identifier = 'GeneratedValue';
  }
  if (/^[0-9]/.test(identifier)) {
    identifier = `Value${identifier}`;
  }
  return identifier.charAt(0).toLowerCase() + identifier.slice(1);
}

function serializeString(value: string) {
  return JSON.stringify(value);
}

function serializeUITextDescriptor(key: string, fallback: string) {
  return `{ key: ${serializeString(key)}, fallback: ${serializeString(fallback)} }`;
}

function pageTextKey(page: string, ...segments: string[]) {
  return ['pages', slugifyName(page), ...segments].join('.');
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function normalizePositiveInt(value: string | number | undefined, fallback: number) {
  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback;
}

function parseOptionalBoolean(value: string | undefined) {
  if (value === undefined) return undefined;
  const normalized = value.trim().toLowerCase();
  if (['true', '1', 'yes', 'y'].includes(normalized)) return true;
  if (['false', '0', 'no', 'n'].includes(normalized)) return false;
  return undefined;
}

async function promptText(rl: readline.Interface, label: string, defaultValue?: string, allowEmpty: boolean = false) {
  while (true) {
    const suffix = defaultValue ? ` [${defaultValue}]` : '';
    const value = (await ask(rl, `${label}${suffix}: `)).trim();
    if (value.length > 0) return value;
    if (defaultValue !== undefined) return defaultValue;
    if (allowEmpty) return '';
  }
}

async function promptNumber(rl: readline.Interface, label: string, defaultValue: number, min: number) {
  while (true) {
    const value = (await ask(rl, `${label} [${defaultValue}]: `)).trim();
    if (!value) return defaultValue;
    const parsed = Number(value);
    if (Number.isInteger(parsed) && parsed >= min) return parsed;
  }
}

async function promptChoice(rl: readline.Interface, label: string, choices: string[], defaultValue: string) {
  while (true) {
    const value = (await ask(rl, `${label} [${defaultValue}]: `)).trim().toLowerCase();
    const resolved = value || defaultValue;
    if (choices.includes(resolved)) return resolved;
  }
}

async function promptBoolean(rl: readline.Interface, label: string, defaultValue: boolean) {
  while (true) {
    const suffix = defaultValue ? ' [Y/n]' : ' [y/N]';
    const value = (await ask(rl, `${label}${suffix}: `)).trim().toLowerCase();
    if (!value) return defaultValue;
    if (['y', 'yes', 'true', '1'].includes(value)) return true;
    if (['n', 'no', 'false', '0'].includes(value)) return false;
  }
}

function ask(rl: readline.Interface, prompt: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => resolve(answer));
  });
}
