import fs from 'node:fs';
import path from 'node:path';
import * as readline from 'node:readline';

export interface BootstrapApiAnswers {
  backend: 'none' | 'axios' | 'feathers';
  apiURL?: string;
  keycloakURL?: string;
  keycloakRealm?: string;
  keycloakClientId?: string;
  keycloakOnLoad?: 'login-required' | 'check-sso';
  useSocket?: boolean;
  socketURL?: string;
  socketEvent?: string;
  socketAuthMode?: 'auth' | 'query';
  authPath?: string;
  refreshAuthPath?: string;
  authCreateMethod?: 'get' | 'post' | 'put';
  authRefreshMethod?: 'get' | 'patch' | 'post' | 'put';
}

export interface BootstrapAppCommandOptions {
  cwd: string;
  force: boolean;
  dryRun: boolean;
  interactive: boolean;
  apiAnswers?: Partial<BootstrapApiAnswers>;
  stdin: NodeJS.ReadableStream;
  stdout: Pick<typeof process.stdout, 'write'>;
  stderr: Pick<typeof process.stderr, 'write'>;
}

interface BootstrapTargets {
  entryFile: string;
  entryExt: '.ts' | '.js';
  scaffoldFiles: Array<{
    file: string;
    content: string;
  }>;
}

interface ExistingMainAnalysis {
  preservedImports: string[];
  prelude: string;
  useCalls: string[];
  mountSelector: string;
}

const GENERATED_MARKER = '// Generated by vuetify-ext bootstrap app';
const DEFAULT_SELECTOR = "'#app'";
const ENTRY_CANDIDATES = [
  'src/main.ts',
  'src/main.js',
] as const;

export async function runBootstrapAppCommand(options: BootstrapAppCommandOptions): Promise<number> {
  const targets = resolveBootstrapTargets(options.cwd);

  if (!targets) {
    options.stderr.write(
      '[vuetify-ext] Could not find a supported Vue entry file. Expected one of: src/main.ts or src/main.js\n',
    );
    return 1;
  }

  if (!options.force) {
    const existingBootstrapFiles = targets.scaffoldFiles
      .map(entry => entry.file)
      .filter(fileExists);
    if (existingBootstrapFiles.length > 0) {
      options.stderr.write(
        `[vuetify-ext] Bootstrap files already exist:\n- ${existingBootstrapFiles.join('\n- ')}\n` +
          'Use --force to overwrite them.\n',
      );
      return 1;
    }
  }

  const mainSource = fs.readFileSync(targets.entryFile, 'utf8');

  if (!options.force && mainSource.includes(`${GENERATED_MARKER}`)) {
    options.stderr.write(
      `[vuetify-ext] ${relativeToCwd(options.cwd, targets.entryFile)} already looks bootstrapped.\n` +
        'Use --force to regenerate the bootstrap files.\n',
    );
    return 1;
  }

  const apiAnswers = await resolveApiAnswers(options);
  if (!apiAnswers) {
    return 1;
  }

  targets.scaffoldFiles = buildScaffoldFiles(path.dirname(targets.entryFile), targets.entryExt, apiAnswers);

  const analysis = analyzeExistingMain(mainSource);
  const nextMainSource = buildMainFileSource({
    preservedImports: analysis.preservedImports,
    prelude: analysis.prelude,
    useCalls: analysis.useCalls,
    mountSelector: analysis.mountSelector,
  });

  const writes = [
    ...targets.scaffoldFiles,
    { file: targets.entryFile, content: nextMainSource },
  ];

  if (options.dryRun) {
    options.stdout.write('[vuetify-ext] Dry run only. The following files would be written:\n');
    for (const write of writes) {
      options.stdout.write(`- ${relativeToCwd(options.cwd, write.file)}\n`);
    }
    return 0;
  }

  for (const write of writes) {
    fs.mkdirSync(path.dirname(write.file), { recursive: true });
    fs.writeFileSync(write.file, write.content, 'utf8');
  }

  options.stdout.write('[vuetify-ext] Bootstrap scaffolding created successfully:\n');
  for (const write of writes) {
    options.stdout.write(`- ${relativeToCwd(options.cwd, write.file)}\n`);
  }
  options.stdout.write(
    '\nNext steps:\n' +
      '1. Review src/api/index.* and confirm the generated backend configuration.\n' +
      '2. Review src/bootstrap/index.* plus header/footer sections for shell structure.\n' +
      '3. Review src/menu/index.* and src/pages/home/index.* as the starter menu/page structure.\n' +
      '4. Run your app and confirm the new Vuetify Extended shell boots correctly.\n',
  );

  return 0;
}

function resolveBootstrapTargets(cwd: string): BootstrapTargets | undefined {
  const entryRelativePath = ENTRY_CANDIDATES.find(candidate => fileExists(path.join(cwd, candidate)));
  if (!entryRelativePath) {
    return undefined;
  }

  const entryFile = path.join(cwd, entryRelativePath);
  const entryExt = path.extname(entryFile) as '.ts' | '.js';

  return {
    entryFile,
    entryExt,
    scaffoldFiles: [],
  };
}

async function resolveApiAnswers(options: BootstrapAppCommandOptions): Promise<BootstrapApiAnswers | undefined> {
  const normalizedInput = normalizeApiAnswersInput(options.apiAnswers || {});

  if (!options.interactive) {
    return validateNonInteractiveApiAnswers(normalizedInput, options.stderr);
  }

  return await promptForApiAnswers(normalizedInput, options.stdin, options.stdout);
}

function normalizeApiAnswersInput(input: Partial<BootstrapApiAnswers>): Partial<BootstrapApiAnswers> {
  const normalized: Partial<BootstrapApiAnswers> = { ...input };

  if (normalized.backend) {
    normalized.backend = String(normalized.backend).toLowerCase() as BootstrapApiAnswers['backend'];
  }

  if (normalized.keycloakOnLoad) {
    normalized.keycloakOnLoad = String(normalized.keycloakOnLoad).toLowerCase() as BootstrapApiAnswers['keycloakOnLoad'];
  }

  if (normalized.socketAuthMode) {
    normalized.socketAuthMode = String(normalized.socketAuthMode).toLowerCase() as BootstrapApiAnswers['socketAuthMode'];
  }

  if (normalized.authCreateMethod) {
    normalized.authCreateMethod = String(normalized.authCreateMethod).toLowerCase() as BootstrapApiAnswers['authCreateMethod'];
  }

  if (normalized.authRefreshMethod) {
    normalized.authRefreshMethod = String(normalized.authRefreshMethod).toLowerCase() as BootstrapApiAnswers['authRefreshMethod'];
  }

  return normalized;
}

function validateNonInteractiveApiAnswers(
  input: Partial<BootstrapApiAnswers>,
  stderr: Pick<typeof process.stderr, 'write'>,
): BootstrapApiAnswers | undefined {
  const hasApiFlags = Object.keys(input).some((key) => (input as any)[key] !== undefined && (input as any)[key] !== '');
  const backend = input.backend;

  if (!backend) {
    if (hasApiFlags) {
      stderr.write('[vuetify-ext] When using API-related flags in --non-interactive mode, also pass --backend none|axios|feathers\n');
      return undefined;
    }

    return {
      backend: 'none',
      useSocket: false,
    };
  }

  if (!['none', 'axios', 'feathers'].includes(backend)) {
    stderr.write(`[vuetify-ext] Invalid --backend value: ${backend}. Expected none, axios, or feathers.\n`);
    return undefined;
  }

  if (backend === 'none') {
    return {
      backend: 'none',
      useSocket: false,
    };
  }

  const missing: string[] = [];
  if (!input.apiURL) missing.push('--api-url');
  if (!input.keycloakURL) missing.push('--keycloak-url');
  if (!input.keycloakRealm) missing.push('--keycloak-realm');
  if (!input.keycloakClientId) missing.push('--keycloak-client-id');

  if (missing.length > 0) {
    stderr.write(
      `[vuetify-ext] Missing required flags for --non-interactive ${backend} bootstrap:\n- ${missing.join('\n- ')}\n`,
    );
    return undefined;
  }

  const useSocket = input.useSocket === true;
  const apiURL = input.apiURL!;

  return {
    backend,
    apiURL,
    keycloakURL: input.keycloakURL!,
    keycloakRealm: input.keycloakRealm!,
    keycloakClientId: input.keycloakClientId!,
    keycloakOnLoad: input.keycloakOnLoad || 'login-required',
    useSocket,
    socketURL: backend === 'axios'
      ? (input.socketURL || defaultSocketURL(apiURL))
      : undefined,
    socketEvent: backend === 'axios'
      ? (input.socketEvent || 'domain-event')
      : undefined,
    socketAuthMode: backend === 'axios'
      ? (input.socketAuthMode || 'auth')
      : undefined,
    authPath: backend === 'axios'
      ? (input.authPath || 'auth/me')
      : undefined,
    refreshAuthPath: backend === 'axios'
      ? (input.refreshAuthPath || 'auth/me')
      : undefined,
    authCreateMethod: backend === 'axios'
      ? (input.authCreateMethod || 'get')
      : undefined,
    authRefreshMethod: backend === 'axios'
      ? (input.authRefreshMethod || 'get')
      : undefined,
  };
}

async function promptForApiAnswers(
  input: Partial<BootstrapApiAnswers>,
  stdin: NodeJS.ReadableStream,
  stdout: Pick<typeof process.stdout, 'write'>,
): Promise<BootstrapApiAnswers> {
  const rl = readline.createInterface({
    input: stdin,
    output: stdout as NodeJS.WritableStream,
  });

  try {
    const backend = await promptChoice(
      rl,
      'Backend type (none/axios/feathers)',
      ['none', 'axios', 'feathers'],
      input.backend || 'none',
    ) as BootstrapApiAnswers['backend'];

    if (backend === 'none') {
      return {
        backend: 'none',
        useSocket: false,
      };
    }

    const apiURL = await promptText(rl, 'API URL', input.apiURL);
    const keycloakURL = await promptText(rl, 'Keycloak URL', input.keycloakURL);
    const keycloakRealm = await promptText(rl, 'Keycloak realm', input.keycloakRealm);
    const keycloakClientId = await promptText(rl, 'Keycloak client ID', input.keycloakClientId);
    const keycloakOnLoad = await promptChoice(
      rl,
      'Keycloak onLoad (login-required/check-sso)',
      ['login-required', 'check-sso'],
      input.keycloakOnLoad || 'login-required',
    ) as BootstrapApiAnswers['keycloakOnLoad'];

    if (backend === 'feathers') {
      const useSocket = await promptBoolean(rl, 'Enable Socket.IO realtime', input.useSocket === true);
      return {
        backend,
        apiURL,
        keycloakURL,
        keycloakRealm,
        keycloakClientId,
        keycloakOnLoad,
        useSocket,
      };
    }

    const useSocket = await promptBoolean(rl, 'Enable Socket.IO realtime', input.useSocket === true);
    const authPath = await promptText(rl, 'Auth path', input.authPath || 'auth/me', true);
    const refreshAuthPath = await promptText(rl, 'Refresh auth path', input.refreshAuthPath || 'auth/me', true);
    const authCreateMethod = await promptChoice(
      rl,
      'Auth create method (get/post/put)',
      ['get', 'post', 'put'],
      input.authCreateMethod || 'get',
    ) as BootstrapApiAnswers['authCreateMethod'];
    const authRefreshMethod = await promptChoice(
      rl,
      'Auth refresh method (get/post/put/patch)',
      ['get', 'post', 'put', 'patch'],
      input.authRefreshMethod || 'get',
    ) as BootstrapApiAnswers['authRefreshMethod'];

    let socketURL: string | undefined;
    let socketEvent: string | undefined;
    let socketAuthMode: BootstrapApiAnswers['socketAuthMode'] | undefined;

    if (useSocket) {
      socketURL = await promptText(rl, 'Socket URL', input.socketURL || defaultSocketURL(apiURL), true);
      socketEvent = await promptText(rl, 'Socket event', input.socketEvent || 'domain-event', true);
      socketAuthMode = await promptChoice(
        rl,
        'Socket auth mode (auth/query)',
        ['auth', 'query'],
        input.socketAuthMode || 'auth',
      ) as BootstrapApiAnswers['socketAuthMode'];
    }

    return {
      backend,
      apiURL,
      keycloakURL,
      keycloakRealm,
      keycloakClientId,
      keycloakOnLoad,
      useSocket,
      socketURL,
      socketEvent,
      socketAuthMode,
      authPath,
      refreshAuthPath,
      authCreateMethod,
      authRefreshMethod,
    };
  } finally {
    rl.close();
  }
}

async function promptText(
  rl: readline.Interface,
  label: string,
  defaultValue?: string,
  allowEmpty: boolean = false,
): Promise<string> {
  while (true) {
    const suffix = defaultValue ? ` [${defaultValue}]` : '';
    const value = (await ask(rl, `${label}${suffix}: `)).trim();
    if (value.length > 0) {
      return value;
    }

    if (defaultValue !== undefined) {
      return defaultValue;
    }

    if (allowEmpty) {
      return '';
    }
  }
}

async function promptBoolean(
  rl: readline.Interface,
  label: string,
  defaultValue: boolean,
): Promise<boolean> {
  while (true) {
    const suffix = defaultValue ? ' [Y/n]' : ' [y/N]';
    const value = (await ask(rl, `${label}${suffix}: `)).trim().toLowerCase();
    if (!value) {
      return defaultValue;
    }

    if (['y', 'yes', 'true', '1'].includes(value)) {
      return true;
    }

    if (['n', 'no', 'false', '0'].includes(value)) {
      return false;
    }
  }
}

async function promptChoice(
  rl: readline.Interface,
  label: string,
  choices: string[],
  defaultValue: string,
): Promise<string> {
  while (true) {
    const value = (await ask(rl, `${label} [${defaultValue}]: `)).trim().toLowerCase();
    const resolved = value || defaultValue;
    if (choices.includes(resolved)) {
      return resolved;
    }
  }
}

function ask(rl: readline.Interface, prompt: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => resolve(answer));
  });
}

function analyzeExistingMain(source: string): ExistingMainAnalysis {
  const importMatches = collectMatches(source, /^\s*import[\s\S]*?;?\s*$/gm);
  const importStatements = importMatches.map(match => match[0].trim()).filter(Boolean);
  const preservedImports = importStatements
    .map(transformImportForPreservation)
    .filter((statement): statement is string => Boolean(statement));
  const importsEndIndex = importMatches.length > 0
    ? (importMatches[importMatches.length - 1].index || 0) + importMatches[importMatches.length - 1][0].length
    : 0;

  const chainMatch = source.match(
    /createApp\s*\([\s\S]*?\)\s*((?:\s*\.\s*use\s*\([\s\S]*?\)\s*)*)\.\s*mount\s*\(([\s\S]*?)\)\s*;?/m,
  );

  if (chainMatch && typeof chainMatch.index === 'number') {
    return {
      preservedImports,
      prelude: cleanPrelude(source.slice(importsEndIndex, chainMatch.index)),
      useCalls: extractUseCalls(chainMatch[1] || ''),
      mountSelector: sanitizeMountSelector(chainMatch[2]),
    };
  }

  const appVariableMatch = source.match(/const\s+(\w+)\s*=\s*createApp\s*\([\s\S]*?\)\s*;?/m);
  if (appVariableMatch && typeof appVariableMatch.index === 'number') {
    const appVariableName = appVariableMatch[1];
    const useCalls = extractVariableUseCalls(source, appVariableName);
    const mountSelector = extractVariableMountSelector(source, appVariableName);
    return {
      preservedImports,
      prelude: cleanPrelude(source.slice(importsEndIndex, appVariableMatch.index)),
      useCalls,
      mountSelector,
    };
  }

  return {
    preservedImports,
    prelude: cleanPrelude(source.slice(importsEndIndex)),
    useCalls: [],
    mountSelector: DEFAULT_SELECTOR,
  };
}

function transformImportForPreservation(statement: string): string | undefined {
  const normalized = statement.replace(/\s+/g, ' ').trim();

  if (/from\s+['"]vue['"]/.test(normalized)) {
    return preserveVueImport(statement);
  }
  if (/from\s+['"]vuetify['"]/.test(normalized)) return undefined;
  if (/from\s+['"]vuetify\/components['"]/.test(normalized)) return undefined;
  if (/from\s+['"]vuetify\/directives['"]/.test(normalized)) return undefined;
  if (/['"]vuetify\/styles['"]/.test(normalized)) return undefined;
  if (/['"]@mdi\/font\/css\/materialdesignicons\.css['"]/.test(normalized)) return undefined;
  if (/['"]vuetify-extended\/lib\/esm\/css\/index\.css['"]/.test(normalized)) return undefined;
  if (/from\s+['"].*App\.vue['"]/.test(normalized)) return undefined;
  if (/from\s+['"].*bootstrap['"]/.test(normalized) && normalized.includes('initialize')) return undefined;

  return statement;
}

function preserveVueImport(statement: string): string | undefined {
  const importMatch = statement.match(/import\s*\{([\s\S]*?)\}\s*from\s*['"]vue['"];?/);
  if (!importMatch) {
    return undefined;
  }

  const preservedSpecifiers = importMatch[1]
    .split(',')
    .map(specifier => specifier.trim())
    .filter(Boolean)
    .filter(specifier => {
      const importedName = specifier.split(/\s+as\s+/i)[0].trim();
      return importedName !== 'createApp' && importedName !== 'defineComponent' && importedName !== 'h';
    });

  if (preservedSpecifiers.length === 0) {
    return undefined;
  }

  return `import { ${preservedSpecifiers.join(', ')} } from 'vue';`;
}

function extractUseCalls(chain: string): string[] {
  const matches = collectMatches(chain, /\.use\s*\(([\s\S]*?)\)\s*/g);
  return dedupe(matches.map(match => match[1].trim()).filter(Boolean));
}

function extractVariableUseCalls(source: string, variableName: string): string[] {
  const escaped = escapeRegExp(variableName);
  const expression = new RegExp(`${escaped}\\s*\\.\\s*use\\s*\\(([\\s\\S]*?)\\)\\s*;?`, 'g');
  const matches = collectMatches(source, expression);
  return dedupe(matches.map(match => match[1].trim()).filter(Boolean));
}

function extractVariableMountSelector(source: string, variableName: string): string {
  const escaped = escapeRegExp(variableName);
  const mountMatch = source.match(new RegExp(`${escaped}\\s*\\.\\s*mount\\s*\\(([\\s\\S]*?)\\)\\s*;?`));
  return sanitizeMountSelector(mountMatch?.[1]);
}

function sanitizeMountSelector(selector: string | undefined): string {
  const normalized = selector?.trim();
  return normalized ? normalized : DEFAULT_SELECTOR;
}

function cleanPrelude(prelude: string): string {
  const trimmed = prelude.trim();
  if (!trimmed) {
    return '';
  }

  return trimmed
    .split('\n')
    .map(line => line.replace(/\s+$/, ''))
    .join('\n');
}

function buildScaffoldFiles(srcDir: string, ext: '.ts' | '.js', apiAnswers: BootstrapApiAnswers) {
  return [
    {
      file: path.join(srcDir, `api/index${ext}`),
      content: buildApiFileSource(ext, apiAnswers),
    },
    {
      file: path.join(srcDir, `bootstrap/header${ext}`),
      content: buildHeaderFileSource(ext),
    },
    {
      file: path.join(srcDir, `bootstrap/footer${ext}`),
      content: buildFooterFileSource(ext),
    },
    {
      file: path.join(srcDir, `bootstrap/index${ext}`),
      content: buildBootstrapIndexFileSource(ext),
    },
    {
      file: path.join(srcDir, `menu/index${ext}`),
      content: buildMenuFileSource(),
    },
    {
      file: path.join(srcDir, `pages/home/form${ext}`),
      content: buildHomeFormFileSource(),
    },
    {
      file: path.join(srcDir, `pages/home/index${ext}`),
      content: buildHomePageFileSource(ext),
    },
  ];
}

function buildApiFileSource(ext: '.ts' | '.js', answers: BootstrapApiAnswers): string {
  const typeImport = ext === '.ts' ? "import type { VuetifyExtendedApiConfig } from 'vuetify-extended';\n\n" : '';
  const returnType = ext === '.ts' ? ': VuetifyExtendedApiConfig | undefined' : '';

  if (answers.backend === 'none') {
    return `${GENERATED_MARKER}
${typeImport}export function createApiConfig()${returnType} {
  return undefined;
}
`;
  }

  const keycloakOnLoad = answers.keycloakOnLoad || 'login-required';

  if (answers.backend === 'feathers') {
    return `${GENERATED_MARKER}
${typeImport}export function createApiConfig()${returnType} {
  return {
    type: 'feathers',
    apiURL: ${serializeString(answers.apiURL)},
    keycloakConfig: {
      keycloakConfig: {
        url: ${serializeString(answers.keycloakURL)},
        realm: ${serializeString(answers.keycloakRealm)},
        clientId: ${serializeString(answers.keycloakClientId)},
      },
      keycloakInit: {
        onLoad: ${serializeString(keycloakOnLoad)},
      },
    },
    options: {
      useSocket: ${answers.useSocket === true ? 'true' : 'false'},
    },
  };
}
`;
  }

  const useSocket = answers.useSocket === true;
  const socketLines = useSocket
    ? `\n      useSocket: true,\n      socketURL: ${serializeString(answers.socketURL || defaultSocketURL(answers.apiURL || ''))},\n      socketAuthMode: ${serializeString(answers.socketAuthMode || 'auth')},\n      socketEvent: ${serializeString(answers.socketEvent || 'domain-event')},`
    : '';

  return `${GENERATED_MARKER}
${typeImport}export function createApiConfig()${returnType} {
  return {
    type: 'axios',
    apiURL: ${serializeString(answers.apiURL)},
    keycloakConfig: {
      keycloakConfig: {
        url: ${serializeString(answers.keycloakURL)},
        realm: ${serializeString(answers.keycloakRealm)},
        clientId: ${serializeString(answers.keycloakClientId)},
      },
      keycloakInit: {
        onLoad: ${serializeString(keycloakOnLoad)},
      },
    },
    options: {${socketLines}
      authPath: ${serializeString(answers.authPath || 'auth/me')},
      refreshAuthPath: ${serializeString(answers.refreshAuthPath || 'auth/me')},
      authCreateMethod: ${serializeString(answers.authCreateMethod || 'get')},
      authRefreshMethod: ${serializeString(answers.authRefreshMethod || 'get')},
    },
  };
}
`;
}

function buildHeaderFileSource(ext: '.ts' | '.js'): string {
  const typeImports = ext === '.ts' ? ', type AppMain, type AppShellContent' : '';
  const typeReturn = ext === '.ts' ? ': AppShellContent[]' : '';
  const typeArg = ext === '.ts' ? ': AppMain' : '';

  return `${GENERATED_MARKER}
import { AppTitleBlock, EnvironmentTag, StatusBadge${typeImports} } from 'vuetify-extended';

export function buildHeaderStart(app${typeArg})${typeReturn} {
  return [
    new AppTitleBlock({
      title: app.$params.title || ${serializeUITextDescriptor('bootstrap.header.title', 'My Workspace')},
      subtitle: ${serializeUITextDescriptor('bootstrap.header.subtitle', 'Built with vuetify-extended')},
      overline: ${serializeUITextDescriptor('bootstrap.header.overline', 'Workspace')},
      icon: 'mdi-view-dashboard-outline',
      color: 'primary',
    }),
  ];
}

export function buildHeaderCenter(_app${typeArg})${typeReturn} {
  return [
    new EnvironmentTag({
      text: ${serializeUITextDescriptor('bootstrap.header.environment', 'Starter')},
      color: 'info',
      variant: 'outlined',
    }),
  ];
}

export function buildHeaderEnd(_app${typeArg})${typeReturn} {
  return [
    new StatusBadge({
      text: ${serializeUITextDescriptor('bootstrap.header.status', 'Ready')},
      icon: 'mdi-check-circle-outline',
      color: 'success',
      variant: 'tonal',
    }),
  ];
}
`;
}

function buildFooterFileSource(ext: '.ts' | '.js'): string {
  const typeImports = ext === '.ts' ? ', type AppMain, type AppShellContent' : '';
  const typeReturn = ext === '.ts' ? ': AppShellContent[]' : '';
  const typeArg = ext === '.ts' ? ': AppMain' : '';

  return `${GENERATED_MARKER}
import { EnvironmentTag, StatusBadge${typeImports} } from 'vuetify-extended';

export function buildFooterStart(_app${typeArg})${typeReturn} {
  return [
    new StatusBadge({
      text: ${serializeUITextDescriptor('bootstrap.footer.start', 'vuetify-extended Starter')},
      icon: 'mdi-flask-outline',
      color: 'primary',
      variant: 'outlined',
    }),
  ];
}

export function buildFooterCenter(_app${typeArg})${typeReturn} {
  return [
    new EnvironmentTag({
      text: ${serializeUITextDescriptor('bootstrap.footer.center', 'Bootstrap + Pages + Menu')},
      color: 'secondary',
      variant: 'outlined',
    }),
  ];
}

export function buildFooterEnd(_app${typeArg})${typeReturn} {
  return [
    new StatusBadge({
      text: ${serializeUITextDescriptor('bootstrap.footer.end', 'Home Page Ready')},
      icon: 'mdi-home-outline',
      color: 'success',
      variant: 'tonal',
    }),
  ];
}
`;
}

function buildBootstrapIndexFileSource(ext: '.ts' | '.js'): string {
  const typeOnlyImport = ext === '.ts' ? ', type VuetifyExtendedAppFactoryOptions' : '';
  const optionsBlock = ext === '.ts'
    ? `export interface InitializeBootstrapOptions {
  bootstrap?: Partial<VuetifyExtendedAppFactoryOptions>;
}

`
    : '';
  const optionsSignature = ext === '.ts' ? 'options: InitializeBootstrapOptions = {}' : 'options = {}';
  const appReturnType = ext === '.ts' ? ': AppMain' : '';

  return `${GENERATED_MARKER}
import { AppMain, createVuetifyExtendedApp${typeOnlyImport} } from 'vuetify-extended';
import { createApiConfig } from '../api';
import { createMainMenu } from '../menu';
import { buildHeaderCenter, buildHeaderEnd, buildHeaderStart } from './header';
import { buildFooterCenter, buildFooterEnd, buildFooterStart } from './footer';

${optionsBlock}export function createMainApp()${appReturnType} {
  return new AppMain(
    {
      ref: 'main-app',
      title: ${serializeUITextDescriptor('bootstrap.app.title', 'My Workspace')},
      showHeader: true,
      showFooter: true,
      showFab: false,
    },
    {
      menu: async () => createMainMenu(),
      headerStart: buildHeaderStart,
      headerCenter: buildHeaderCenter,
      headerEnd: buildHeaderEnd,
      footerStart: buildFooterStart,
      footerCenter: buildFooterCenter,
      footerEnd: buildFooterEnd,
    },
  );
}

export function initializeBootstrap(${optionsSignature}) {
  const api = createApiConfig();

  return createVuetifyExtendedApp({
    requireApi: false,
    ...(api ? { api } : {}),
    app: createMainApp(),
    dialogs: {
      progressSize: 96,
      progressWidth: 10,
      successTimeout: 2400,
      warningTimeout: 3200,
      errorTimeout: 4200,
    },
    notifications: {
      location: 'top-right',
      maxVisible: 4,
      defaultTimeout: 3600,
    },
    ...(options.bootstrap || {}),
  });
}
`;
}

function buildMenuFileSource(): string {
  return `${GENERATED_MARKER}
import { $MI, $MN } from 'vuetify-extended';
// vuetify-ext:menu-imports
import { createHomeReport } from '../pages/home';

export function createMainMenu() {
  return $MN(
    {
      title: ${serializeUITextDescriptor('bootstrap.menu.title', 'Workspace')},
      cols: 12,
      width: 380,
    },
    {
      children: async () => [
        // vuetify-ext:menu-items
        $MI(
          {
            action: 'report',
            mode: 'display',
            text: ${serializeUITextDescriptor('pages.home.menu.report.display.text', 'Home')},
            subText: ${serializeUITextDescriptor('pages.home.menu.report.display.subText', 'Starter page entry from src/pages/home.')},
            icon: 'mdi-home-outline',
            color: 'primary',
          },
          {
            report: async (_menuItem, mode) => createHomeReport(mode || 'display'),
            navigation: () => ({
              key: 'pages.home.report.display',
              persist: true,
            }),
          },
        ),
      ],
    },
  );
}
`;
}

function buildHomeFormFileSource(): string {
  return `${GENERATED_MARKER}
import { $FD, $FM, $PT } from 'vuetify-extended';

export function createHomeForm() {
  return $FM(
    {
      title: ${serializeUITextDescriptor('pages.home.form.title', 'Welcome')},
      mode: 'display',
      width: 860,
    },
    {
      children: () => [
        $PT(
          { cols: 12, dense: true },
          {
            children: () => [
              $FD({
                type: 'label',
                label: ${serializeUITextDescriptor('pages.home.form.intro.location', 'This starter page is defined in src/pages/home/index.')},
                cols: 12,
              }),
              $FD({
                type: 'label',
                label: ${serializeUITextDescriptor('pages.home.form.intro.pages', 'Add future reports, triggers, collections, and dashboards under src/pages/<page-name>/.')},
                cols: 12,
              }),
              $FD({
                type: 'label',
                label: ${serializeUITextDescriptor('pages.home.form.intro.structure', 'Split larger pages into form.ts, report.ts, trigger.ts, collection.ts, fields.ts, or parts.ts as needed.')},
                cols: 12,
              }),
            ],
          },
        ),
      ],
    },
  );
}
`;
}

function buildHomePageFileSource(ext: '.ts' | '.js'): string {
  const typeImport = ext === '.ts' ? ', type NavigationEntry, type ReportMode' : '';
  const modeArg = ext === '.ts' ? `mode: ReportMode = 'display'` : `mode = 'display'`;
  const entryArg = ext === '.ts' ? 'entry?: NavigationEntry' : 'entry';
  const resolvedModeLine = ext === '.ts'
    ? `    const resolvedMode = (entry?.mode as ReportMode | undefined) || mode;`
    : `    const resolvedMode = (entry && entry.mode) || mode;`;

  return `${GENERATED_MARKER}
import { $RP${typeImport} } from 'vuetify-extended';
import { createHomeForm } from './form';

export function createHomeReport(${modeArg}) {
  return (${entryArg}) => {
${resolvedModeLine}
    return $RP(
      {
        title: ${serializeUITextDescriptor('pages.home.report.title', 'Home')},
        forms: 1,
        mode: resolvedMode,
        horizontalAlign: 'center',
        verticalAlign: 'start',
        fluid: true,
      },
      {
        form: async () => createHomeForm(),
      },
    );
  };
}
`;
}

function buildMainFileSource(options: {
  preservedImports: string[];
  prelude: string;
  useCalls: string[];
  mountSelector: string;
}): string {
  const sections: string[] = [];

  sections.push(
    `${GENERATED_MARKER}
import { createApp, defineComponent, h } from 'vue';
import { createVuetify } from 'vuetify';
import * as components from 'vuetify/components';
import * as directives from 'vuetify/directives';
import '@mdi/font/css/materialdesignicons.css';
import 'vuetify/styles';
import 'vuetify-extended/lib/esm/css/index.css';
import { initializeBootstrap } from './bootstrap';`,
  );

  if (options.preservedImports.length > 0) {
    sections.push(options.preservedImports.join('\n'));
  }

  sections.push(`const vuetify = createVuetify({
  components,
  directives,
});

const bootstrap = initializeBootstrap();`);

  if (options.prelude) {
    sections.push(options.prelude);
  }

  sections.push(`const Root = defineComponent({
  name: 'VuetifyExtendedHostApp',
  setup() {
    return () => [
      h(bootstrap.component),
      h(bootstrap.dialogs),
      h(bootstrap.notifications),
    ];
  },
});

const app = createApp(Root);
app.use(vuetify);
app.use(bootstrap.plugin);`);

  if (options.useCalls.length > 0) {
    sections.push(options.useCalls.map(useCall => `app.use(${useCall});`).join('\n'));
  }

  sections.push(`app.mount(${options.mountSelector});
bootstrap.validate({ warn: true, requireApi: false });`);

  return sections.filter(Boolean).join('\n\n') + '\n';
}

function dedupe(values: string[]): string[] {
  return Array.from(new Set(values));
}

function collectMatches(source: string, expression: RegExp): RegExpExecArray[] {
  const flags = expression.flags.includes('g') ? expression.flags : `${expression.flags}g`;
  const matcher = new RegExp(expression.source, flags);
  const matches: RegExpExecArray[] = [];
  let match = matcher.exec(source);

  while (match) {
    matches.push(match);
    match = matcher.exec(source);
  }

  return matches;
}

function serializeString(value: string | undefined): string {
  return JSON.stringify(value || '');
}

function serializeUITextDescriptor(key: string, fallback: string): string {
  return `{ key: ${serializeString(key)}, fallback: ${serializeString(fallback)} }`;
}

function defaultSocketURL(apiURL: string): string {
  return `${apiURL.replace(/\/+$/, '')}/realtime`;
}

function fileExists(file: string): boolean {
  return fs.existsSync(file);
}

function relativeToCwd(cwd: string, absolutePath: string): string {
  return path.relative(cwd, absolutePath) || path.basename(absolutePath);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
