import fs from 'node:fs';
import path from 'node:path';
import * as readline from 'node:readline';

export interface CreateCommandOptions {
  cwd: string;
  force: boolean;
  dryRun: boolean;
  interactive: boolean;
  stdin: NodeJS.ReadableStream;
  stdout: Pick<typeof process.stdout, 'write'>;
  stderr: Pick<typeof process.stderr, 'write'>;
  values?: Record<string, string>;
  positionals?: string[];
}

type ScriptExt = '.ts' | '.js';
type ReportMode = 'create' | 'edit' | 'display';
type MenuItemTarget = 'report' | 'trigger' | 'collection' | 'dashboard';
type PrepareWritesResult = 'ok' | 'dry-run' | 'error';

interface PageAnswers {
  name: string;
  title: string;
  objectType: string;
  mode: ReportMode;
}

interface ReportAnswers extends PageAnswers {
  forms: number;
}

interface TriggerAnswers extends PageAnswers {
  idField: string;
  multiple: boolean;
}

interface CollectionAnswers extends TriggerAnswers {
  withReport: boolean;
  withTrigger: boolean;
}

interface MenuItemAnswers {
  page: string;
  target: MenuItemTarget;
  mode: ReportMode;
  text: string;
  subText: string;
  icon: string;
  color: string;
  menuFile?: string;
}

interface SubMenuAnswers {
  name: string;
  title: string;
  text: string;
  subText: string;
  icon: string;
  color: string;
  parent?: string;
  menuFile?: string;
}

interface FormStepAnswers {
  page: string;
  step: number;
  title: string;
}

interface FileWrite {
  file: string;
  content: string;
}

const GENERATED_MARKER = '// Generated by vuetify-ext';
const MENU_IMPORT_MARKER = '// vuetify-ext:menu-imports';
const MENU_ITEM_MARKER = '// vuetify-ext:menu-items';
const REPORT_IMPORT_MARKER = '// vuetify-ext:report-form-imports';
const REPORT_RESOLVER_MARKER = '// vuetify-ext:report-form-resolver';
const FORM_PARTS_MARKER = '// vuetify-ext:form-parts';
const FORM_FIELDS_MARKER_PREFIX = '// vuetify-ext:part:';

export const __testing = {
  resolveFormStepPageContext,
};

export async function runCreateReportCommand(options: CreateCommandOptions): Promise<number> {
  const ext = resolveProjectScriptExtension(options.cwd);
  const answers = await resolveReportAnswers(options);
  if (!answers) {
    return 1;
  }

  const pageDir = path.join(options.cwd, 'src/pages', answers.name);
  const pascalName = toPascalCase(answers.name);
  const writes = buildReportWrites(pageDir, ext, answers, pascalName);
  const ok = prepareWrites(options, writes);
  if (ok === 'error') {
    return 1;
  }
  if (ok === 'dry-run') {
    options.stdout.write(`- ${relativeToCwd(options.cwd, path.join(pageDir, `index${ext}`))}\n`);
    return 0;
  }

  writeFiles(writes);
  ensureIndexExports(pageDir, ext, [
    `export { create${pascalName}Form } from './form';`,
    `export { create${pascalName}Report } from './report';`,
  ]);

  writeSuccess(options, 'Report scaffolding created successfully', [
    ...writes.map((entry) => entry.file),
    path.join(pageDir, `index${ext}`),
  ]);
  options.stdout.write(
    '\nNext steps:\n' +
      `1. Review src/pages/${answers.name}/form${ext} and replace starter fields with your real form.\n` +
      `2. Review src/pages/${answers.name}/report${ext} and adjust title, mode, and multi-step behavior.\n` +
      `3. Run "vuetify-ext create menu-item --page ${answers.name} --target report" when you want it in the main menu.\n`,
  );

  return 0;
}

export async function runCreateTriggerCommand(options: CreateCommandOptions): Promise<number> {
  const ext = resolveProjectScriptExtension(options.cwd);
  const answers = await resolveTriggerAnswers(options);
  if (!answers) {
    return 1;
  }

  const pageDir = path.join(options.cwd, 'src/pages', answers.name);
  const pascalName = toPascalCase(answers.name);
  const writes = buildTriggerWrites(pageDir, ext, answers, pascalName);
  const ok = prepareWrites(options, writes);
  if (ok === 'error') {
    return 1;
  }
  if (ok === 'dry-run') {
    options.stdout.write(`- ${relativeToCwd(options.cwd, path.join(pageDir, `index${ext}`))}\n`);
    return 0;
  }

  writeFiles(writes);
  ensureIndexExports(pageDir, ext, [
    `export { create${pascalName}Trigger } from './trigger';`,
  ]);

  writeSuccess(options, 'Trigger scaffolding created successfully', [
    ...writes.map((entry) => entry.file),
    path.join(pageDir, `index${ext}`),
  ]);
  options.stdout.write(
    '\nNext steps:\n' +
      `1. Replace the starter in-memory rows in src/pages/${answers.name}/trigger${ext} with your API-backed load/query logic.\n` +
      `2. Adjust trigger headers, query fields, and side buttons to match your workflow.\n` +
      `3. Run "vuetify-ext create menu-item --page ${answers.name} --target trigger" when you want it in the main menu.\n`,
  );

  return 0;
}

export async function runCreateCollectionCommand(options: CreateCommandOptions): Promise<number> {
  const ext = resolveProjectScriptExtension(options.cwd);
  const answers = await resolveCollectionAnswers(options);
  if (!answers) {
    return 1;
  }

  const pageDir = path.join(options.cwd, 'src/pages', answers.name);
  const pascalName = toPascalCase(answers.name);
  const expectedReportFactory = `create${pascalName}Report`;
  const expectedTriggerFactory = `create${pascalName}Trigger`;

  if (!answers.withReport && !verifyExpectedPageExport(path.join(pageDir, `report${ext}`), expectedReportFactory)) {
    options.stderr.write(
      `[vuetify-ext] ${relativeToCwd(options.cwd, path.join(pageDir, `report${ext}`))} is missing the expected export ${expectedReportFactory}.\n` +
        'Either allow the command to scaffold the report or create it first using the standard factory name.\n',
    );
    return 1;
  }

  if (!answers.withTrigger && !verifyExpectedPageExport(path.join(pageDir, `trigger${ext}`), expectedTriggerFactory)) {
    options.stderr.write(
      `[vuetify-ext] ${relativeToCwd(options.cwd, path.join(pageDir, `trigger${ext}`))} is missing the expected export ${expectedTriggerFactory}.\n` +
        'Either allow the command to scaffold the trigger or create it first using the standard factory name.\n',
    );
    return 1;
  }

  const writes: FileWrite[] = [];

  if (answers.withReport) {
    writes.push(...buildReportWrites(pageDir, ext, {
      name: answers.name,
      title: answers.title,
      objectType: answers.objectType,
      mode: answers.mode,
      forms: 1,
    }, pascalName));
  }

  if (answers.withTrigger) {
    writes.push(...buildTriggerWrites(pageDir, ext, answers, pascalName));
  }

  writes.push(...buildCollectionWrites(pageDir, ext, answers, pascalName));

  const ok = prepareWrites(options, writes);
  if (ok === 'error') {
    return 1;
  }
  if (ok === 'dry-run') {
    options.stdout.write(`- ${relativeToCwd(options.cwd, path.join(pageDir, `index${ext}`))}\n`);
    return 0;
  }

  writeFiles(writes);

  const exports = [
    `export { create${pascalName}Collection } from './collection';`,
  ];
  if (answers.withReport || fileExists(path.join(pageDir, `report${ext}`))) {
    exports.unshift(`export { create${pascalName}Report } from './report';`);
  }
  if (answers.withTrigger || fileExists(path.join(pageDir, `trigger${ext}`))) {
    exports.unshift(`export { create${pascalName}Trigger } from './trigger';`);
  }
  if (answers.withReport || fileExists(path.join(pageDir, `form${ext}`))) {
    exports.unshift(`export { create${pascalName}Form } from './form';`);
  }
  ensureIndexExports(pageDir, ext, exports);

  writeSuccess(options, 'Collection scaffolding created successfully', [
    ...writes.map((entry) => entry.file),
    path.join(pageDir, `index${ext}`),
  ]);
  options.stdout.write(
    '\nNext steps:\n' +
      `1. Review src/pages/${answers.name}/collection${ext} and connect it to your real report/trigger behavior.\n` +
      `2. Replace the starter trigger dataset with live loading if needed.\n` +
      `3. Run "vuetify-ext create menu-item --page ${answers.name} --target collection" when you want it in the main menu.\n`,
  );

  return 0;
}

export async function runCreateMenuItemCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveMenuItemAnswers(options);
  if (!answers) {
    return 1;
  }
  const ext = resolveExistingPageScriptExtension(options.cwd, answers.page) || resolveProjectScriptExtension(options.cwd);

  const pageIndexFile = path.join(options.cwd, 'src/pages', answers.page, `index${ext}`);
  const expectedFactoryName = `create${toPascalCase(answers.page)}${capitalize(answers.target)}`;
  if (!verifyExpectedPageExport(pageIndexFile, expectedFactoryName)) {
    options.stderr.write(
      `[vuetify-ext] ${relativeToCwd(options.cwd, pageIndexFile)} is missing the expected export ${expectedFactoryName}.\n` +
        `Create the page first or export ${expectedFactoryName} from the page index before adding the menu item.\n`,
    );
    return 1;
  }

  const menuFile = resolveMenuFile(options.cwd, ext, answers.menuFile);
  if (!menuFile) {
    options.stderr.write(
      '[vuetify-ext] Could not locate src/menu/index.ts or src/menu/index.js.\n' +
        'Run "vuetify-ext bootstrap app" first or pass --menu-file.\n',
    );
    return 1;
  }

  if (!fileExists(menuFile)) {
    options.stderr.write(`[vuetify-ext] Menu file not found: ${relativeToCwd(options.cwd, menuFile)}\n`);
    return 1;
  }

  const source = fs.readFileSync(menuFile, 'utf8');
  const patched = patchMenuFile(source, answers);
  if (!patched) {
    options.stderr.write(
      `[vuetify-ext] Could not patch ${relativeToCwd(options.cwd, menuFile)} automatically.\n` +
        'Make sure the file contains createMainMenu() with a children: async () => [ ... ] block.\n',
    );
    return 1;
  }

  if (options.dryRun) {
    options.stdout.write('[vuetify-ext] Dry run only. The following file would be updated:\n');
    options.stdout.write(`- ${relativeToCwd(options.cwd, menuFile)}\n`);
    return 0;
  }

  fs.writeFileSync(menuFile, patched, 'utf8');
  writeSuccess(options, 'Menu item added successfully', [menuFile]);
  options.stdout.write(
    '\nNext steps:\n' +
      `1. Open ${relativeToCwd(options.cwd, menuFile)} and confirm the inserted import and menu item labels.\n` +
      '2. Run the app and verify the new menu card opens the expected page.\n',
  );

  return 0;
}

export async function runCreateSubMenuCommand(options: CreateCommandOptions): Promise<number> {
  const initialExt = resolveProjectScriptExtension(options.cwd);
  const answers = await resolveSubMenuAnswers(options);
  if (!answers) {
    return 1;
  }

  const parentMenuFile = resolveParentMenuFile(options.cwd, initialExt, answers.parent, answers.menuFile);
  if (!parentMenuFile) {
    options.stderr.write(
      '[vuetify-ext] Could not locate the parent menu file.\n' +
        'Run "vuetify-ext bootstrap app" first, pass --parent <menu-name>, or use --menu-file.\n',
    );
    return 1;
  }

  if (!fileExists(parentMenuFile)) {
    options.stderr.write(`[vuetify-ext] Parent menu file not found: ${relativeToCwd(options.cwd, parentMenuFile)}\n`);
    return 1;
  }

  const ext = normalizeScriptExt(path.extname(parentMenuFile)) || initialExt;
  const subMenuFile = path.join(options.cwd, 'src/menu', `${answers.name}${ext}`);
  if (path.resolve(parentMenuFile) === path.resolve(subMenuFile)) {
    options.stderr.write('[vuetify-ext] The submenu file cannot also be the parent menu file.\n');
    return 1;
  }

  const pascalName = toPascalCase(answers.name);
  const writes: FileWrite[] = [
    {
      file: subMenuFile,
      content: buildSubMenuFileSource(answers, pascalName),
    },
  ];

  const ok = prepareWrites(options, writes);
  if (ok === 'error') {
    return 1;
  }

  const parentSource = fs.readFileSync(parentMenuFile, 'utf8');
  const patchedParentSource = patchMenuFileWithSubMenu(parentSource, parentMenuFile, subMenuFile, answers, pascalName);
  if (!patchedParentSource) {
    options.stderr.write(
      `[vuetify-ext] Could not patch ${relativeToCwd(options.cwd, parentMenuFile)} automatically.\n` +
        'Make sure the file contains create...Menu() with a children: async () => [ ... ] block.\n',
    );
    return 1;
  }

  if (options.dryRun) {
    options.stdout.write('[vuetify-ext] Dry run only. The following files would be written or updated:\n');
    options.stdout.write(`- ${relativeToCwd(options.cwd, subMenuFile)}\n`);
    options.stdout.write(`- ${relativeToCwd(options.cwd, parentMenuFile)}\n`);
    return 0;
  }

  writeFiles(writes);
  fs.writeFileSync(parentMenuFile, patchedParentSource, 'utf8');

  writeSuccess(options, 'Sub-menu created successfully', [
    subMenuFile,
    parentMenuFile,
  ]);
  options.stdout.write(
    '\nNext steps:\n' +
      `1. Add child items to ${relativeToCwd(options.cwd, subMenuFile)} with "vuetify-ext create menu-item --menu-file ${relativeToCwd(options.cwd, subMenuFile)}".\n` +
      `2. Review ${relativeToCwd(options.cwd, parentMenuFile)} and confirm the inserted parent menu card styling.\n` +
      '3. Run the app and verify the new card opens the nested menu.\n',
  );

  return 0;
}

export async function runCreateFormCommand(options: CreateCommandOptions): Promise<number> {
  const initialExt = resolveProjectScriptExtension(options.cwd);
  const answers = await resolveFormStepAnswers(options, initialExt);
  if (!answers) {
    return 1;
  }
  const ext = resolveExistingPageScriptExtension(options.cwd, answers.page) || initialExt;

  const pageDir = path.join(options.cwd, 'src/pages', answers.page);
  const pascalName = toPascalCase(answers.page);
  const reportFile = path.join(pageDir, `report${ext}`);
  const indexFile = path.join(pageDir, `index${ext}`);
  const formFile = path.join(pageDir, formFileNameForStep(answers.step, ext));
  const formFunctionName = formFunctionNameForStep(pascalName, answers.step);
  const baseFormFunctionName = formFunctionNameForStep(pascalName, 1);
  const reportFunctionName = `create${pascalName}Report`;

  if (!verifyExpectedPageExport(reportFile, reportFunctionName)) {
    options.stderr.write(
      `[vuetify-ext] ${relativeToCwd(options.cwd, reportFile)} is missing the expected export ${reportFunctionName}.\n` +
        'Create the report first or export the standard factory name before adding form steps.\n',
    );
    return 1;
  }

  if (!verifyExpectedPageExport(path.join(pageDir, `form${ext}`), baseFormFunctionName)) {
    options.stderr.write(
      `[vuetify-ext] ${relativeToCwd(options.cwd, path.join(pageDir, `form${ext}`))} is missing the expected export ${baseFormFunctionName}.\n` +
        'The base form must use the standard factory name before adding more forms.\n',
    );
    return 1;
  }

  const reportSource = fs.readFileSync(reportFile, 'utf8');
  const currentForms = extractReportFormsCount(reportSource) || 1;
  if (answers.step <= 1) {
    options.stderr.write('[vuetify-ext] create form is intended for additional report steps. Use a step number of 2 or greater.\n');
    return 1;
  }
  if (answers.step > currentForms + 1) {
    options.stderr.write(
      `[vuetify-ext] The next available step is ${currentForms + 1}, but you requested step ${answers.step}.\n` +
        'Create intermediate steps first so the report flow stays contiguous.\n',
    );
    return 1;
  }

  if (!options.force && fileExists(formFile)) {
    options.stderr.write(
      `[vuetify-ext] ${relativeToCwd(options.cwd, formFile)} already exists.\n` +
        'Use --force to overwrite it.\n',
    );
    return 1;
  }

  const normalizedReportSource = ensureReportFormMarkers(reportSource, pascalName);
  const patchedReportSource = normalizedReportSource
    ? patchReportForNewForm(normalizedReportSource, {
        pascalName,
        step: answers.step,
        nextFormsCount: Math.max(currentForms, answers.step),
      })
    : patchLegacySingleFormReport(reportSource, {
        pascalName,
        step: answers.step,
        nextFormsCount: Math.max(currentForms, answers.step),
      });
  if (!patchedReportSource) {
    options.stderr.write(
      `[vuetify-ext] Could not patch ${relativeToCwd(options.cwd, reportFile)} automatically.\n` +
        'Make sure the report uses the standard create<PageName>Report scaffold shape.\n',
    );
    return 1;
  }

  const nextIndexSource = appendExportLine(
    fileExists(indexFile) ? fs.readFileSync(indexFile, 'utf8') : `${GENERATED_MARKER} page index\n`,
    `export { ${formFunctionName} } from './${formImportStemForStep(answers.step)}';`,
  );

  const formSource = buildAdditionalFormFileSource(ext, {
    title: answers.title,
    mode: 'display',
    forms: answers.step,
    name: answers.page,
    objectType: answers.page,
  }, pascalName, answers.step);

  if (options.dryRun) {
    options.stdout.write('[vuetify-ext] Dry run only. The following files would be written or updated:\n');
    options.stdout.write(`- ${relativeToCwd(options.cwd, formFile)}\n`);
    options.stdout.write(`- ${relativeToCwd(options.cwd, reportFile)}\n`);
    options.stdout.write(`- ${relativeToCwd(options.cwd, indexFile)}\n`);
    return 0;
  }

  fs.mkdirSync(pageDir, { recursive: true });
  fs.writeFileSync(formFile, formSource, 'utf8');
  fs.writeFileSync(reportFile, patchedReportSource, 'utf8');
  fs.writeFileSync(indexFile, nextIndexSource, 'utf8');

  writeSuccess(options, 'Form step added successfully', [
    formFile,
    reportFile,
    indexFile,
  ]);
  options.stdout.write(
    '\nNext steps:\n' +
      `1. Review ${relativeToCwd(options.cwd, formFile)} and replace the starter fields with the fields for step ${answers.step}.\n` +
      `2. Review ${relativeToCwd(options.cwd, reportFile)} and confirm the inserted report step order.\n` +
      '3. Run the app and verify Prev/Next navigation now includes the new form step.\n',
  );

  return 0;
}

function buildReportWrites(pageDir: string, ext: ScriptExt, answers: ReportAnswers, pascalName: string): FileWrite[] {
  return [
    {
      file: path.join(pageDir, `form${ext}`),
      content: buildFormFileSource(ext, answers, pascalName),
    },
    {
      file: path.join(pageDir, `report${ext}`),
      content: buildReportFileSource(ext, answers, pascalName),
    },
  ];
}

function buildTriggerWrites(pageDir: string, ext: ScriptExt, answers: TriggerAnswers, pascalName: string): FileWrite[] {
  return [
    {
      file: path.join(pageDir, `trigger${ext}`),
      content: buildTriggerFileSource(ext, answers, pascalName),
    },
  ];
}

function buildCollectionWrites(pageDir: string, ext: ScriptExt, answers: CollectionAnswers, pascalName: string): FileWrite[] {
  return [
    {
      file: path.join(pageDir, `collection${ext}`),
      content: buildCollectionFileSource(ext, answers, pascalName),
    },
  ];
}

function buildFormFileSource(ext: ScriptExt, answers: ReportAnswers, pascalName: string): string {
  return buildNamedFormFileSource(ext, answers, pascalName, 1);
}

function buildAdditionalFormFileSource(ext: ScriptExt, answers: ReportAnswers, pascalName: string, step: number): string {
  return buildNamedFormFileSource(ext, answers, pascalName, step);
}

function buildNamedFormFileSource(ext: ScriptExt, answers: ReportAnswers, pascalName: string, step: number): string {
  const typeImport = ext === '.ts' ? ', type ReportMode' : '';
  const modeSignature = ext === '.ts' ? `mode: ReportMode = 'display'` : `mode = 'display'`;
  const functionName = formFunctionNameForStep(pascalName, step);
  const defaultTitle = step <= 1 ? `${answers.title} Form` : answers.title;
  const partMarker = `${FORM_FIELDS_MARKER_PREFIX}1:fields`;

  return `${GENERATED_MARKER} ${step <= 1 ? 'create report' : 'create form'}
import { $FD, $FM, $PT${typeImport} } from 'vuetify-extended';

export function ${functionName}(${modeSignature}) {
  return $FM(
    {
      title: ${serializeString(defaultTitle)},
      mode,
      width: 920,
    },
    {
      children: () => [
        ${FORM_PARTS_MARKER}
        $PT(
          { cols: 12, dense: true },
          {
            children: () => [
              ${partMarker}
              $FD({
                label: 'Name',
                storage: 'name',
                cols: 6,
                required: true,
              }),
              $FD({
                label: 'Code',
                storage: 'code',
                cols: 6,
              }),
              $FD({
                label: 'Description',
                storage: 'description',
                type: 'textarea',
                cols: 12,
              }),
              $FD({
                type: 'label',
                label: 'Replace these starter fields with the real form schema for this page.',
                cols: 12,
              }),
            ],
          },
        ),
      ],
    },
  );
}
`;
}

function buildReportFileSource(ext: ScriptExt, answers: ReportAnswers, pascalName: string): string {
  const typeImport = ext === '.ts' ? ', type ReportMode' : '';
  const modeSignature = ext === '.ts' ? `mode: ReportMode = ${serializeString(answers.mode)}` : `mode = ${serializeString(answers.mode)}`;

  return `${GENERATED_MARKER} create report
import { $RP${typeImport} } from 'vuetify-extended';
import { create${pascalName}Form } from './form';
${REPORT_IMPORT_MARKER}

export function create${pascalName}Report(${modeSignature}) {
  return $RP(
    {
      title: ${serializeString(answers.title)},
      objectType: ${serializeString(answers.objectType)},
      forms: ${Math.max(1, answers.forms)},
      mode,
      horizontalAlign: 'center',
      verticalAlign: 'start',
      fluid: true,
    },
    {
      form: async (_props, _context, index) => {
        ${REPORT_RESOLVER_MARKER}
        if (index === 0) return create${pascalName}Form(mode);
        return undefined;
      },
    },
  );
}
`;
}

function buildTriggerFileSource(ext: ScriptExt, answers: TriggerAnswers, pascalName: string): string {
  const typeImport = ext === '.ts' ? ', type ReportMode' : '';
  const modeSignature = ext === '.ts' ? `mode: ReportMode = ${serializeString(answers.mode)}` : `mode = ${serializeString(answers.mode)}`;
  const dataPrefix = sanitizeIdentifier(answers.objectType || answers.name).toUpperCase();
  const itemAccessor = ext === '.ts' ? '(item as Record<string, any>)[key]' : 'item[key]';

  return `${GENERATED_MARKER} create trigger
import { $FD, $TG${typeImport} } from 'vuetify-extended';

const ${dataPrefix}_HEADERS = [
  { title: 'Name', key: 'name' },
  { title: 'Description', key: 'description' },
  { title: 'Status', key: 'status' },
];

const ${dataPrefix}_ROWS = [
  { ${serializeKey(answers.idField)}: '${answers.name}-1', name: '${pascalName} Example 1', description: 'Starter row one', status: 'active' },
  { ${serializeKey(answers.idField)}: '${answers.name}-2', name: '${pascalName} Example 2', description: 'Starter row two', status: 'draft' },
  { ${serializeKey(answers.idField)}: '${answers.name}-3', name: '${pascalName} Example 3', description: 'Starter row three', status: 'archived' },
];

export function create${pascalName}Trigger(${modeSignature}) {
  return $TG(
    {
      title: ${serializeString(`${answers.title} Trigger`)},
      subtitle: 'Starter trigger generated by vuetify-ext.',
      objectType: ${serializeString(answers.objectType)},
      idField: ${serializeString(answers.idField)},
      multiple: ${answers.multiple ? 'true' : 'false'},
      mode,
      queryFields: ['name', 'description', 'status'],
      headers: ${dataPrefix}_HEADERS,
      fluid: true,
      canPrint: false,
      canExport: false,
    },
    {
      headers: async () => ${dataPrefix}_HEADERS,
      load: async (searchText) => {
        const search = String(searchText || '').trim().toLowerCase();
        if (!search) {
          return ${dataPrefix}_ROWS;
        }

        return ${dataPrefix}_ROWS.filter((item) =>
          ['name', 'description', 'status'].some((key) =>
            String(${itemAccessor} || '').toLowerCase().includes(search),
          ),
        );
      },
      topChildren: () => [
        $FD({
          type: 'label',
          label: 'Replace the in-memory load() function with your API-backed query when ready.',
          cols: 12,
        }),
      ],
    },
  );
}
`;
}

function buildCollectionFileSource(ext: ScriptExt, answers: CollectionAnswers, pascalName: string): string {
  const typeImport = ext === '.ts' ? ', type ReportMode' : '';
  const modeSignature = ext === '.ts' ? `mode: ReportMode = ${serializeString(answers.mode)}` : `mode = ${serializeString(answers.mode)}`;

  return `${GENERATED_MARKER} create collection
import { $COL${typeImport} } from 'vuetify-extended';
import { create${pascalName}Report } from './report';
import { create${pascalName}Trigger } from './trigger';

export function create${pascalName}Collection(${modeSignature}) {
  return $COL(
    {
      objectType: ${serializeString(answers.objectType)},
      idField: ${serializeString(answers.idField)},
      multiple: ${answers.multiple ? 'true' : 'false'},
      mode,
    },
    {
      trigger: async () => create${pascalName}Trigger(mode),
      report: async () => create${pascalName}Report(mode),
    },
  );
}
`;
}

async function resolveReportAnswers(options: CreateCommandOptions): Promise<ReportAnswers | undefined> {
  const input = normalizePageInput(options);
  if (!options.interactive) {
    return validateReportAnswers(input, options.stderr);
  }

  const rl = readline.createInterface({
    input: options.stdin,
    output: options.stdout as NodeJS.WritableStream,
  });

  try {
    const name = await promptText(rl, 'Page name/folder', input.name || 'sample-report');
    const title = await promptText(rl, 'Report title', input.title || humanizeName(name));
    const objectType = await promptText(rl, 'Object type', input.objectType || slugifyName(name));
    const mode = await promptChoice(rl, 'Default mode (create/edit/display)', ['create', 'edit', 'display'], input.mode || 'display') as ReportMode;
    const forms = await promptNumber(rl, 'Number of forms/steps', normalizePositiveInt(input.forms, 1), 1);
    return {
      name: slugifyName(name),
      title,
      objectType,
      mode,
      forms,
    };
  } finally {
    rl.close();
  }
}

async function resolveTriggerAnswers(options: CreateCommandOptions): Promise<TriggerAnswers | undefined> {
  const input = normalizePageInput(options);
  if (!options.interactive) {
    return validateTriggerAnswers(input, options.stderr);
  }

  const rl = readline.createInterface({
    input: options.stdin,
    output: options.stdout as NodeJS.WritableStream,
  });

  try {
    const name = await promptText(rl, 'Page name/folder', input.name || 'sample-trigger');
    const title = await promptText(rl, 'Trigger title', input.title || humanizeName(name));
    const objectType = await promptText(rl, 'Object type', input.objectType || slugifyName(name));
    const idField = await promptText(rl, 'ID field', input.idField || '_id');
    const mode = await promptChoice(rl, 'Default mode (create/edit/display)', ['create', 'edit', 'display'], input.mode || 'edit') as ReportMode;
    const multiple = await promptBoolean(rl, 'Allow multiple selection', input.multiple === true);
    return {
      name: slugifyName(name),
      title,
      objectType,
      idField,
      mode,
      multiple,
    };
  } finally {
    rl.close();
  }
}

async function resolveFormStepAnswers(options: CreateCommandOptions, ext: ScriptExt): Promise<FormStepAnswers | undefined> {
  const values = options.values || {};
  const input = {
    page: values['page'] || values['name'] || options.positionals?.[0],
    step: normalizePositiveInt(values['step'], 0),
    title: values['title'],
  };

  if (!options.interactive) {
    const resolvedExt = input.page ? (resolveExistingPageScriptExtension(options.cwd, slugifyName(input.page)) || ext) : ext;
    return validateFormStepAnswers(input, options, resolvedExt);
  }

  const rl = readline.createInterface({
    input: options.stdin,
    output: options.stdout as NodeJS.WritableStream,
  });

  try {
    const page = slugifyName(await promptText(rl, 'Page folder name', input.page || 'sample-report'));
    const context = resolveFormStepPageContext(options.cwd, page, ext);
    const nextStep = context.currentForms + 1;
    const step = await promptNumber(rl, 'Form step number', input.step > 0 ? input.step : nextStep, 2);
    const defaultTitle = `${context.reportTitle || humanizeName(page)} Form ${step}`;
    const title = await promptText(rl, 'Form title', input.title || defaultTitle);
    return {
      page,
      step,
      title,
    };
  } finally {
    rl.close();
  }
}

async function resolveCollectionAnswers(options: CreateCommandOptions): Promise<CollectionAnswers | undefined> {
  const input = normalizePageInput(options);
  if (!options.interactive) {
    return validateCollectionAnswers(input, options.stderr);
  }

  const rl = readline.createInterface({
    input: options.stdin,
    output: options.stdout as NodeJS.WritableStream,
  });

  try {
    const name = await promptText(rl, 'Page name/folder', input.name || 'sample-collection');
    const title = await promptText(rl, 'Companion report title', input.title || humanizeName(name));
    const objectType = await promptText(rl, 'Object type', input.objectType || slugifyName(name));
    const idField = await promptText(rl, 'ID field', input.idField || '_id');
    const mode = await promptChoice(rl, 'Default mode (create/edit/display)', ['create', 'edit', 'display'], input.mode || 'edit') as ReportMode;
    const multiple = await promptBoolean(rl, 'Allow multiple selection', input.multiple === true);
    const withReport = await promptBoolean(rl, 'Scaffold a companion report', input.withReport !== false);
    const withTrigger = await promptBoolean(rl, 'Scaffold a companion trigger', input.withTrigger !== false);
    return {
      name: slugifyName(name),
      title,
      objectType,
      idField,
      mode,
      multiple,
      withReport,
      withTrigger,
    };
  } finally {
    rl.close();
  }
}

async function resolveMenuItemAnswers(options: CreateCommandOptions): Promise<MenuItemAnswers | undefined> {
  const values = options.values || {};
  const input: Partial<MenuItemAnswers> = {
    page: values['page'] || options.positionals?.[0],
    target: values['target'] as MenuItemTarget | undefined,
    mode: values['mode'] as ReportMode | undefined,
    text: values['text'],
    subText: values['sub-text'],
    icon: values['icon'],
    color: values['color'],
    menuFile: values['menu-file'],
  };

  if (!options.interactive) {
    return validateMenuItemAnswers(input, options.stderr);
  }

  const rl = readline.createInterface({
    input: options.stdin,
    output: options.stdout as NodeJS.WritableStream,
  });

  try {
    const page = await promptText(rl, 'Page folder name', input.page || 'home');
    const target = await promptChoice(rl, 'Target type (report/trigger/collection/dashboard)', ['report', 'trigger', 'collection', 'dashboard'], input.target || 'report') as MenuItemTarget;
    const text = await promptText(rl, 'Menu card text', input.text || humanizeName(page));
    const subTextDefault = target === 'trigger'
      ? `Open the ${humanizeName(page)} trigger.`
      : target === 'collection'
        ? `Open the ${humanizeName(page)} collection workflow.`
        : target === 'dashboard'
          ? `Open the ${humanizeName(page)} dashboard.`
        : `Open the ${humanizeName(page)} report.`;
    const subText = await promptText(rl, 'Menu card sub text', input.subText || subTextDefault);
    const icon = await promptText(rl, 'Icon', input.icon || defaultMenuIcon(target));
    const color = await promptText(rl, 'Color', input.color || defaultMenuColor(target));
    const mode = await promptChoice(rl, 'Default mode (create/edit/display)', ['create', 'edit', 'display'], input.mode || defaultMenuMode(target)) as ReportMode;

    return {
      page: slugifyName(page),
      target,
      text,
      subText,
      icon,
      color,
      mode,
      menuFile: input.menuFile,
    };
  } finally {
    rl.close();
  }
}

async function resolveSubMenuAnswers(options: CreateCommandOptions): Promise<SubMenuAnswers | undefined> {
  const values = options.values || {};
  const input: Partial<SubMenuAnswers> = {
    name: values['name'] || options.positionals?.[0],
    title: values['title'],
    text: values['text'],
    subText: values['sub-text'],
    icon: values['icon'],
    color: values['color'],
    parent: values['parent'],
    menuFile: values['menu-file'],
  };

  if (!options.interactive) {
    return validateSubMenuAnswers(input, options.stderr);
  }

  const rl = readline.createInterface({
    input: options.stdin,
    output: options.stdout as NodeJS.WritableStream,
  });

  try {
    const name = slugifyName(await promptText(rl, 'Sub-menu file name', input.name || 'settings'));
    const title = await promptText(rl, 'Sub-menu title', input.title || humanizeName(name));
    const text = await promptText(rl, 'Parent menu card text', input.text || title);
    const subText = await promptText(rl, 'Parent menu card sub text', input.subText || `Open the ${title} menu.`);
    const icon = await promptText(rl, 'Icon', input.icon || 'mdi-folder-outline');
    const color = await promptText(rl, 'Color', input.color || 'primary');
    const parent = await promptText(rl, 'Parent menu (main or menu file slug)', input.parent || 'main');

    return {
      name,
      title,
      text,
      subText,
      icon,
      color,
      parent,
      menuFile: input.menuFile,
    };
  } finally {
    rl.close();
  }
}

function validateReportAnswers(input: any, stderr: Pick<typeof process.stderr, 'write'>): ReportAnswers | undefined {
  const missing = collectMissing(input, ['name', 'title', 'objectType']);
  if (missing.length > 0) {
    stderr.write(`[vuetify-ext] Missing required flags for create report:\n- ${missing.map(flagName).join('\n- ')}\n`);
    return undefined;
  }

  return {
    name: slugifyName(input.name),
    title: input.title,
    objectType: input.objectType,
    mode: normalizeMode(input.mode, 'display'),
    forms: normalizePositiveInt(input.forms, 1),
  };
}

function validateTriggerAnswers(input: any, stderr: Pick<typeof process.stderr, 'write'>): TriggerAnswers | undefined {
  const missing = collectMissing(input, ['name', 'title', 'objectType']);
  if (missing.length > 0) {
    stderr.write(`[vuetify-ext] Missing required flags for create trigger:\n- ${missing.map(flagName).join('\n- ')}\n`);
    return undefined;
  }

  return {
    name: slugifyName(input.name),
    title: input.title,
    objectType: input.objectType,
    idField: input.idField || '_id',
    mode: normalizeMode(input.mode, 'edit'),
    multiple: input.multiple === true,
  };
}

function validateCollectionAnswers(input: any, stderr: Pick<typeof process.stderr, 'write'>): CollectionAnswers | undefined {
  const missing = collectMissing(input, ['name', 'title', 'objectType']);
  if (missing.length > 0) {
    stderr.write(`[vuetify-ext] Missing required flags for create collection:\n- ${missing.map(flagName).join('\n- ')}\n`);
    return undefined;
  }

  return {
    name: slugifyName(input.name),
    title: input.title,
    objectType: input.objectType,
    idField: input.idField || '_id',
    mode: normalizeMode(input.mode, 'edit'),
    multiple: input.multiple === true,
    withReport: input.withReport !== false,
    withTrigger: input.withTrigger !== false,
  };
}

function validateMenuItemAnswers(
  input: Partial<MenuItemAnswers>,
  stderr: Pick<typeof process.stderr, 'write'>,
): MenuItemAnswers | undefined {
  const missing = collectMissing(input, ['page', 'target', 'text']);
  if (missing.length > 0) {
    stderr.write(`[vuetify-ext] Missing required flags for create menu-item:\n- ${missing.map(flagName).join('\n- ')}\n`);
    return undefined;
  }

  const target = input.target as MenuItemTarget;
  if (!['report', 'trigger', 'collection', 'dashboard'].includes(target)) {
    stderr.write(`[vuetify-ext] Invalid --target value: ${String(input.target)}. Expected report, trigger, collection, or dashboard.\n`);
    return undefined;
  }

  return {
    page: slugifyName(input.page!),
    target,
    mode: normalizeMode(input.mode, defaultMenuMode(target)),
    text: input.text!,
    subText: input.subText || (
      target === 'trigger'
        ? `Open the ${humanizeName(input.page!)} trigger.`
        : target === 'collection'
          ? `Open the ${humanizeName(input.page!)} collection workflow.`
          : target === 'dashboard'
            ? `Open the ${humanizeName(input.page!)} dashboard.`
          : `Open the ${humanizeName(input.page!)} report.`
    ),
    icon: input.icon || defaultMenuIcon(target),
    color: input.color || defaultMenuColor(target),
    menuFile: input.menuFile,
  };
}

function validateSubMenuAnswers(
  input: Partial<SubMenuAnswers>,
  stderr: Pick<typeof process.stderr, 'write'>,
): SubMenuAnswers | undefined {
  const missing = collectMissing(input, ['name']);
  if (missing.length > 0) {
    stderr.write(`[vuetify-ext] Missing required flags for create sub-menu:\n- ${missing.map(flagName).join('\n- ')}\n`);
    return undefined;
  }

  const name = slugifyName(input.name!);
  if (name === 'index') {
    stderr.write('[vuetify-ext] "index" is reserved for the main menu entry file. Choose another sub-menu name.\n');
    return undefined;
  }

  const title = input.title || humanizeName(name);
  return {
    name,
    title,
    text: input.text || title,
    subText: input.subText || `Open the ${title} menu.`,
    icon: input.icon || 'mdi-folder-outline',
    color: input.color || 'primary',
    parent: input.parent,
    menuFile: input.menuFile,
  };
}

function validateFormStepAnswers(
  input: { page?: string; step?: number; title?: string },
  options: CreateCommandOptions,
  ext: ScriptExt,
): FormStepAnswers | undefined {
  const missing: string[] = [];
  if (!input.page) missing.push('--page');
  if (missing.length > 0) {
    options.stderr.write(`[vuetify-ext] Missing required flags for create form:\n- ${missing.join('\n- ')}\n`);
    return undefined;
  }

  const page = slugifyName(input.page!);
  const reportFile = path.join(options.cwd, 'src/pages', page, `report${ext}`);
  if (!fileExists(reportFile)) {
    options.stderr.write(`[vuetify-ext] Report file not found: ${relativeToCwd(options.cwd, reportFile)}\n`);
    return undefined;
  }

  const reportSource = fs.readFileSync(reportFile, 'utf8');
  const currentForms = extractReportFormsCount(reportSource) || 1;
  const step = input.step && input.step >= 2 ? input.step : currentForms + 1;
  const title = input.title || `${extractReportTitle(reportSource) || humanizeName(page)} Form ${step}`;

  return {
    page,
    step,
    title,
  };
}

function normalizePageInput(options: CreateCommandOptions) {
  const values = options.values || {};
  return {
    name: values['name'] || options.positionals?.[0],
    title: values['title'],
    objectType: values['object-type'],
    idField: values['id-field'],
    mode: values['mode'],
    forms: values['forms'],
    multiple: parseOptionalBoolean(values['multiple']),
    withReport: parseOptionalBoolean(values['with-report']),
    withTrigger: parseOptionalBoolean(values['with-trigger']),
  };
}

function prepareWrites(options: CreateCommandOptions, writes: FileWrite[]): PrepareWritesResult {
  const duplicates = new Set<string>();
  const existing: string[] = [];

  for (const write of writes) {
    if (duplicates.has(write.file)) {
      continue;
    }
    duplicates.add(write.file);
    if (!options.force && fileExists(write.file)) {
      existing.push(write.file);
    }
  }

  if (existing.length > 0) {
    options.stderr.write(
      `[vuetify-ext] The following files already exist:\n- ${existing.map(file => relativeToCwd(options.cwd, file)).join('\n- ')}\n` +
        'Use --force to overwrite them.\n',
    );
    return 'error';
  }

  if (options.dryRun) {
    options.stdout.write('[vuetify-ext] Dry run only. The following files would be written:\n');
    for (const write of writes) {
      options.stdout.write(`- ${relativeToCwd(options.cwd, write.file)}\n`);
    }
    return 'dry-run';
  }

  return 'ok';
}

function writeFiles(writes: FileWrite[]) {
  for (const write of writes) {
    fs.mkdirSync(path.dirname(write.file), { recursive: true });
    fs.writeFileSync(write.file, write.content, 'utf8');
  }
}

function writeSuccess(options: CreateCommandOptions, heading: string, files: string[]) {
  const uniqueFiles = Array.from(new Set(files));
  options.stdout.write(`[vuetify-ext] ${heading}:\n`);
  for (const file of uniqueFiles) {
    options.stdout.write(`- ${relativeToCwd(options.cwd, file)}\n`);
  }
}

function ensureIndexExports(pageDir: string, ext: ScriptExt, exportLines: string[]) {
  const indexFile = path.join(pageDir, `index${ext}`);
  const current = fileExists(indexFile) ? fs.readFileSync(indexFile, 'utf8') : `${GENERATED_MARKER} page index\n`;
  const lines = current.trimEnd().split('\n').filter(Boolean);

  for (const exportLine of exportLines) {
    if (!lines.includes(exportLine)) {
      lines.push(exportLine);
    }
  }

  fs.mkdirSync(pageDir, { recursive: true });
  fs.writeFileSync(indexFile, `${lines.join('\n')}\n`, 'utf8');
}

function patchMenuFile(source: string, answers: MenuItemAnswers): string | undefined {
  const page = answers.page;
  const pascalName = toPascalCase(page);
  const importLines = buildMenuImportLines(answers.target, pascalName, page);
  const itemMarker = `// vuetify-ext:menu-item:${answers.target}:${page}`;

  if (source.includes(itemMarker)) {
    return source;
  }

  let next = ensureMenuMarkers(source);
  if (!next) {
    return undefined;
  }

  for (const importLine of importLines) {
    if (!next.includes(importLine)) {
      next = next.replace(MENU_IMPORT_MARKER, `${MENU_IMPORT_MARKER}\n${importLine}`);
    }
  }

  const itemBlock = buildMenuItemBlock(answers, pascalName, itemMarker);
  next = next.replace(MENU_ITEM_MARKER, `${MENU_ITEM_MARKER}\n${itemBlock}`);

  return next;
}

function patchMenuFileWithSubMenu(
  source: string,
  parentMenuFile: string,
  subMenuFile: string,
  answers: SubMenuAnswers,
  pascalName: string,
): string | undefined {
  const itemMarker = `// vuetify-ext:sub-menu:${answers.name}`;
  if (source.includes(itemMarker)) {
    return source;
  }

  let next = ensureMenuMarkers(source);
  if (!next) {
    return undefined;
  }

  const importLine = `import { create${pascalName}Menu } from ${serializeString(buildRelativeImportSpecifier(parentMenuFile, subMenuFile))};`;
  if (!next.includes(importLine)) {
    next = next.replace(MENU_IMPORT_MARKER, `${MENU_IMPORT_MARKER}\n${importLine}`);
  }

  const itemBlock = buildSubMenuItemBlock(answers, pascalName, itemMarker);
  next = next.replace(MENU_ITEM_MARKER, `${MENU_ITEM_MARKER}\n${itemBlock}`);
  return next;
}

function ensureMenuMarkers(source: string): string | undefined {
  let next = source;

  if (!next.includes(MENU_IMPORT_MARKER)) {
    const importMatches = Array.from(next.matchAll(/^import .*$/gm));
    if (importMatches.length === 0) {
      return undefined;
    }
    const lastImport = importMatches[importMatches.length - 1];
    const insertAt = (lastImport.index || 0) + lastImport[0].length;
    next = `${next.slice(0, insertAt)}\n${MENU_IMPORT_MARKER}${next.slice(insertAt)}`;
  }

  if (!next.includes(MENU_ITEM_MARKER)) {
    const pattern = /children:\s*async\s*\(\)\s*=>\s*\[/;
    if (!pattern.test(next)) {
      return undefined;
    }
    next = next.replace(pattern, (match) => `${match}\n        ${MENU_ITEM_MARKER}`);
  }

  return next;
}

function buildMenuImportLines(target: MenuItemTarget, pascalName: string, page: string): string[] {
  const lines = [
    `import { $MI${target === 'trigger' || target === 'dashboard' ? ', AppManager' : ''} } from 'vuetify-extended';`,
    `import { create${pascalName}${capitalize(target)} } from '../pages/${page}';`,
  ];
  return lines;
}

function buildMenuItemBlock(answers: MenuItemAnswers, pascalName: string, itemMarker: string): string {
  const functionName = `create${pascalName}${capitalize(answers.target)}`;

  const body = answers.target === 'report'
    ? `$MI(
          {
            action: 'report',
            mode: ${serializeString(answers.mode)},
            text: ${serializeString(answers.text)},
            subText: ${serializeString(answers.subText)},
            icon: ${serializeString(answers.icon)},
            color: ${serializeString(answers.color)},
          },
          {
            report: async (_menuItem, mode) => ${functionName}(mode || ${serializeString(answers.mode)}),
          },
        ),`
    : answers.target === 'collection'
      ? `$MI(
          {
            action: 'collection',
            mode: ${serializeString(answers.mode)},
            text: ${serializeString(answers.text)},
            subText: ${serializeString(answers.subText)},
            icon: ${serializeString(answers.icon)},
            color: ${serializeString(answers.color)},
          },
          {
            collection: async (_menuItem, mode) => ${functionName}(mode || ${serializeString(answers.mode)}),
          },
        ),`
      : answers.target === 'dashboard'
        ? `$MI(
          {
            action: 'function',
            mode: ${serializeString(answers.mode)},
            text: ${serializeString(answers.text)},
            subText: ${serializeString(answers.subText)},
            icon: ${serializeString(answers.icon)},
            color: ${serializeString(answers.color)},
          },
          {
            callback: async () => {
              const dashboard = await ${functionName}();
              AppManager.showUI(dashboard);
            },
          },
        ),`
      : `$MI(
          {
            action: 'function',
            mode: ${serializeString(answers.mode)},
            text: ${serializeString(answers.text)},
            subText: ${serializeString(answers.subText)},
            icon: ${serializeString(answers.icon)},
            color: ${serializeString(answers.color)},
          },
          {
            callback: async () => {
              const trigger = await ${functionName}(${serializeString(answers.mode)});
              AppManager.showTrigger(trigger);
            },
          },
        ),`;

  return `        ${itemMarker}
        ${body}`;
}

function buildSubMenuFileSource(answers: SubMenuAnswers, pascalName: string): string {
  return `${GENERATED_MARKER} create sub-menu
import { $MN } from 'vuetify-extended';
// vuetify-ext:menu-imports

export function create${pascalName}Menu() {
  return $MN(
    {
      title: ${serializeString(answers.title)},
      cols: 12,
      width: 380,
    },
    {
      children: async () => [
        // vuetify-ext:menu-items
      ],
    },
  );
}
`;
}

function buildSubMenuItemBlock(answers: SubMenuAnswers, pascalName: string, itemMarker: string): string {
  return `        ${itemMarker}
        $MI(
          {
            action: 'menu',
            text: ${serializeString(answers.text)},
            subText: ${serializeString(answers.subText)},
            icon: ${serializeString(answers.icon)},
            color: ${serializeString(answers.color)},
          },
          {
            menu: async () => create${pascalName}Menu(),
          },
        ),`;
}

function resolveProjectScriptExtension(cwd: string): ScriptExt {
  const candidates = [
    path.join(cwd, 'src/main.ts'),
    path.join(cwd, 'src/menu/index.ts'),
    path.join(cwd, 'src/pages/home/index.ts'),
  ];
  if (candidates.some(fileExists)) {
    return '.ts';
  }

  const jsCandidates = [
    path.join(cwd, 'src/main.js'),
    path.join(cwd, 'src/menu/index.js'),
    path.join(cwd, 'src/pages/home/index.js'),
  ];
  if (jsCandidates.some(fileExists)) {
    return '.js';
  }

  return fileExists(path.join(cwd, 'tsconfig.json')) ? '.ts' : '.js';
}

function resolveMenuFile(cwd: string, ext: ScriptExt, override?: string): string | undefined {
  if (override) {
    return path.isAbsolute(override) ? override : path.join(cwd, override);
  }

  const candidates = [
    path.join(cwd, 'src/menu/index.ts'),
    path.join(cwd, 'src/menu/index.js'),
    path.join(cwd, `src/menu/index${ext}`),
  ];

  return candidates.find(fileExists);
}

function resolveParentMenuFile(cwd: string, ext: ScriptExt, parent?: string, override?: string): string | undefined {
  if (override) {
    return resolveMenuFile(cwd, ext, override);
  }

  if (!parent || parent === 'main') {
    return resolveMenuFile(cwd, ext);
  }

  const parentName = slugifyName(parent);
  const candidates = [
    path.join(cwd, 'src/menu', `${parentName}.ts`),
    path.join(cwd, 'src/menu', `${parentName}.js`),
    path.join(cwd, 'src/menu', `${parentName}${ext}`),
  ];

  return candidates.find(fileExists);
}

function resolveExistingPageScriptExtension(cwd: string, page: string): ScriptExt | undefined {
  const candidates: Array<{ file: string; ext: ScriptExt }> = [
    { file: path.join(cwd, 'src/pages', page, 'report.ts'), ext: '.ts' },
    { file: path.join(cwd, 'src/pages', page, 'report.js'), ext: '.js' },
    { file: path.join(cwd, 'src/pages', page, 'index.ts'), ext: '.ts' },
    { file: path.join(cwd, 'src/pages', page, 'index.js'), ext: '.js' },
  ];

  return candidates.find((candidate) => fileExists(candidate.file))?.ext;
}

function resolveFormStepPageContext(cwd: string, page: string, fallbackExt: ScriptExt) {
  const pageExt = resolveExistingPageScriptExtension(cwd, page) || fallbackExt;
  const reportFile = path.join(cwd, 'src/pages', page, `report${pageExt}`);
  const reportSource = fileExists(reportFile) ? fs.readFileSync(reportFile, 'utf8') : '';

  return {
    pageExt,
    reportFile,
    reportSource,
    currentForms: extractReportFormsCount(reportSource) || 1,
    reportTitle: extractReportTitle(reportSource),
  };
}

function extractReportFormsCount(source: string): number | undefined {
  const match = source.match(/forms:\s*(\d+)/);
  if (!match) return undefined;
  const parsed = Number(match[1]);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined;
}

function extractReportTitle(source: string): string | undefined {
  const match = source.match(/title:\s*['"`]([^'"`]+)['"`]/);
  return match?.[1];
}

function ensureReportFormMarkers(source: string, pascalName: string): string | undefined {
  if (source.includes(REPORT_IMPORT_MARKER) && source.includes(REPORT_RESOLVER_MARKER)) {
    return source;
  }

  let next = source;
  const baseImportPattern = new RegExp(
    `import\\s*\\{\\s*create${pascalName}Form\\s*\\}\\s*from\\s*['"]\\.\\/form['"];?`,
  );
  if (!next.includes(REPORT_IMPORT_MARKER)) {
    const baseImportMatch = next.match(baseImportPattern);
    if (!baseImportMatch) {
      return undefined;
    }
    next = next.replace(baseImportMatch[0], `${baseImportMatch[0]}\n${REPORT_IMPORT_MARKER}`);
  }

  if (!next.includes(REPORT_RESOLVER_MARKER)) {
    const exactSingleResolver = `form: async (_props, _context, _index) => create${pascalName}Form(mode),`;
    if (next.includes(exactSingleResolver)) {
      next = next.replace(
        exactSingleResolver,
        `form: async (_props, _context, index) => {\n        ${REPORT_RESOLVER_MARKER}\n        if (index === 0) return create${pascalName}Form(mode);\n        return undefined;\n      },`,
      );
      return next;
    }

    const singleResolverPattern = new RegExp(
      `form:\\s*async\\s*\\([^)]*\\)\\s*=>\\s*create${pascalName}Form\\(mode\\),`,
    );
    if (singleResolverPattern.test(next)) {
      next = next.replace(
        singleResolverPattern,
        `form: async (_props, _context, index) => {\n        ${REPORT_RESOLVER_MARKER}\n        if (index === 0) return create${pascalName}Form(mode);\n        return undefined;\n      },`,
      );
      return next;
    }

    if (next.includes('return undefined;')) {
      next = next.replace('return undefined;', `${REPORT_RESOLVER_MARKER}\n        return undefined;`);
      return next;
    }

    return undefined;
  }

  return next;
}

function patchReportForNewForm(
  source: string,
  input: { pascalName: string; step: number; nextFormsCount: number },
): string | undefined {
  const importLine = `import { ${formFunctionNameForStep(input.pascalName, input.step)} } from './${formImportStemForStep(input.step)}';`;
  const resolverLine = `if (index === ${input.step - 1}) return ${formFunctionNameForStep(input.pascalName, input.step)}(mode);`;

  let next = source.replace(/forms:\s*\d+/, `forms: ${input.nextFormsCount}`);

  if (!next.includes(REPORT_IMPORT_MARKER) || !next.includes(REPORT_RESOLVER_MARKER)) {
    return undefined;
  }

  if (!next.includes(importLine)) {
    next = next.replace(REPORT_IMPORT_MARKER, `${REPORT_IMPORT_MARKER}\n${importLine}`);
  }

  if (!next.includes(resolverLine)) {
    if (!next.includes('return undefined;')) {
      return undefined;
    }
    next = next.replace('return undefined;', `${resolverLine}\n        return undefined;`);
  }

  return next;
}

function patchLegacySingleFormReport(
  source: string,
  input: { pascalName: string; step: number; nextFormsCount: number },
): string | undefined {
  const exactSingleResolver = `form: async (_props, _context, _index) => create${input.pascalName}Form(mode),`;
  const singleResolverPattern = new RegExp(
    `form:\\s*async\\s*\\([^)]*\\)\\s*=>\\s*create${input.pascalName}Form\\(mode\\),`,
  );
  const baseImportPattern = new RegExp(
    `import\\s*\\{\\s*create${input.pascalName}Form\\s*\\}\\s*from\\s*['"]\\.\\/form['"];?`,
  );
  const baseImportMatch = source.match(baseImportPattern);
  if (!baseImportMatch) {
    return undefined;
  }

  const replacementResolver = `form: async (_props, _context, index) => {\n        ${REPORT_RESOLVER_MARKER}\n        if (index === 0) return create${input.pascalName}Form(mode);\n        if (index === ${input.step - 1}) return ${formFunctionNameForStep(input.pascalName, input.step)}(mode);\n        return undefined;\n      },`;

  let next = source.replace(baseImportMatch[0], `${baseImportMatch[0]}\n${REPORT_IMPORT_MARKER}\nimport { ${formFunctionNameForStep(input.pascalName, input.step)} } from './${formImportStemForStep(input.step)}';`);
  next = next.replace(/forms:\s*\d+/, `forms: ${input.nextFormsCount}`);

  if (next.includes(exactSingleResolver)) {
    return next.replace(exactSingleResolver, replacementResolver);
  }

  if (singleResolverPattern.test(next)) {
    return next.replace(singleResolverPattern, replacementResolver);
  }

  return undefined;
}

function appendExportLine(source: string, exportLine: string): string {
  const lines = source.trimEnd().split('\n').filter(Boolean);
  if (!lines.includes(exportLine)) {
    lines.push(exportLine);
  }
  return `${lines.join('\n')}\n`;
}

function verifyExpectedPageExport(file: string, exportName: string): boolean {
  if (!fileExists(file)) {
    return false;
  }

  const source = fs.readFileSync(file, 'utf8');
  return sourceIncludesNamedExport(source, exportName);
}

function sourceIncludesNamedExport(source: string, exportName: string): boolean {
  const escaped = escapeRegExp(exportName);
  const patterns = [
    new RegExp(`export\\s+function\\s+${escaped}\\s*\\(`),
    new RegExp(`export\\s+(?:const|let|var)\\s+${escaped}\\s*=`),
    new RegExp(`export\\s*\\{[^}]*\\b${escaped}\\b[^}]*\\}`),
  ];

  return patterns.some((pattern) => pattern.test(source));
}

async function promptText(
  rl: readline.Interface,
  label: string,
  defaultValue?: string,
  allowEmpty: boolean = false,
): Promise<string> {
  while (true) {
    const suffix = defaultValue ? ` [${defaultValue}]` : '';
    const value = (await ask(rl, `${label}${suffix}: `)).trim();
    if (value.length > 0) {
      return value;
    }

    if (defaultValue !== undefined) {
      return defaultValue;
    }

    if (allowEmpty) {
      return '';
    }
  }
}

async function promptBoolean(rl: readline.Interface, label: string, defaultValue: boolean): Promise<boolean> {
  while (true) {
    const suffix = defaultValue ? ' [Y/n]' : ' [y/N]';
    const value = (await ask(rl, `${label}${suffix}: `)).trim().toLowerCase();
    if (!value) {
      return defaultValue;
    }

    if (['y', 'yes', 'true', '1'].includes(value)) {
      return true;
    }

    if (['n', 'no', 'false', '0'].includes(value)) {
      return false;
    }
  }
}

async function promptChoice(
  rl: readline.Interface,
  label: string,
  choices: string[],
  defaultValue: string,
): Promise<string> {
  while (true) {
    const value = (await ask(rl, `${label} [${defaultValue}]: `)).trim().toLowerCase();
    const resolved = value || defaultValue;
    if (choices.includes(resolved)) {
      return resolved;
    }
  }
}

async function promptNumber(
  rl: readline.Interface,
  label: string,
  defaultValue: number,
  min: number,
): Promise<number> {
  while (true) {
    const value = (await ask(rl, `${label} [${defaultValue}]: `)).trim();
    if (!value) {
      return defaultValue;
    }

    const parsed = Number(value);
    if (Number.isInteger(parsed) && parsed >= min) {
      return parsed;
    }
  }
}

function ask(rl: readline.Interface, prompt: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => resolve(answer));
  });
}

function collectMissing(input: Record<string, any>, keys: string[]) {
  return keys.filter((key) => !input[key]);
}

function normalizeMode(value: string | undefined, fallback: ReportMode): ReportMode {
  const normalized = String(value || fallback).toLowerCase();
  if (normalized === 'create' || normalized === 'edit' || normalized === 'display') {
    return normalized;
  }
  return fallback;
}

function normalizePositiveInt(value: string | number | undefined, fallback: number): number {
  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback;
}

function parseOptionalBoolean(value: string | undefined): boolean | undefined {
  if (value === undefined) {
    return undefined;
  }

  const normalized = value.trim().toLowerCase();
  if (['true', '1', 'yes', 'y'].includes(normalized)) {
    return true;
  }

  if (['false', '0', 'no', 'n'].includes(normalized)) {
    return false;
  }

  return undefined;
}

function toPascalCase(value: string): string {
  return slugifyName(value)
    .split('-')
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('');
}

function formFunctionNameForStep(pascalName: string, step: number): string {
  return step <= 1 ? `create${pascalName}Form` : `create${pascalName}Form${step}`;
}

function formImportStemForStep(step: number): string {
  return step <= 1 ? 'form' : `form-${step}`;
}

function formFileNameForStep(step: number, ext: ScriptExt): string {
  return `${formImportStemForStep(step)}${ext}`;
}

function humanizeName(value: string): string {
  return slugifyName(value)
    .split('-')
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join(' ');
}

function slugifyName(value: string): string {
  const normalized = String(value || '')
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();

  return normalized || 'sample-page';
}

function sanitizeIdentifier(value: string): string {
  const identifier = slugifyName(value).replace(/-/g, '_').replace(/[^a-zA-Z0-9_]/g, '_');
  if (/^[0-9]/.test(identifier)) {
    return `item_${identifier}`;
  }
  return identifier || 'ITEM';
}

function serializeString(value: string | undefined): string {
  return JSON.stringify(value || '');
}

function serializeKey(key: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function flagName(key: string): string {
  return `--${key.replace(/[A-Z]/g, (char) => `-${char.toLowerCase()}`)}`;
}

function defaultMenuIcon(target: MenuItemTarget): string {
  if (target === 'dashboard') return 'mdi-view-dashboard-outline';
  if (target === 'collection') return 'mdi-view-list';
  if (target === 'trigger') return 'mdi-table-search';
  return 'mdi-file-document-outline';
}

function defaultMenuColor(target: MenuItemTarget): string {
  if (target === 'dashboard') return 'primary';
  if (target === 'collection') return 'deep-orange';
  if (target === 'trigger') return 'brown';
  return 'primary';
}

function defaultMenuMode(target: MenuItemTarget): ReportMode {
  return target === 'report' || target === 'dashboard' ? 'display' : 'edit';
}

function fileExists(file: string): boolean {
  return fs.existsSync(file);
}

function normalizeScriptExt(value: string): ScriptExt | undefined {
  if (value === '.ts' || value === '.js') {
    return value;
  }

  return undefined;
}

function buildRelativeImportSpecifier(fromFile: string, targetFile: string): string {
  const relative = path.relative(path.dirname(fromFile), targetFile).replace(/\\/g, '/');
  const withoutExt = relative.replace(/\.(ts|js)$/i, '');
  return withoutExt.startsWith('.') ? withoutExt : `./${withoutExt}`;
}

function relativeToCwd(cwd: string, absolutePath: string): string {
  return path.relative(cwd, absolutePath) || path.basename(absolutePath);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
