import fs from 'node:fs';
import path from 'node:path';
import * as readline from 'node:readline';
import { CreateCommandOptions } from './create-ui';

type ScriptExt = '.ts' | '.js';
type ReportMode = 'create' | 'edit' | 'display';
type PageTarget = 'report' | 'trigger' | 'collection' | 'dashboard';
type HeaderItemKind = 'title' | 'environment' | 'status' | 'action' | 'user';
type HeaderRegion = 'start' | 'center' | 'end';
type ThemeMode = 'light' | 'dark';

interface RouteAnswers {
  name: string;
  title: string;
  path: string;
  page: string;
  target: PageTarget;
  mode: ReportMode;
}

interface DialogFormAnswers {
  name: string;
  title: string;
  mode: ReportMode;
}

interface TriggerFieldAnswers {
  page: string;
  label: string;
  storage: string;
  type: string;
  cols: number;
}

interface TriggerActionAnswers {
  page: string;
  text: string;
  icon: string;
  color: string;
  variant: string;
  shortcut?: string;
}

interface ReportActionAnswers {
  page: string;
  text: string;
  icon: string;
  color: string;
  variant: string;
  shortcut?: string;
}

interface DashboardDataSourceAnswers {
  page: string;
  name: string;
}

interface AssetServiceAnswers {
  name: string;
  path: string;
}

interface AutocompleteSourceAnswers {
  name: string;
  servicePath: string;
  labelField: string;
  valueField: string;
}

interface HeaderItemAnswers {
  kind: HeaderItemKind;
  region: HeaderRegion;
  text: string;
  subtitle?: string;
  overline?: string;
  icon: string;
  color: string;
}

interface BootstrapThemeAnswers {
  mode: ThemeMode;
}

interface FileWrite {
  file: string;
  content: string;
}

const GENERATED_MARKER = '// Generated by vuetify-ext';
const ROUTES_IMPORT_MARKER = '// vuetify-ext:route-imports';
const ROUTES_ITEM_MARKER = '// vuetify-ext:routes';
const TRIGGER_SEARCH_MARKER = '// vuetify-ext:trigger-search-fields';
const TRIGGER_ACTION_MARKER = '// vuetify-ext:trigger-side-actions';
const REPORT_ACTION_MARKER = '// vuetify-ext:report-side-actions';
const HEADER_IMPORT_MARKER = '// vuetify-ext:header-imports';
const HEADER_START_MARKER = '// vuetify-ext:header-start';
const HEADER_CENTER_MARKER = '// vuetify-ext:header-center';
const HEADER_END_MARKER = '// vuetify-ext:header-end';

export async function runCreateRouteCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveRouteAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveExistingPageScriptExtension(options.cwd, answers.page) || resolveProjectScriptExtension(options.cwd);
  const pageIndexFile = path.join(options.cwd, 'src/pages', answers.page, `index${ext}`);
  const factoryName = `create${toPascalCase(answers.page)}${capitalize(answers.target)}`;
  if (!verifyExpectedPageExport(pageIndexFile, factoryName)) {
    options.stderr.write(
      `[vuetify-ext] ${relativeToCwd(options.cwd, pageIndexFile)} is missing ${factoryName}.\n`,
    );
    return 1;
  }

  const routesDir = path.join(options.cwd, 'src/routes');
  const routeFile = path.join(routesDir, `${answers.name}${ext}`);
  const routesIndexFile = path.join(routesDir, `index${ext}`);
  const prepare = prepareWrites(options, [
    { file: routeFile, content: buildRouteFileSource(answers) },
  ]);
  if (prepare === 'error') {
    return 1;
  }

  const currentIndexSource = fileExists(routesIndexFile)
    ? fs.readFileSync(routesIndexFile, 'utf8')
    : buildRoutesIndexFileSource(ext);
  const nextIndexSource = patchRoutesIndexSource(currentIndexSource, answers);
  if (!nextIndexSource) {
    options.stderr.write(
      `[vuetify-ext] Could not patch ${relativeToCwd(options.cwd, routesIndexFile)} automatically.\n`,
    );
    return 1;
  }

  if (prepare === 'dry-run') {
    options.stdout.write(`- ${relativeToCwd(options.cwd, routesIndexFile)}\n`);
    return 0;
  }

  writeFiles([{ file: routeFile, content: buildRouteFileSource(answers) }]);
  fs.mkdirSync(path.dirname(routesIndexFile), { recursive: true });
  fs.writeFileSync(routesIndexFile, nextIndexSource, 'utf8');
  writeSuccess(options, 'Route scaffolding created successfully', [routeFile, routesIndexFile]);
  return 0;
}

export async function runCreateDialogFormCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveDialogFormAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveProjectScriptExtension(options.cwd);
  const dialogsDir = path.join(options.cwd, 'src/dialogs');
  const file = path.join(dialogsDir, `${answers.name}${ext}`);
  const indexFile = path.join(dialogsDir, `index${ext}`);
  const writes = [{ file, content: buildDialogFormFileSource(ext, answers) }];
  const prepare = prepareWrites(options, writes);
  if (prepare === 'error') {
    return 1;
  }
  if (prepare === 'dry-run') {
    options.stdout.write(`- ${relativeToCwd(options.cwd, indexFile)}\n`);
    return 0;
  }

  writeFiles(writes);
  ensureSimpleExport(indexFile, `export { create${toPascalCase(answers.name)}DialogForm } from './${answers.name}';`);
  writeSuccess(options, 'Dialog form scaffolding created successfully', [file, indexFile]);
  return 0;
}

export async function runCreateTriggerFieldCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveTriggerFieldAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveExistingPageScriptExtension(options.cwd, answers.page) || resolveProjectScriptExtension(options.cwd);
  const triggerFile = path.join(options.cwd, 'src/pages', answers.page, `trigger${ext}`);
  if (!fileExists(triggerFile)) {
    options.stderr.write(`[vuetify-ext] Trigger file not found: ${relativeToCwd(options.cwd, triggerFile)}\n`);
    return 1;
  }

  const fieldMarker = `// vuetify-ext:trigger-field:${answers.storage}`;
  let source = fs.readFileSync(triggerFile, 'utf8');
  if (source.includes(fieldMarker)) {
    writeSuccess(options, 'Trigger field already present', [triggerFile]);
    return 0;
  }

  source = ensureTriggerSearchMarkers(source) || '';
  if (!source || !source.includes(TRIGGER_SEARCH_MARKER)) {
    options.stderr.write(`[vuetify-ext] Could not normalize trigger search fields in ${relativeToCwd(options.cwd, triggerFile)}.\n`);
    return 1;
  }

  const block = buildTriggerFieldBlock(answers, fieldMarker);
  const next = source.replace(TRIGGER_SEARCH_MARKER, `${TRIGGER_SEARCH_MARKER}\n${block}`);

  if (options.dryRun) {
    options.stdout.write(`[vuetify-ext] Dry run only. The following file would be updated:\n- ${relativeToCwd(options.cwd, triggerFile)}\n`);
    return 0;
  }

  fs.writeFileSync(triggerFile, next, 'utf8');
  writeSuccess(options, 'Trigger field added successfully', [triggerFile]);
  return 0;
}

export async function runCreateTriggerActionCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveTriggerActionAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveExistingPageScriptExtension(options.cwd, answers.page) || resolveProjectScriptExtension(options.cwd);
  const triggerFile = path.join(options.cwd, 'src/pages', answers.page, `trigger${ext}`);
  if (!fileExists(triggerFile)) {
    options.stderr.write(`[vuetify-ext] Trigger file not found: ${relativeToCwd(options.cwd, triggerFile)}\n`);
    return 1;
  }

  const actionSlug = slugifyName(answers.text);
  const actionMarker = `// vuetify-ext:trigger-action:${actionSlug}`;
  let source = fs.readFileSync(triggerFile, 'utf8');
  if (source.includes(actionMarker)) {
    writeSuccess(options, 'Trigger action already present', [triggerFile]);
    return 0;
  }

  source = ensureTriggerActionMarkers(source) || '';
  if (!source || !source.includes(TRIGGER_ACTION_MARKER)) {
    options.stderr.write(`[vuetify-ext] Could not normalize trigger side actions in ${relativeToCwd(options.cwd, triggerFile)}.\n`);
    return 1;
  }

  const block = buildTriggerActionBlock(answers, actionMarker);
  const next = source.replace(TRIGGER_ACTION_MARKER, `${TRIGGER_ACTION_MARKER}\n${block}`);

  if (options.dryRun) {
    options.stdout.write(`[vuetify-ext] Dry run only. The following file would be updated:\n- ${relativeToCwd(options.cwd, triggerFile)}\n`);
    return 0;
  }

  fs.writeFileSync(triggerFile, next, 'utf8');
  writeSuccess(options, 'Trigger action added successfully', [triggerFile]);
  return 0;
}

export async function runCreateReportActionCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveReportActionAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveExistingPageScriptExtension(options.cwd, answers.page) || resolveProjectScriptExtension(options.cwd);
  const reportFile = path.join(options.cwd, 'src/pages', answers.page, `report${ext}`);
  if (!fileExists(reportFile)) {
    options.stderr.write(`[vuetify-ext] Report file not found: ${relativeToCwd(options.cwd, reportFile)}\n`);
    return 1;
  }

  const actionSlug = slugifyName(answers.text);
  const actionMarker = `// vuetify-ext:report-action:${actionSlug}`;
  let source = fs.readFileSync(reportFile, 'utf8');
  if (source.includes(actionMarker)) {
    writeSuccess(options, 'Report action already present', [reportFile]);
    return 0;
  }

  source = ensureReportActionMarkers(source) || '';
  if (!source || !source.includes(REPORT_ACTION_MARKER)) {
    options.stderr.write(`[vuetify-ext] Could not normalize report side actions in ${relativeToCwd(options.cwd, reportFile)}.\n`);
    return 1;
  }

  const block = buildReportActionBlock(answers, actionMarker);
  const next = source.replace(REPORT_ACTION_MARKER, `${REPORT_ACTION_MARKER}\n${block}`);

  if (options.dryRun) {
    options.stdout.write(`[vuetify-ext] Dry run only. The following file would be updated:\n- ${relativeToCwd(options.cwd, reportFile)}\n`);
    return 0;
  }

  fs.writeFileSync(reportFile, next, 'utf8');
  writeSuccess(options, 'Report action added successfully', [reportFile]);
  return 0;
}

export async function runCreateDashboardDataSourceCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveDashboardDataSourceAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveExistingPageScriptExtension(options.cwd, answers.page) || resolveProjectScriptExtension(options.cwd);
  const pageDir = path.join(options.cwd, 'src/pages', answers.page);
  const file = path.join(pageDir, `${answers.name}${ext}`);
  const indexFile = path.join(pageDir, `index${ext}`);
  const writes = [{ file, content: buildDashboardDataSourceFileSource(ext, answers) }];
  const prepare = prepareWrites(options, writes);
  if (prepare === 'error') {
    return 1;
  }
  if (prepare === 'dry-run') {
    options.stdout.write(`- ${relativeToCwd(options.cwd, indexFile)}\n`);
    return 0;
  }

  writeFiles(writes);
  ensureSimpleExport(indexFile, `export * from './${answers.name}';`);
  writeSuccess(options, 'Dashboard data source created successfully', [file, indexFile]);
  return 0;
}

export async function runCreateAssetServiceCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveAssetServiceAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveProjectScriptExtension(options.cwd);
  const apiDir = path.join(options.cwd, 'src/api');
  const file = path.join(apiDir, `${answers.name}${ext}`);
  const indexFile = path.join(apiDir, `index${ext}`);
  const writes = [{ file, content: buildAssetServiceFileSource(ext, answers) }];
  const prepare = prepareWrites(options, writes);
  if (prepare === 'error') {
    return 1;
  }
  if (prepare === 'dry-run') {
    options.stdout.write(`- ${relativeToCwd(options.cwd, indexFile)}\n`);
    return 0;
  }

  writeFiles(writes);
  ensureSimpleExport(indexFile, `export * from './${answers.name}';`);
  writeSuccess(options, 'Asset service created successfully', [file, indexFile]);
  return 0;
}

export async function runCreateAutocompleteSourceCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveAutocompleteSourceAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveProjectScriptExtension(options.cwd);
  const apiDir = path.join(options.cwd, 'src/api');
  const file = path.join(apiDir, `${answers.name}${ext}`);
  const indexFile = path.join(apiDir, `index${ext}`);
  const writes = [{ file, content: buildAutocompleteSourceFileSource(ext, answers) }];
  const prepare = prepareWrites(options, writes);
  if (prepare === 'error') {
    return 1;
  }
  if (prepare === 'dry-run') {
    options.stdout.write(`- ${relativeToCwd(options.cwd, indexFile)}\n`);
    return 0;
  }

  writeFiles(writes);
  ensureSimpleExport(indexFile, `export * from './${answers.name}';`);
  writeSuccess(options, 'Autocomplete source created successfully', [file, indexFile]);
  return 0;
}

export async function runCreateHeaderItemCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveHeaderItemAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveProjectScriptExtension(options.cwd);
  const headerFile = findExistingFile(options.cwd, ['src/bootstrap/header.ts', 'src/bootstrap/header.js']) || path.join(options.cwd, 'src/bootstrap', `header${ext}`);
  if (!fileExists(headerFile)) {
    options.stderr.write('[vuetify-ext] Bootstrap header file not found. Run "vuetify-ext bootstrap app" first.\n');
    return 1;
  }

  const itemMarker = `// vuetify-ext:header-item:${answers.region}:${answers.kind}:${slugifyName(answers.text)}`;
  let source = fs.readFileSync(headerFile, 'utf8');
  if (source.includes(itemMarker)) {
    writeSuccess(options, 'Header item already present', [headerFile]);
    return 0;
  }

  source = ensureHeaderMarkers(source) || '';
  if (!source) {
    options.stderr.write(`[vuetify-ext] Could not normalize header regions in ${relativeToCwd(options.cwd, headerFile)}.\n`);
    return 1;
  }

  source = ensureVuetifyExtendedImport(source, ['$ATB', '$ENV', '$SIA', '$STB', '$USR']);
  if (answers.kind === 'action') {
    source = ensureImportLine(source, `import { Dialogs } from 'vuetify-extended';`);
  }

  const regionMarker = answers.region === 'start' ? HEADER_START_MARKER : answers.region === 'center' ? HEADER_CENTER_MARKER : HEADER_END_MARKER;
  const next = source.replace(regionMarker, `${regionMarker}\n${buildHeaderItemBlock(answers, itemMarker)}`);

  if (options.dryRun) {
    options.stdout.write(`[vuetify-ext] Dry run only. The following file would be updated:\n- ${relativeToCwd(options.cwd, headerFile)}\n`);
    return 0;
  }

  fs.writeFileSync(headerFile, next, 'utf8');
  writeSuccess(options, 'Header item added successfully', [headerFile]);
  return 0;
}

export async function runBootstrapThemeCommand(options: CreateCommandOptions): Promise<number> {
  const answers = await resolveBootstrapThemeAnswers(options);
  if (!answers) {
    return 1;
  }

  const ext = resolveProjectScriptExtension(options.cwd);
  const mainFile = findExistingFile(options.cwd, ['src/main.ts', 'src/main.js']);
  if (!mainFile) {
    options.stderr.write('[vuetify-ext] Could not locate src/main.ts or src/main.js.\n');
    return 1;
  }

  const themeFile = path.join(options.cwd, 'src/bootstrap', `theme${ext}`);
  const writes = [{ file: themeFile, content: buildBootstrapThemeFileSource(ext, answers) }];
  const prepare = prepareWrites(options, writes);
  if (prepare === 'error') {
    return 1;
  }

  const currentMainSource = fs.readFileSync(mainFile, 'utf8');
  const nextMainSource = patchMainForThemeBootstrap(currentMainSource, mainFile);
  if (!nextMainSource) {
    options.stderr.write(`[vuetify-ext] Could not patch ${relativeToCwd(options.cwd, mainFile)} automatically.\n`);
    return 1;
  }

  if (prepare === 'dry-run') {
    options.stdout.write(`- ${relativeToCwd(options.cwd, mainFile)}\n`);
    return 0;
  }

  writeFiles(writes);
  fs.writeFileSync(mainFile, nextMainSource, 'utf8');
  writeSuccess(options, 'Theme bootstrap created successfully', [themeFile, mainFile]);
  return 0;
}

async function resolveRouteAnswers(options: CreateCommandOptions): Promise<RouteAnswers | undefined> {
  const values = options.values || {};
  const input = {
    name: values.name || options.positionals?.[0],
    title: values.title,
    path: values.path,
    page: values.page,
    target: values.target as PageTarget | undefined,
    mode: values.mode as ReportMode | undefined,
  };

  if (!options.interactive) {
    if (!input.name || !input.page) {
      options.stderr.write('[vuetify-ext] Missing required flags for create route:\n- --name\n- --page\n');
      return undefined;
    }
    const target = input.target || 'report';
    return {
      name: slugifyName(input.name),
      title: input.title || humanizeName(input.name),
      path: input.path || `/${slugifyName(input.name)}`,
      page: slugifyName(input.page),
      target,
      mode: normalizeMode(input.mode, defaultModeForTarget(target)),
    };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const name = slugifyName(await promptText(rl, 'Route name/file', input.name || 'workspace-home'));
    const page = slugifyName(await promptText(rl, 'Page folder', input.page || name));
    const target = await promptChoice(rl, 'Target (report/trigger/collection/dashboard)', ['report', 'trigger', 'collection', 'dashboard'], input.target || 'report') as PageTarget;
    const title = await promptText(rl, 'Route title', input.title || humanizeName(name));
    const routePath = await promptText(rl, 'Route path', input.path || `/${name}`);
    const mode = await promptChoice(rl, 'Default mode (create/edit/display)', ['create', 'edit', 'display'], input.mode || defaultModeForTarget(target)) as ReportMode;
    return { name, title, path: routePath, page, target, mode };
  } finally {
    rl.close();
  }
}

async function resolveDialogFormAnswers(options: CreateCommandOptions): Promise<DialogFormAnswers | undefined> {
  const values = options.values || {};
  const input = {
    name: values.name || options.positionals?.[0],
    title: values.title,
    mode: values.mode as ReportMode | undefined,
  };

  if (!options.interactive) {
    if (!input.name) {
      options.stderr.write('[vuetify-ext] Missing required flags for create dialog-form:\n- --name\n');
      return undefined;
    }
    return {
      name: slugifyName(input.name),
      title: input.title || humanizeName(input.name),
      mode: normalizeMode(input.mode, 'create'),
    };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const name = slugifyName(await promptText(rl, 'Dialog form name/file', input.name || 'quick-edit'));
    const title = await promptText(rl, 'Dialog title', input.title || humanizeName(name));
    const mode = await promptChoice(rl, 'Default mode (create/edit/display)', ['create', 'edit', 'display'], input.mode || 'create') as ReportMode;
    return { name, title, mode };
  } finally {
    rl.close();
  }
}

async function resolveTriggerFieldAnswers(options: CreateCommandOptions): Promise<TriggerFieldAnswers | undefined> {
  const values = options.values || {};
  const input = {
    page: values.page || options.positionals?.[0],
    label: values.label,
    storage: values.storage,
    type: values.type || 'text',
    cols: normalizePositiveInt(values.cols, 12),
  };

  if (!options.interactive) {
    if (!input.page || !input.label || !input.storage) {
      options.stderr.write('[vuetify-ext] Missing required flags for create trigger-field:\n- --page\n- --label\n- --storage\n');
      return undefined;
    }
    return {
      page: slugifyName(input.page),
      label: input.label,
      storage: input.storage,
      type: input.type,
      cols: input.cols,
    };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const page = slugifyName(await promptText(rl, 'Trigger page folder', input.page || 'sample-trigger'));
    const label = await promptText(rl, 'Filter label', input.label || 'Status');
    const storage = await promptText(rl, 'Filter storage key', input.storage || slugifyName(label));
    const type = await promptText(rl, 'Field type', input.type || 'text');
    const cols = await promptNumber(rl, 'Grid columns', input.cols, 1);
    return { page, label, storage, type, cols };
  } finally {
    rl.close();
  }
}

async function resolveTriggerActionAnswers(options: CreateCommandOptions): Promise<TriggerActionAnswers | undefined> {
  return resolveActionAnswers(options, 'create trigger-action', 'sample-trigger', 'Bulk Approve');
}

async function resolveReportActionAnswers(options: CreateCommandOptions): Promise<ReportActionAnswers | undefined> {
  return resolveActionAnswers(options, 'create report-action', 'sample-report', 'Summary');
}

async function resolveDashboardDataSourceAnswers(options: CreateCommandOptions): Promise<DashboardDataSourceAnswers | undefined> {
  const values = options.values || {};
  const input = {
    page: values.page || options.positionals?.[0],
    name: values.name || values.file,
  };

  if (!options.interactive) {
    if (!input.page) {
      options.stderr.write('[vuetify-ext] Missing required flags for create dashboard-data-source:\n- --page\n');
      return undefined;
    }
    return {
      page: slugifyName(input.page),
      name: slugifyName(input.name || 'dashboard-data'),
    };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const page = slugifyName(await promptText(rl, 'Dashboard page folder', input.page || 'operations-dashboard'));
    const name = slugifyName(await promptText(rl, 'Data source file name', input.name || 'dashboard-data'));
    return { page, name };
  } finally {
    rl.close();
  }
}

async function resolveAssetServiceAnswers(options: CreateCommandOptions): Promise<AssetServiceAnswers | undefined> {
  const values = options.values || {};
  const input = {
    name: values.name || options.positionals?.[0],
    path: values.path || values['service-path'],
  };

  if (!options.interactive) {
    return validateSimpleServiceAnswers(input, options.stderr, 'create asset-service');
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const name = slugifyName(await promptText(rl, 'Asset service file name', input.name || 'assets'));
    const servicePath = await promptText(rl, 'Asset service path', input.path || 'assets');
    return { name, path: servicePath };
  } finally {
    rl.close();
  }
}

async function resolveAutocompleteSourceAnswers(options: CreateCommandOptions): Promise<AutocompleteSourceAnswers | undefined> {
  const values = options.values || {};
  const input = {
    name: values.name || options.positionals?.[0],
    servicePath: values.path || values['service-path'],
    labelField: values['label-field'],
    valueField: values['value-field'],
  };

  if (!options.interactive) {
    if (!input.name) {
      options.stderr.write('[vuetify-ext] Missing required flags for create autocomplete-source:\n- --name\n');
      return undefined;
    }
    return {
      name: slugifyName(input.name),
      servicePath: input.servicePath || slugifyName(input.name.replace(/-autocomplete$/i, '')),
      labelField: input.labelField || 'name',
      valueField: input.valueField || '_id',
    };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const name = slugifyName(await promptText(rl, 'Autocomplete source file name', input.name || 'people-autocomplete'));
    const servicePath = await promptText(rl, 'Service path', input.servicePath || name.replace(/-autocomplete$/i, ''));
    const labelField = await promptText(rl, 'Label field', input.labelField || 'name');
    const valueField = await promptText(rl, 'Value field', input.valueField || '_id');
    return { name, servicePath, labelField, valueField };
  } finally {
    rl.close();
  }
}

async function resolveHeaderItemAnswers(options: CreateCommandOptions): Promise<HeaderItemAnswers | undefined> {
  const values = options.values || {};
  const input = {
    kind: values.kind as HeaderItemKind | undefined,
    region: values.region as HeaderRegion | undefined,
    text: values.text || values.title,
    subtitle: values.subtitle,
    overline: values.overline,
    icon: values.icon,
    color: values.color,
  };

  if (!options.interactive) {
    if (!input.kind || !input.region || !input.text) {
      options.stderr.write('[vuetify-ext] Missing required flags for create header-item:\n- --kind\n- --region\n- --text\n');
      return undefined;
    }
    return {
      kind: input.kind,
      region: input.region,
      text: input.text,
      subtitle: input.subtitle,
      overline: input.overline,
      icon: input.icon || defaultHeaderIcon(input.kind),
      color: input.color || defaultHeaderColor(input.kind),
    };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const kind = await promptChoice(rl, 'Header item kind (title/environment/status/action/user)', ['title', 'environment', 'status', 'action', 'user'], input.kind || 'status') as HeaderItemKind;
    const region = await promptChoice(rl, 'Header region (start/center/end)', ['start', 'center', 'end'], input.region || 'end') as HeaderRegion;
    const text = await promptText(rl, 'Primary text/title', input.text || defaultHeaderText(kind));
    const subtitle = await promptText(rl, 'Subtitle (optional)', input.subtitle || '', true);
    const overline = await promptText(rl, 'Overline (optional)', input.overline || '', true);
    const icon = await promptText(rl, 'Icon', input.icon || defaultHeaderIcon(kind));
    const color = await promptText(rl, 'Color', input.color || defaultHeaderColor(kind));
    return {
      kind,
      region,
      text,
      subtitle: subtitle || undefined,
      overline: overline || undefined,
      icon,
      color,
    };
  } finally {
    rl.close();
  }
}

async function resolveBootstrapThemeAnswers(options: CreateCommandOptions): Promise<BootstrapThemeAnswers | undefined> {
  const values = options.values || {};
  const input = {
    mode: values.mode as ThemeMode | undefined,
  };

  if (!options.interactive) {
    return {
      mode: input.mode || 'light',
    };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const mode = await promptChoice(rl, 'Default theme mode (light/dark)', ['light', 'dark'], input.mode || 'light') as ThemeMode;
    return { mode };
  } finally {
    rl.close();
  }
}

async function resolveActionAnswers(
  options: CreateCommandOptions,
  commandName: string,
  defaultPage: string,
  defaultText: string,
): Promise<TriggerActionAnswers | ReportActionAnswers | undefined> {
  const values = options.values || {};
  const input = {
    page: values.page || options.positionals?.[0],
    text: values.text,
    icon: values.icon,
    color: values.color,
    variant: values.variant,
    shortcut: values.shortcut,
  };

  if (!options.interactive) {
    if (!input.page || !input.text) {
      options.stderr.write(`[vuetify-ext] Missing required flags for ${commandName}:\n- --page\n- --text\n`);
      return undefined;
    }
    return {
      page: slugifyName(input.page),
      text: input.text,
      icon: input.icon || 'mdi-lightning-bolt-outline',
      color: input.color || 'primary',
      variant: input.variant || 'outlined',
      shortcut: input.shortcut,
    };
  }

  const rl = readline.createInterface({ input: options.stdin, output: options.stdout as NodeJS.WritableStream });
  try {
    const page = slugifyName(await promptText(rl, 'Page folder', input.page || defaultPage));
    const text = await promptText(rl, 'Action text', input.text || defaultText);
    const icon = await promptText(rl, 'Icon', input.icon || 'mdi-lightning-bolt-outline');
    const color = await promptText(rl, 'Color', input.color || 'primary');
    const variant = await promptText(rl, 'Variant', input.variant || 'outlined');
    const shortcut = await promptText(rl, 'Shortcut (optional)', input.shortcut || '', true);
    return { page, text, icon, color, variant, shortcut: shortcut || undefined };
  } finally {
    rl.close();
  }
}

function validateSimpleServiceAnswers(
  input: { name?: string; path?: string },
  stderr: Pick<typeof process.stderr, 'write'>,
  commandName: string,
): AssetServiceAnswers | undefined {
  if (!input.name) {
    stderr.write(`[vuetify-ext] Missing required flags for ${commandName}:\n- --name\n`);
    return undefined;
  }
  return {
    name: slugifyName(input.name),
    path: input.path || slugifyName(input.name),
  };
}

function buildRouteFileSource(answers: RouteAnswers) {
  const pascalPage = toPascalCase(answers.page);
  const factoryName = `create${pascalPage}${capitalize(answers.target)}`;
  const routeIdentifier = routeIdentifierForName(answers.name);
  const targetVar = answers.target === 'dashboard' ? 'dashboard' : answers.target;
  const navigationKey = answers.target === 'dashboard'
    ? `routes.${answers.name}.ui`
    : `routes.${answers.name}.${answers.target}.${answers.mode}`;
  const openBody = answers.target === 'report'
    ? `const report = ${factoryName}(${serializeString(answers.mode)});
    AppManager.showReport(report, {
      mode: ${serializeString(answers.mode)},
      navigation: {
        key: ${serializeString(navigationKey)},
        persist: false,
      },
    });`
    : answers.target === 'trigger'
      ? `const trigger = ${factoryName}(${serializeString(answers.mode)});
    AppManager.showTrigger(trigger, {
      mode: ${serializeString(answers.mode)},
      navigation: {
        key: ${serializeString(navigationKey)},
        persist: false,
      },
    });`
      : answers.target === 'collection'
        ? `const collection = ${factoryName}(${serializeString(answers.mode)});
    AppManager.showCollection(collection, {
      mode: ${serializeString(answers.mode)},
      navigation: {
        key: ${serializeString(navigationKey)},
        persist: false,
      },
    });`
        : `const dashboard = ${factoryName}();
    AppManager.showUI(dashboard, {
      navigation: {
        key: ${serializeString(navigationKey)},
        persist: false,
      },
    });`;

  return `${GENERATED_MARKER} create route
import { AppManager } from 'vuetify-extended';
import { ${factoryName} } from '../pages/${answers.page}';

export const ${routeIdentifier} = {
  name: ${serializeString(answers.name)},
  title: ${serializeString(answers.title)},
  path: ${serializeString(answers.path)},
  target: ${serializeString(targetVar)},
  async open() {
    ${openBody}
  },
};
`;
}

function buildRoutesIndexFileSource(ext: ScriptExt) {
  const typeLine = ext === '.ts'
    ? `export interface AppRouteEntry {
  name: string;
  title: string;
  path: string;
  target: 'report' | 'trigger' | 'collection' | 'dashboard';
  open: () => Promise<void>;
}

`
    : '';

  return `${GENERATED_MARKER} routes index
${ROUTES_IMPORT_MARKER}

${typeLine}export const appRoutes${ext === '.ts' ? ': AppRouteEntry[]' : ''} = [
  ${ROUTES_ITEM_MARKER}
];
`;
}

function patchRoutesIndexSource(source: string, answers: RouteAnswers) {
  const routeIdentifier = routeIdentifierForName(answers.name);
  const importLine = `import { ${routeIdentifier} } from './${answers.name}';`;
  const itemLine = `  ${routeIdentifier},`;
  let next = ensureRouteIndexMarkers(source);
  if (!next) {
    return undefined;
  }
  if (!next.includes(importLine)) {
    next = next.replace(ROUTES_IMPORT_MARKER, `${ROUTES_IMPORT_MARKER}\n${importLine}`);
  }
  if (!next.includes(itemLine)) {
    next = next.replace(ROUTES_ITEM_MARKER, `${ROUTES_ITEM_MARKER}\n${itemLine}`);
  }
  return next;
}

function ensureRouteIndexMarkers(source: string) {
  let next = source;
  if (!next.includes(ROUTES_IMPORT_MARKER)) {
    const importMatches = Array.from(next.matchAll(/^import .*$/gm));
    if (importMatches.length > 0) {
      const lastImport = importMatches[importMatches.length - 1];
      const insertAt = (lastImport.index || 0) + lastImport[0].length;
      next = `${next.slice(0, insertAt)}\n${ROUTES_IMPORT_MARKER}${next.slice(insertAt)}`;
    } else {
      next = `${ROUTES_IMPORT_MARKER}\n\n${next}`;
    }
  }

  if (!next.includes(ROUTES_ITEM_MARKER)) {
    const arrayPattern = /export const appRoutes(?:\s*:\s*AppRouteEntry\[\])?\s*=\s*\[/;
    if (!arrayPattern.test(next)) {
      return undefined;
    }
    next = next.replace(arrayPattern, (match) => `${match}\n  ${ROUTES_ITEM_MARKER}`);
  }

  return next;
}

function buildDialogFormFileSource(ext: ScriptExt, answers: DialogFormAnswers) {
  const typeImport = ext === '.ts' ? ', type ReportMode' : '';
  const modeArg = ext === '.ts' ? `mode: ReportMode = ${serializeString(answers.mode)}` : `mode = ${serializeString(answers.mode)}`;
  const pascalName = toPascalCase(answers.name);
  const textBase = dialogTextKey(answers.name);

  return `${GENERATED_MARKER} create dialog form
import { $DF, $FD, $FM, $PT${typeImport} } from 'vuetify-extended';

export function create${pascalName}DialogForm(${modeArg}) {
  return $DF(
    {
      ref: ${serializeString(answers.name)},
      closeOnSave: true,
      mode,
    },
    {
      form: async () =>
        $FM(
          {
            title: ${serializeUITextDescriptor(`${textBase}.title`, answers.title)},
            mode,
            width: 760,
          },
          {
            children: () => [
              $PT(
                { cols: 12, dense: true },
                {
                  children: () => [
                    $FD({
                      label: ${serializeUITextDescriptor(`${textBase}.fields.title.label`, 'Title')},
                      storage: 'title',
                      cols: 6,
                      required: true,
                    }),
                    $FD({
                      label: ${serializeUITextDescriptor(`${textBase}.fields.owner.label`, 'Owner')},
                      storage: 'owner',
                      cols: 6,
                    }),
                    $FD({
                      label: ${serializeUITextDescriptor(`${textBase}.fields.summary.label`, 'Summary')},
                      storage: 'summary',
                      type: 'textarea',
                      cols: 12,
                    }),
                  ],
                },
              ),
            ],
          },
        ),
    },
  );
}
`;
}

function buildTriggerFieldBlock(answers: TriggerFieldAnswers, fieldMarker: string) {
  const lines = [
    `          ${fieldMarker}`,
    `          $FD({`,
    `            label: ${serializeUITextDescriptor(pageTextKey(answers.page, 'trigger', 'fields', answers.storage, 'label'), answers.label)},`,
    `            storage: ${serializeString(answers.storage)},`,
  ];
  if (answers.type !== 'text') {
    lines.push(`            type: ${serializeString(answers.type)},`);
  }
  lines.push(`            cols: ${answers.cols},`);
  lines.push(`          }),`);
  return lines.join('\n');
}

function buildTriggerActionBlock(answers: TriggerActionAnswers, marker: string) {
  const actionSlug = slugifyName(answers.text);
  const keyBase = pageTextKey(answers.page, 'trigger', 'actions', actionSlug);
  return `        ${marker}
        $BN(
          {
            text: ${serializeUITextDescriptor(`${keyBase}.text`, answers.text)},
            icon: ${serializeString(answers.icon)},
            color: ${serializeString(answers.color)},
            variant: ${serializeString(answers.variant)},
${answers.shortcut ? `            shortcut: ${serializeString(answers.shortcut)},\n` : ''}          },
          {
            onClicked: () => {
              trigger.emit('side-action', ${serializeString(actionSlug)});
              Dialogs.$success(${serializeUITextDescriptor(`${keyBase}.success`, `${answers.text} clicked.`)});
            },
          },
        ),`;
}

function buildReportActionBlock(answers: ReportActionAnswers, marker: string) {
  const actionSlug = slugifyName(answers.text);
  const keyBase = pageTextKey(answers.page, 'report', 'actions', actionSlug);
  return `        ${marker}
        $BN(
          {
            text: ${serializeUITextDescriptor(`${keyBase}.text`, answers.text)},
            icon: ${serializeString(answers.icon)},
            color: ${serializeString(answers.color)},
            variant: ${serializeString(answers.variant)},
${answers.shortcut ? `            shortcut: ${serializeString(answers.shortcut)},\n` : ''}          },
          {
            onClicked: () => {
              report.emit('side-action', ${serializeString(actionSlug)});
              Dialogs.$success(${serializeUITextDescriptor(`${keyBase}.success`, `${answers.text} clicked.`)});
            },
          },
        ),`;
}

function buildDashboardDataSourceFileSource(ext: ScriptExt, answers: DashboardDataSourceAnswers) {
  const pascalName = toPascalCase(answers.page);
  const interfaceType = `${pascalName}DashboardSnapshot`;
  const typed = ext === '.ts';

  return `${GENERATED_MARKER} create dashboard data source
${typed ? `export interface ${interfaceType} {
  generatedAt: string;
  metrics: Array<{ title: string; value: string | number; caption?: string; icon?: string }>;
  alerts: Array<{ severity: string; title: string; message: string }>;
}

` : ''}export async function load${pascalName}DashboardSnapshot()${typed ? `: Promise<${interfaceType}>` : ''} {
  return {
    generatedAt: new Date().toISOString(),
    metrics: [
      { title: 'Open Tasks', value: 18, caption: 'Starter data source', icon: 'mdi-clipboard-check-outline' },
      { title: 'Revenue', value: '$12,450', caption: 'Replace with API data', icon: 'mdi-cash-multiple' },
    ],
    alerts: [
      { severity: 'info', title: 'Dashboard Data Ready', message: 'Replace this starter snapshot with API-backed data.' },
    ],
  };
}

export async function refresh${pascalName}DashboardSnapshot()${typed ? `: Promise<${interfaceType}>` : ''} {
  return load${pascalName}DashboardSnapshot();
}
`;
}

function buildAssetServiceFileSource(ext: ScriptExt, answers: AssetServiceAnswers) {
  const pascalName = toPascalCase(answers.name);
  const constantName = `${sanitizeIdentifier(answers.name).toUpperCase()}_SERVICE_PATH`;
  const typed = ext === '.ts';

  return `${GENERATED_MARKER} create asset service
import { Api } from 'vuetify-extended';

export const ${constantName} = ${serializeString(answers.path)};

${typed ? `export type ${pascalName}Id = string | number;

export interface ${pascalName}Metadata {
  _id?: ${pascalName}Id;
  id?: ${pascalName}Id;
  assetId?: ${pascalName}Id;
  name?: string;
  fileName?: string;
  mimeType?: string;
  size?: number;
  url?: string;
  objectType?: string;
  objectId?: ${pascalName}Id;
  [key: string]: any;
}

export interface Upload${pascalName}Options {
  objectType?: string;
  objectId?: ${pascalName}Id;
  folder?: string;
  metadata?: Record<string, any>;
}

` : ''}export function get${pascalName}Service() {
  return Api.instance.service(${constantName});
}

export async function fileToBase64(file${typed ? ': File' : ''})${typed ? ': Promise<string>' : ''} {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result || ''));
    reader.onerror = () => reject(reader.error || new Error('Could not read file.'));
    reader.readAsDataURL(file);
  });
}

export async function upload${pascalName}(file${typed ? ': File' : ''}, options${typed ? `: Upload${pascalName}Options = {}` : ' = {}'}) {
  const data = await fileToBase64(file);
  return get${pascalName}Service().create({
    fileName: file.name,
    mimeType: file.type,
    size: file.size,
    data,
    objectType: options.objectType,
    objectId: options.objectId,
    folder: options.folder,
    ...(options.metadata || {}),
  });
}

export async function get${pascalName}Metadata(id${typed ? `: ${pascalName}Id` : ''})${typed ? `: Promise<${pascalName}Metadata>` : ''} {
  return get${pascalName}Service().get(id);
}

export async function remove${pascalName}(id${typed ? `: ${pascalName}Id` : ''}) {
  return get${pascalName}Service().remove(id);
}

export async function build${pascalName}DownloadUrl(asset${typed ? `: ${pascalName}Metadata | ${pascalName}Id` : ''})${typed ? ': Promise<string>' : ''} {
  const metadata = typeof asset === 'object' ? asset : await get${pascalName}Metadata(asset);
  if (metadata.url) {
    return metadata.url;
  }
  const id = metadata.assetId || metadata._id || metadata.id;
  return ${constantName} + '/' + id;
}
`;
}

function buildAutocompleteSourceFileSource(ext: ScriptExt, answers: AutocompleteSourceAnswers) {
  const pascalName = toPascalCase(answers.name.replace(/-autocomplete$/i, ''));
  const constantName = `${sanitizeIdentifier(answers.name).toUpperCase()}_SERVICE_PATH`;
  const typed = ext === '.ts';
  const itemType = `${pascalName}AutocompleteItem`;
  const pageType = `${pascalName}AutocompletePage`;

  return `${GENERATED_MARKER} create autocomplete source
import { Api } from 'vuetify-extended';

export const ${constantName} = ${serializeString(answers.servicePath)};

${typed ? `export interface ${itemType} {
  [key: string]: any;
}

export interface ${pageType} {
  data: ${itemType}[];
  skip: number;
  limit: number;
  total: number;
}

` : ''}export function get${pascalName}AutocompleteService() {
  return Api.instance.service(${constantName});
}

export async function search${pascalName}Autocomplete(searchText${typed ? ': string' : ''}, page${typed ? ': number' : ''} = 1, limit${typed ? ': number' : ''} = 20, extraQuery${typed ? ': Record<string, any> = {}' : ' = {}'})${typed ? `: Promise<${pageType}>` : ''} {
  const normalizedLimit = Math.max(1, Number(limit) || 20);
  const normalizedPage = Math.max(1, Number(page) || 1);
  const normalizedSkip = Math.max(normalizedPage - 1, 0) * normalizedLimit;
  const query: any = {
    $limit: normalizedLimit,
    $skip: normalizedSkip,
    $sort: { ${serializeKey(answers.labelField)}: 1 },
    ...(extraQuery || {}),
  };

  if (String(searchText || '').trim()) {
    query.$or = [
      {
        ${serializeKey(answers.labelField)}: {
          $regex: String(searchText).trim(),
          $options: 'i',
        },
      },
    ];
  }

  const response = await get${pascalName}AutocompleteService().find({ query });
  const data = Array.isArray(response?.data) ? response.data : (Array.isArray(response) ? response : []);
  const total = Number(response?.total ?? data.length);
  const skip = Number(response?.skip ?? normalizedSkip);
  const resolvedLimit = Number(response?.limit ?? normalizedLimit);

  return {
    data,
    skip,
    limit: resolvedLimit,
    total,
  };
}

export async function resolve${pascalName}AutocompleteValue(value${typed ? ': any' : ''}, extraQuery${typed ? ': Record<string, any> = {}' : ' = {}'})${typed ? `: Promise<${itemType} | ${itemType}[] | undefined>` : ''} {
  if (value === undefined || value === null || value === '') {
    return undefined;
  }

  const values = Array.isArray(value) ? value.filter((item) => item !== undefined && item !== null && item !== '') : [value];
  if (values.length === 0) {
    return Array.isArray(value) ? [] : undefined;
  }

  if (values.length === 1 && !Array.isArray(value)) {
    return get${pascalName}AutocompleteService().get(values[0], extraQuery);
  }

  const response = await get${pascalName}AutocompleteService().find({
    query: {
      ${serializeKey(answers.valueField)}: { $in: values },
      ...(extraQuery || {}),
    },
  });

  return Array.isArray(response?.data) ? response.data : (Array.isArray(response) ? response : []);
}
`;
}

function buildHeaderItemBlock(answers: HeaderItemAnswers, marker: string) {
  if (answers.kind === 'title') {
    return `    ${marker}
    $ATB({
      title: ${serializeUITextDescriptor(shellTextKey(answers.region, answers.kind, 'title'), answers.text)},
      subtitle: ${serializeUITextDescriptor(shellTextKey(answers.region, answers.kind, 'subtitle'), answers.subtitle || 'Built with vuetify-extended')},
      overline: ${serializeUITextDescriptor(shellTextKey(answers.region, answers.kind, 'overline'), answers.overline || 'Workspace')},
      icon: ${serializeString(answers.icon)},
      color: ${serializeString(answers.color)},
    }),`;
  }

  if (answers.kind === 'environment') {
    return `    ${marker}
    $ENV({
      text: ${serializeUITextDescriptor(shellTextKey(answers.region, answers.kind, 'text'), answers.text)},
      color: ${serializeString(answers.color)},
      variant: 'outlined',
    }),`;
  }

  if (answers.kind === 'status') {
    return `    ${marker}
    $STB({
      text: ${serializeUITextDescriptor(shellTextKey(answers.region, answers.kind, 'text'), answers.text)},
      icon: ${serializeString(answers.icon)},
      color: ${serializeString(answers.color)},
      variant: 'tonal',
    }),`;
  }

  if (answers.kind === 'user') {
    return `    ${marker}
    $USR({
      name: ${serializeUITextDescriptor(shellTextKey(answers.region, answers.kind, 'name'), answers.text)},
      subtitle: ${serializeUITextDescriptor(shellTextKey(answers.region, answers.kind, 'subtitle'), answers.subtitle || 'Workspace User')},
      email: ${serializeUITextDescriptor(shellTextKey(answers.region, answers.kind, 'email'), 'user@example.com')},
      avatarColor: ${serializeString(answers.color)},
    }),`;
  }

  return `    ${marker}
    $SIA(
      {
        icon: ${serializeString(answers.icon)},
        title: ${serializeUITextDescriptor(shellTextKey(answers.region, answers.kind, 'title'), answers.text)},
        color: ${serializeString(answers.color)},
      },
      {
        onClicked: () => {
          Dialogs.$info(${serializeUITextDescriptor(shellTextKey(answers.region, answers.kind, 'clicked'), `${answers.text} clicked.`)});
        },
      },
    ),`;
}

function buildBootstrapThemeFileSource(ext: ScriptExt, answers: BootstrapThemeAnswers) {
  const typed = ext === '.ts';
  return `${GENERATED_MARKER} bootstrap theme
export type AppThemeMode = 'light' | 'dark';

export const APP_THEME_STORAGE_KEY = 'vuetify-extended-theme-mode';

export function getThemeMode()${typed ? ': AppThemeMode' : ''} {
  if (typeof window === 'undefined') {
    return ${serializeString(answers.mode)};
  }

  const stored = window.localStorage.getItem(APP_THEME_STORAGE_KEY);
  if (stored === 'light' || stored === 'dark') {
    return stored;
  }

  return ${serializeString(answers.mode)};
}

export function setThemeMode(mode${typed ? ': AppThemeMode' : ''}) {
  if (typeof window !== 'undefined') {
    window.localStorage.setItem(APP_THEME_STORAGE_KEY, mode);
  }
  return mode;
}

export function toggleThemeMode()${typed ? ': AppThemeMode' : ''} {
  const nextMode = getThemeMode() === 'dark' ? 'light' : 'dark';
  return setThemeMode(nextMode);
}

export function createVuetifyThemeOptions() {
  return {
    defaultTheme: getThemeMode(),
    themes: {
      light: {
        dark: false,
        colors: {
          primary: '#1867c0',
          secondary: '#5cbbf6',
          success: '#2e7d32',
          info: '#0288d1',
          warning: '#ed6c02',
          error: '#d32f2f',
          background: '#f5f7fb',
          surface: '#ffffff',
        },
      },
      dark: {
        dark: true,
        colors: {
          primary: '#90caf9',
          secondary: '#80cbc4',
          success: '#81c784',
          info: '#4fc3f7',
          warning: '#ffb74d',
          error: '#ef9a9a',
          background: '#0f172a',
          surface: '#111827',
        },
      },
    },
  };
}
`;
}

function ensureTriggerSearchMarkers(source: string) {
  let next = ensureVuetifyExtendedImport(source, ['$FD']);
  if (!/searchFields:\s*async\s*\(/.test(next)) {
    const block = `      searchFields: async () => ({
        fields: [
          ${TRIGGER_SEARCH_MARKER}
        ],
      }),
`;
    next = insertIntoOptionsObject(next, block, ['topChildren:', 'format:', 'on:', 'sideButtons:']) || '';
    if (!next) {
      return undefined;
    }
  }

  if (!next.includes(TRIGGER_SEARCH_MARKER)) {
    next = next.replace(/fields:\s*\[/, (match) => `${match}\n          ${TRIGGER_SEARCH_MARKER}`);
  }

  return next;
}

function ensureTriggerActionMarkers(source: string) {
  let next = ensureVuetifyExtendedImport(source, ['$BN', 'Dialogs']);
  if (!/sideButtons:\s*\(/.test(next)) {
    const block = `      sideButtons: (_props, _context, trigger) => [
        ${TRIGGER_ACTION_MARKER}
      ],
`;
    next = insertIntoOptionsObject(next, block, []) || '';
    if (!next) {
      return undefined;
    }
  }

  if (!next.includes(TRIGGER_ACTION_MARKER)) {
    next = next.replace(/sideButtons:\s*\([^)]*\)\s*=>\s*\[/, (match) => `${match}\n        ${TRIGGER_ACTION_MARKER}`);
  }

  return next;
}

function ensureReportActionMarkers(source: string) {
  let next = ensureVuetifyExtendedImport(source, ['$BN', 'Dialogs']);
  if (!/sideButtons:\s*\(/.test(next)) {
    const block = `      sideButtons: (_props, _context, report) => [
        ${REPORT_ACTION_MARKER}
      ],
`;
    next = insertIntoOptionsObject(next, block, []) || '';
    if (!next) {
      return undefined;
    }
  }

  if (!next.includes(REPORT_ACTION_MARKER)) {
    next = next.replace(/sideButtons:\s*\([^)]*\)\s*=>\s*\[/, (match) => `${match}\n        ${REPORT_ACTION_MARKER}`);
  }

  return next;
}

function ensureHeaderMarkers(source: string) {
  let next = source;
  if (!next.includes(HEADER_IMPORT_MARKER)) {
    const importMatches = Array.from(next.matchAll(/^import .*$/gm));
    if (importMatches.length === 0) {
      return undefined;
    }
    const lastImport = importMatches[importMatches.length - 1];
    const insertAt = (lastImport.index || 0) + lastImport[0].length;
    next = `${next.slice(0, insertAt)}\n${HEADER_IMPORT_MARKER}${next.slice(insertAt)}`;
  }

  next = ensureHeaderRegionMarker(next, 'buildHeaderStart', HEADER_START_MARKER) || '';
  if (!next) return undefined;
  next = ensureHeaderRegionMarker(next, 'buildHeaderCenter', HEADER_CENTER_MARKER) || '';
  if (!next) return undefined;
  next = ensureHeaderRegionMarker(next, 'buildHeaderEnd', HEADER_END_MARKER) || '';
  if (!next) return undefined;

  return next;
}

function ensureHeaderRegionMarker(source: string, functionName: string, marker: string) {
  if (source.includes(marker)) {
    return source;
  }

  const pattern = new RegExp(`(export function ${functionName}\\([^)]*\\)[\\s\\S]*?return \\[\\n)`);
  if (!pattern.test(source)) {
    return undefined;
  }

  return source.replace(pattern, `$1    ${marker}\n`);
}

function patchMainForThemeBootstrap(source: string, mainFile: string) {
  const themeImportLine = `import { createVuetifyThemeOptions } from ${serializeString(buildRelativeImportSpecifier(mainFile, path.join(path.dirname(mainFile), 'bootstrap', `theme${path.extname(mainFile) || '.ts'}`)))};`;
  let next = source;

  if (!next.includes(themeImportLine)) {
    const importMatches = Array.from(next.matchAll(/^import .*$/gm));
    if (importMatches.length === 0) {
      return undefined;
    }
    const lastImport = importMatches[importMatches.length - 1];
    const insertAt = (lastImport.index || 0) + lastImport[0].length;
    next = `${next.slice(0, insertAt)}\n${themeImportLine}${next.slice(insertAt)}`;
  }

  if (/theme:\s*createVuetifyThemeOptions\(\)/.test(next)) {
    return next;
  }

  const vuetifyPattern = /const\s+vuetify\s*=\s*createVuetify\(\{\s*components,\s*directives,([\s\S]*?)\}\);/m;
  if (!vuetifyPattern.test(next)) {
    return undefined;
  }

  next = next.replace(vuetifyPattern, (_match, existingTail) => {
    if (/theme:/.test(existingTail)) {
      return _match;
    }
    return `const vuetify = createVuetify({
  components,
  directives,
  theme: createVuetifyThemeOptions(),${existingTail}
});`;
  });

  return next;
}

function insertIntoOptionsObject(source: string, block: string, anchors: string[]) {
  for (const anchor of anchors) {
    if (source.includes(anchor)) {
      return source.replace(anchor, `${block}      ${anchor}`);
    }
  }

  const closingPattern = /\r?\n([ \t]*)},\r?\n([ \t]*)\);/g;
  let lastMatch: RegExpMatchArray | undefined;
  for (const match of source.matchAll(closingPattern)) {
    lastMatch = match;
  }

  if (lastMatch && typeof lastMatch.index === 'number') {
    const insertAt = lastMatch.index + (lastMatch[0].startsWith('\r\n') ? 2 : 1);
    return `${source.slice(0, insertAt)}${block}${source.slice(insertAt)}`;
  }

  return undefined;
}

function ensureVuetifyExtendedImport(source: string, names: string[]) {
  const importPattern = /import\s*\{([^}]*)\}\s*from\s*['"]vuetify-extended['"];?/;
  if (!importPattern.test(source)) {
    return ensureImportLine(source, `import { ${names.join(', ')} } from 'vuetify-extended';`);
  }

  return source.replace(importPattern, (_match: string, importedNames: string) => {
    const parts = importedNames
      .split(',')
      .map((part: string) => part.trim())
      .filter(Boolean);

    for (const name of names) {
      if (!parts.includes(name)) {
        parts.push(name);
      }
    }

    return `import { ${parts.join(', ')} } from 'vuetify-extended';`;
  });
}

function ensureImportLine(source: string, importLine: string) {
  if (source.includes(importLine)) {
    return source;
  }
  const importMatches = Array.from(source.matchAll(/^import .*$/gm));
  if (importMatches.length === 0) {
    return `${importLine}\n${source}`;
  }
  const lastImport = importMatches[importMatches.length - 1];
  const insertAt = (lastImport.index || 0) + lastImport[0].length;
  return `${source.slice(0, insertAt)}\n${importLine}${source.slice(insertAt)}`;
}

function ensureSimpleExport(file: string, exportLine: string) {
  const current = fileExists(file) ? fs.readFileSync(file, 'utf8') : `${GENERATED_MARKER} index\n`;
  const next = appendLines(current, [exportLine]);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, next, 'utf8');
}

function appendLines(source: string, linesToAdd: string[]) {
  const lines = source.trimEnd().split('\n').filter(Boolean);
  for (const line of linesToAdd) {
    if (!lines.includes(line)) {
      lines.push(line);
    }
  }
  return `${lines.join('\n')}\n`;
}

function prepareWrites(options: CreateCommandOptions, writes: FileWrite[]): 'ok' | 'dry-run' | 'error' {
  const existing = writes.filter((entry) => !options.force && fileExists(entry.file));
  if (existing.length > 0) {
    options.stderr.write(
      `[vuetify-ext] The following files already exist:\n- ${existing.map((entry) => relativeToCwd(options.cwd, entry.file)).join('\n- ')}\nUse --force to overwrite them.\n`,
    );
    return 'error';
  }
  if (options.dryRun) {
    options.stdout.write('[vuetify-ext] Dry run only. The following files would be written:\n');
    for (const write of writes) {
      options.stdout.write(`- ${relativeToCwd(options.cwd, write.file)}\n`);
    }
    return 'dry-run';
  }
  return 'ok';
}

function writeFiles(writes: FileWrite[]) {
  for (const write of writes) {
    fs.mkdirSync(path.dirname(write.file), { recursive: true });
    fs.writeFileSync(write.file, write.content, 'utf8');
  }
}

function writeSuccess(options: CreateCommandOptions, heading: string, files: string[]) {
  options.stdout.write(`[vuetify-ext] ${heading}:\n`);
  for (const file of Array.from(new Set(files))) {
    options.stdout.write(`- ${relativeToCwd(options.cwd, file)}\n`);
  }
}

function findExistingFile(cwd: string, files: string[]) {
  return files
    .map((file) => path.join(cwd, file))
    .find((file) => fileExists(file));
}

function resolveProjectScriptExtension(cwd: string): ScriptExt {
  if (findExistingFile(cwd, ['src/main.ts', 'src/menu/index.ts', 'src/bootstrap/index.ts'])) {
    return '.ts';
  }
  return fileExists(path.join(cwd, 'tsconfig.json')) ? '.ts' : '.js';
}

function resolveExistingPageScriptExtension(cwd: string, page: string): ScriptExt | undefined {
  const tsFiles = ['report.ts', 'form.ts', 'trigger.ts', 'collection.ts', 'dashboard.ts', 'index.ts'];
  if (tsFiles.some((file) => fileExists(path.join(cwd, 'src/pages', page, file)))) {
    return '.ts';
  }
  const jsFiles = ['report.js', 'form.js', 'trigger.js', 'collection.js', 'dashboard.js', 'index.js'];
  if (jsFiles.some((file) => fileExists(path.join(cwd, 'src/pages', page, file)))) {
    return '.js';
  }
  return undefined;
}

function verifyExpectedPageExport(file: string, exportName: string) {
  if (!fileExists(file)) {
    return false;
  }
  const source = fs.readFileSync(file, 'utf8');
  const escaped = escapeRegExp(exportName);
  return [
    new RegExp(`export\\s+function\\s+${escaped}\\s*\\(`),
    new RegExp(`export\\s+(?:const|let|var)\\s+${escaped}\\s*=`),
    new RegExp(`export\\s*\\{[^}]*\\b${escaped}\\b[^}]*\\}`),
  ].some((pattern) => pattern.test(source));
}

function fileExists(file: string) {
  return fs.existsSync(file);
}

function relativeToCwd(cwd: string, file: string) {
  return path.relative(cwd, file) || '.';
}

function humanizeName(value: string) {
  return value
    .replace(/[-_]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/\b\w/g, (match) => match.toUpperCase());
}

function slugifyName(value: string) {
  return value
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
}

function toPascalCase(value: string) {
  return slugifyName(value)
    .split('-')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function sanitizeIdentifier(value: string) {
  let identifier = toPascalCase(value);
  if (!identifier) {
    identifier = 'GeneratedValue';
  }
  if (/^[0-9]/.test(identifier)) {
    identifier = `Value${identifier}`;
  }
  return identifier.charAt(0).toLowerCase() + identifier.slice(1);
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function serializeString(value: string) {
  return JSON.stringify(value);
}

function serializeUITextDescriptor(key: string, fallback: string) {
  return `{ key: ${serializeString(key)}, fallback: ${serializeString(fallback)} }`;
}

function pageTextKey(page: string, ...segments: string[]) {
  return ['pages', slugifyName(page), ...segments].join('.');
}

function dialogTextKey(name: string, ...segments: string[]) {
  return ['dialogs', slugifyName(name), ...segments].join('.');
}

function shellTextKey(region: HeaderRegion, kind: HeaderItemKind, leaf: string) {
  return ['bootstrap', 'header', region, kind, leaf].join('.');
}

function serializeKey(value: string) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

function routeIdentifierForName(value: string) {
  const base = sanitizeIdentifier(value);
  return /route$/i.test(base) ? base : `${base}Route`;
}

function normalizePositiveInt(value: string | number | undefined, fallback: number) {
  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback;
}

function normalizeMode(value: string | undefined, fallback: ReportMode): ReportMode {
  if (value === 'create' || value === 'edit' || value === 'display') {
    return value;
  }
  return fallback;
}

function defaultModeForTarget(target: PageTarget): ReportMode {
  return target === 'report' || target === 'dashboard' ? 'display' : 'edit';
}

function defaultHeaderText(kind: HeaderItemKind) {
  if (kind === 'title') return 'My Workspace';
  if (kind === 'environment') return 'Starter';
  if (kind === 'status') return 'Ready';
  if (kind === 'user') return 'Workspace User';
  return 'Open Help';
}

function defaultHeaderIcon(kind: HeaderItemKind) {
  if (kind === 'title') return 'mdi-view-dashboard-outline';
  if (kind === 'environment') return 'mdi-tag-outline';
  if (kind === 'status') return 'mdi-check-circle-outline';
  if (kind === 'user') return 'mdi-account-circle-outline';
  return 'mdi-help-circle-outline';
}

function defaultHeaderColor(kind: HeaderItemKind) {
  if (kind === 'environment') return 'info';
  if (kind === 'status') return 'success';
  if (kind === 'user') return 'primary';
  return 'primary';
}

function buildRelativeImportSpecifier(fromFile: string, targetFile: string) {
  const relative = path.relative(path.dirname(fromFile), targetFile).replace(/\\/g, '/');
  const withoutExt = relative.replace(/\.(ts|js)$/i, '');
  return withoutExt.startsWith('.') ? withoutExt : `./${withoutExt}`;
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

async function promptText(rl: readline.Interface, label: string, defaultValue?: string, allowEmpty: boolean = false) {
  while (true) {
    const suffix = defaultValue ? ` [${defaultValue}]` : '';
    const value = (await ask(rl, `${label}${suffix}: `)).trim();
    if (value.length > 0) return value;
    if (defaultValue !== undefined) return defaultValue;
    if (allowEmpty) return '';
  }
}

async function promptChoice(rl: readline.Interface, label: string, choices: string[], defaultValue: string) {
  while (true) {
    const value = (await ask(rl, `${label} [${defaultValue}]: `)).trim().toLowerCase();
    const resolved = value || defaultValue;
    if (choices.includes(resolved)) return resolved;
  }
}

async function promptNumber(rl: readline.Interface, label: string, defaultValue: number, min: number) {
  while (true) {
    const value = (await ask(rl, `${label} [${defaultValue}]: `)).trim();
    if (!value) return defaultValue;
    const parsed = Number(value);
    if (Number.isInteger(parsed) && parsed >= min) return parsed;
  }
}

function ask(rl: readline.Interface, prompt: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => resolve(answer));
  });
}
