import { VNode, Ref } from "vue";
import { ReportMode, UIBase } from "./base";
import { Menu } from "./menu";
import { Report } from "./report";
import { Collection } from "./collection";
import { Selector } from "./selector";
import { Field } from "./field";
import { Button } from "./button";
import { DialogForm } from "./dialogform";
export interface AppParams {
    ref?: string;
    udfQuery?: any;
    title?: string;
    showHeader?: boolean;
    showFooter?: boolean;
    showFab?: boolean;
    fabIcon?: string;
    fabColor?: string;
    fabPosition?: 'bottom-right' | 'bottom-left';
    fabDirection?: 'up' | 'left';
    fabLabel?: string;
    fabShortcut?: string;
    headerLayout?: 'balanced' | 'auto' | 'stacked';
    footerLayout?: 'balanced' | 'auto' | 'stacked';
    headerStartWidth?: string | number;
    headerCenterWidth?: string | number;
    headerEndWidth?: string | number;
    footerStartWidth?: string | number;
    footerCenterWidth?: string | number;
    footerEndWidth?: string | number;
    backgroundColor?: string;
    backgroundGradient?: string;
    backgroundImage?: string;
    backgroundSize?: string;
    backgroundPosition?: string;
    backgroundRepeat?: string;
    backgroundAttachment?: string;
    backgroundOverlay?: string;
}
export type AppShellContent = UIBase | VNode | string | number | boolean | null | undefined;
export interface AppOptions {
    menu?: (app: AppMain) => Promise<Menu | undefined> | Menu | undefined;
    udfs?: (app: AppMain, objectType: string | string[], query: any) => Promise<any[]>;
    makeUDF?: (app: AppMain, options: any) => Field | undefined;
    fabButtons?: AppFabButtonsFactory;
    header?: (app: AppMain) => AppShellContent | AppShellContent[];
    footer?: (app: AppMain) => AppShellContent | AppShellContent[];
    headerStart?: (app: AppMain) => AppShellContent | AppShellContent[];
    headerCenter?: (app: AppMain) => AppShellContent | AppShellContent[];
    headerEnd?: (app: AppMain) => AppShellContent | AppShellContent[];
    footerStart?: (app: AppMain) => AppShellContent | AppShellContent[];
    footerCenter?: (app: AppMain) => AppShellContent | AppShellContent[];
    footerEnd?: (app: AppMain) => AppShellContent | AppShellContent[];
}
export type AppFabButtonsFactory = Button[] | ((app: AppMain, item?: UIBase, stackItem?: AppStackItem) => Button[]);
export interface AppScreenParams {
    showFab?: boolean;
    fabIcon?: string;
    fabColor?: string;
    fabPosition?: 'bottom-right' | 'bottom-left';
    fabDirection?: 'up' | 'left';
    fabLabel?: string;
    fabShortcut?: string;
    fabButtons?: AppFabButtonsFactory;
    [key: string]: any;
}
export interface AppStackItem {
    type: "menu" | "report" | "collection" | "selector" | "ui";
    item: UIBase;
    params: AppScreenParams;
}
export declare class AppMain extends UIBase {
    private params;
    private options;
    private stack;
    private stackRefState;
    private activeItemRefState;
    private loaded;
    private index;
    private selectors;
    private selectorCount;
    private dialogs;
    private dialogCount;
    private selectorFocusTargets;
    private dialogFocusTargets;
    private fabButtonInstances;
    private fabOpen;
    private shortcutHandler?;
    private static defaultParams;
    constructor(params?: AppParams, options?: AppOptions);
    static setDefault(value: AppParams, reset?: boolean): void;
    get $ref(): string | undefined;
    setParams(params: AppParams): void;
    get $params(): AppParams;
    get stackRef(): Ref<AppStackItem[]>;
    get activeItemRef(): Ref<AppStackItem | undefined>;
    private syncStackRefs;
    props(): never[];
    menu(): Promise<Menu | undefined>;
    render(props: any, context: any): VNode | VNode[] | undefined;
    private renderStackContent;
    private wrapStackItemContent;
    private wrapWithFab;
    private getActiveStackItem;
    private resolveFabConfig;
    private resolveFabButtonSource;
    private buildFabButtons;
    private renderFabActions;
    private triggerComponentShortcut;
    private triggerActiveScreenShortcut;
    private triggerFabButtonShortcut;
    private triggerFabShortcut;
    private onAppKeydown;
    private renderShellRegion;
    private renderShellBar;
    private renderShellBarSection;
    private getShellLayout;
    private getShellWidthValue;
    private normalizeCssSize;
    private getShellBarContainerStyle;
    private getShellBarSectionStyle;
    private mainShellStyle;
    private mainShellContentStyle;
    private mainShellOverlayStyle;
    private normalizeShellContent;
    private normalizeShellItem;
    private activateCurrentItem;
    $reload(): Promise<void>;
    private loadApp;
    $getUDFs(objectType: string | string[]): Promise<any[]>;
    $makeUDF(options: any, mode?: ReportMode): Field | undefined;
    $showMenu(menu: Menu, params?: any): Promise<void>;
    $showReport(report: Report, params?: any, replace?: boolean): Promise<void>;
    $showCollection(collection: Collection, params?: any, replace?: boolean): Promise<void>;
    $showUI(ui: UIBase, params?: any, replace?: boolean): Promise<void>;
    $showSelector(selector: Selector, params?: any): Promise<void>;
    $showDialog(dialog: DialogForm, params?: any): Promise<void>;
    $back(): Promise<void>;
    $pop(count?: number): Promise<void>;
    private onCancel;
    private onSelectorCancel;
    private onDialogCancel;
    private captureActiveElement;
    private restoreFocus;
    attachEventListeners(): void;
    removeEventListeners(): void;
}
export declare const $APP: (params?: AppParams, options?: AppOptions) => AppMain;
