import { VNode } from "vue";
import { UIBase } from "./base";
import { ButtonParams } from "./button";
import { OnHandler } from "./lib";
export interface SelectorParams {
    ref?: string;
    invisible?: boolean;
    persistent?: boolean;
    multiple?: boolean;
    title?: string;
    subtitle?: string;
    mode?: 'create' | 'edit' | 'display';
    cancelButton?: ButtonParams;
    saveButton?: ButtonParams;
    elevation?: number;
    maxWidth?: number | string | undefined;
    minWidth?: number | string | undefined;
    width?: number | string | undefined;
    selectFields?: any;
    objectType?: any;
    idField?: any;
    returnObject?: boolean;
    textField?: any;
    defaultButtonPosition?: "top" | "bottom" | "both";
    alignContent?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    dense?: boolean | undefined;
    justify?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    align?: "center" | "end" | "start" | "stretch" | "baseline" | undefined;
}
export interface SelectorOptions {
    cancel?: () => Promise<void>;
    access?: (selector: Selector, mode?: 'create' | 'edit' | 'display') => Promise<boolean> | boolean;
    load?: (selector: Selector, mode?: 'create' | 'edit' | 'display') => Promise<any[]> | any[];
    query?: (selector: Selector, mode?: 'create' | 'edit' | 'display') => Promise<any> | any;
    format?: (item: any, items: any[], selector: Selector, mode?: 'create' | 'edit' | 'display') => Promise<any> | any;
    selected?: (item: any, selector: Selector, mode?: 'create' | 'edit' | 'display') => Promise<any> | any;
    setup?: (selector: Selector) => void;
    on?: (selector: Selector) => OnHandler;
}
export declare class Selector extends UIBase {
    private params;
    private hasAccess;
    private options;
    private topButtonInstances;
    private bottomButtonInstances;
    private items;
    private storage;
    private dialog;
    private loading;
    private dialogRoot;
    private loaded;
    private static defaultParams;
    constructor(params?: SelectorParams, options?: SelectorOptions);
    static setDefault(value: SelectorParams, reset?: boolean): void;
    get $ref(): string | undefined;
    setParams(params: SelectorParams): void;
    get $params(): SelectorParams;
    get $access(): boolean;
    private runAccess;
    validate(): Promise<string | true | undefined | void>;
    selected(item: any, mode?: 'create' | 'edit' | 'display'): Promise<void>;
    format(item: any, items: any[]): Promise<any | undefined>;
    cancel(): Promise<void>;
    access(mode?: 'create' | 'edit' | 'display'): Promise<boolean>;
    load(mode?: 'create' | 'edit' | 'display'): Promise<any[]>;
    query(search: string, mode?: 'create' | 'edit' | 'display'): Promise<any>;
    props(): never[];
    private loadItems;
    render(props: any, context: any): VNode | undefined;
    private toCssSize;
    private clampToViewport;
    private cardSizeStyle;
    private buildTitle;
    private buildSubTitle;
    private buildBody;
    private buildSearchBar;
    private buildStatusMessage;
    show(): Promise<void>;
    hide(): Promise<void>;
    private initialize;
    private buildTopActions;
    private buildBottomActions;
    private buildDefaultButtons;
    private onSelectItem;
    private onSelectorKeyup;
    private setDialogRoot;
    private focusPrimaryInput;
    private findFocusTarget;
    private waitForFocusFrame;
    private isVisibleFocusable;
    private onCancelClicked;
    forceCancel(): Promise<void>;
    setup(props: any, context: any): void;
    private handleOn;
}
export declare const $SL: (params?: SelectorParams, options?: SelectorOptions) => Selector;
