import { VNode, Ref } from "vue";
import { MenuTarget, ReportMode, UIBase } from "./base";
import { Menu } from "./menu";
import { Report } from "./report";
import { Collection } from "./collection";
import { Selector } from "./selector";
import { Trigger } from "./trigger";
import { Field } from "./field";
import { Button } from "./button";
import { DialogForm } from "./dialogform";
import { type AppNavigationOptions, type InlineNavigationOptions, type NavigationEntry, type NavigationMenuRestoreStep, type NavigationScreenFactory, type NavigationScreenType, type UIText } from "./runtime";
export interface AppParams {
    ref?: string;
    udfQuery?: any;
    title?: UIText;
    mobileTitle?: UIText;
    mobileLogo?: string;
    showHeader?: boolean;
    showFooter?: boolean;
    showFab?: boolean;
    fabIcon?: string;
    fabColor?: string;
    fabPosition?: 'bottom-right' | 'bottom-left';
    fabDirection?: 'up' | 'left';
    fabLabel?: UIText;
    fabShortcut?: string;
    headerLayout?: 'balanced' | 'auto' | 'stacked';
    footerLayout?: 'balanced' | 'auto' | 'stacked';
    headerStartWidth?: string | number;
    headerCenterWidth?: string | number;
    headerEndWidth?: string | number;
    footerStartWidth?: string | number;
    footerCenterWidth?: string | number;
    footerEndWidth?: string | number;
    backgroundColor?: string;
    backgroundGradient?: string;
    backgroundImage?: string;
    backgroundSize?: string;
    backgroundPosition?: string;
    backgroundRepeat?: string;
    backgroundAttachment?: string;
    backgroundOverlay?: string;
}
export type AppShellContent = UIBase | VNode | string | number | boolean | null | undefined;
export interface AppOptions {
    menu?: (app: AppMain) => Promise<Menu | undefined> | Menu | undefined;
    leftNav?: (app: AppMain) => Promise<Menu | undefined> | Menu | undefined;
    rightNav?: (app: AppMain) => Promise<Menu | undefined> | Menu | undefined;
    leftNavOptions?: AppSideNavOptions;
    rightNavOptions?: AppSideNavOptions;
    udfs?: (app: AppMain, objectType: string | string[], query: any) => Promise<any[]>;
    makeUDF?: (app: AppMain, options: any) => Field | undefined;
    fabButtons?: AppFabButtonsFactory;
    navigation?: AppNavigationOptions;
    header?: (app: AppMain) => AppShellContent | AppShellContent[];
    footer?: (app: AppMain) => AppShellContent | AppShellContent[];
    headerStart?: (app: AppMain) => AppShellContent | AppShellContent[];
    headerCenter?: (app: AppMain) => AppShellContent | AppShellContent[];
    headerEnd?: (app: AppMain) => AppShellContent | AppShellContent[];
    footerStart?: (app: AppMain) => AppShellContent | AppShellContent[];
    footerCenter?: (app: AppMain) => AppShellContent | AppShellContent[];
    footerEnd?: (app: AppMain) => AppShellContent | AppShellContent[];
}
export type AppFabButtonsFactory = Button[] | ((app: AppMain, item?: UIBase, stackItem?: AppStackItem) => Button[]);
export interface AppSideNavOptions {
    enabled?: boolean;
    side?: 'left' | 'right';
    mode?: 'persistent' | 'temporary' | 'rail';
    width?: number | string;
    open?: boolean;
    overlay?: boolean;
    breakpoint?: number;
    autoCloseOnNavigate?: boolean;
    mobileMode?: 'temporary' | 'rail';
    showToggleButton?: boolean;
    toggleIcon?: string;
    toggleColor?: string;
    toggleVariant?: string;
    toggleTooltip?: UIText;
}
export interface AppScreenParams {
    showFab?: boolean;
    fabIcon?: string;
    fabColor?: string;
    fabPosition?: 'bottom-right' | 'bottom-left';
    fabDirection?: 'up' | 'left';
    fabLabel?: UIText;
    fabShortcut?: string;
    fabButtons?: AppFabButtonsFactory;
    navigationKey?: string;
    navigationType?: NavigationScreenType;
    navigationTitle?: UIText;
    navigationParams?: any;
    navigationState?: any;
    navigationMenuRestorePath?: NavigationMenuRestoreStep[];
    persistState?: boolean | 'default' | 'local';
    excludeFromRestore?: boolean;
    navigation?: InlineNavigationOptions<any>;
    [key: string]: any;
}
export interface AppStackItem {
    type: "menu" | "report" | "trigger" | "collection" | "selector" | "ui";
    item: UIBase;
    params: AppScreenParams;
    navigation?: NavigationEntry;
}
export declare class AppMain extends UIBase {
    private params;
    private options;
    private stack;
    private stackRefState;
    private activeItemRefState;
    private loaded;
    private index;
    private selectors;
    private selectorCount;
    private dialogs;
    private dialogCount;
    private selectorFocusTargets;
    private dialogFocusTargets;
    private fabButtonInstances;
    private fabOpen;
    private shortcutHandler?;
    private compactShellLayout;
    private shellLayoutMediaQuery?;
    private shellLayoutMediaHandler?;
    private mobileHeaderDrawerOpen;
    private footerHeight;
    private footerElement?;
    private footerResizeObserver?;
    private viewportWidth;
    private leftSideMenu;
    private rightSideMenu;
    private leftSideMenuOpen;
    private rightSideMenuOpen;
    private leftSideMenuSource;
    private rightSideMenuSource;
    private leftSideMenuState?;
    private rightSideMenuState?;
    private leftSideMenuTouched;
    private rightSideMenuTouched;
    private leftSideMenuRuntime?;
    private rightSideMenuRuntime?;
    private leftSideMenuRuntimeRevision;
    private rightSideMenuRuntimeRevision;
    private leftSideMenuSuppressedToken?;
    private rightSideMenuSuppressedToken?;
    private navigationPersistence?;
    private navigationOptions;
    private browserNavigationAttached;
    private ignoreNextPopState;
    private restoringNavigation;
    private pendingManagedBackToken?;
    private pendingManagedBackFallback?;
    private pendingManagedBackTimer?;
    private detachCapacitorBackHandler?;
    private readonly boundPopStateHandler;
    private readonly boundPersistenceFlushHandler;
    private readonly boundVisibilityHandler;
    private static defaultParams;
    constructor(params?: AppParams, options?: AppOptions);
    static setDefault(value: AppParams, reset?: boolean): void;
    get $ref(): string | undefined;
    setParams(params: AppParams): void;
    setOptions(options: Partial<AppOptions>): void;
    get $params(): AppParams;
    get stackRef(): Ref<AppStackItem[], AppStackItem[]>;
    get activeItemRef(): Ref<AppStackItem | undefined, AppStackItem | undefined>;
    get $supportsBrowserHistory(): boolean;
    get $navigationEnabled(): boolean;
    private syncStackRefs;
    private navigationEnabled;
    private supportsBrowserHistory;
    private supportsPersistence;
    private getSideNavOptions;
    private sideNavMenuRef;
    private sideNavOpenRef;
    private sideNavState;
    private setSideNavState;
    private suppressedSideNavToken;
    private setSuppressedSideNavToken;
    private setSideNavSource;
    private setSideNavTouched;
    private isSideNavTouched;
    private isSideNavMobile;
    private isSideNavTemporary;
    private defaultSideNavOpen;
    private setSideNavOpen;
    private shouldRenderSideNav;
    private resolveConfiguredSideNavTarget;
    private resolveContextualRightMenuState;
    private resolveSideNavTarget;
    private applySideNavPresentation;
    private resolveSideNavMenu;
    private refreshSideMenus;
    private closeTemporarySideNavsOnNavigate;
    private clearSideNav;
    private ensureNavigationPersistence;
    private shouldIncludePersistedEntry;
    private createSnapshot;
    private createPersistedEntryState;
    private createBrowserState;
    private serializeSnapshotEntry;
    private shouldRewindBrowserHistoryAfterRestore;
    private rewindBrowserHistorySilently;
    private syncNavigationPersistence;
    syncCurrentNavigationState(options?: {
        replaceHistory?: boolean;
        skipHistory?: boolean;
    }): Promise<void>;
    private syncBrowserHistory;
    private afterStackChanged;
    private buildNavigationTitle;
    private buildNavigationEntry;
    private rebuildStackFromEntries;
    private restoreFromSnapshot;
    private restorePersistedNavigation;
    private onPopState;
    private clearPendingManagedBack;
    private runPendingManagedBackFallback;
    private requestManagedHistoryBack;
    private popCurrentStackItemLocally;
    props(): never[];
    menu(): Promise<Menu | undefined>;
    render(props: any, context: any): VNode | VNode[] | undefined;
    private renderStackContent;
    private wrapStackItemContent;
    private wrapWithFab;
    private getActiveStackItem;
    private resolveFabConfig;
    private resolveFabButtonSource;
    private buildFabButtons;
    private renderFabActions;
    private shouldShowTemporarySideNavToggle;
    private renderTemporarySideNavToggle;
    private renderTemporaryRightNavToggle;
    private triggerComponentShortcut;
    private triggerActiveScreenShortcut;
    private triggerFabButtonShortcut;
    private triggerFabShortcut;
    private onAppKeydown;
    private renderShellRegion;
    private renderShellBar;
    private renderShellBarSection;
    private getShellBarSectionItems;
    private getCompactHeaderActionItems;
    private getShellLayout;
    private getResolvedShellLayout;
    private getShellWidthValue;
    private normalizeCssSize;
    private getShellBarContainerStyle;
    private getShellBarSectionStyle;
    private mainShellStyle;
    private mainShellContentStyle;
    private mainShellOverlayStyle;
    private normalizeShellContent;
    private renderMobileHeaderBrand;
    private renderCompactShellOverflow;
    private resolveMobileShellLocation;
    private mobileShellPriority;
    private shouldHideShellItem;
    private renderCompactHeaderDrawer;
    private normalizeShellItem;
    private renderSideNavDrawer;
    private activateCurrentItem;
    $reload(): Promise<void>;
    $goBackWithFallback(fallback: () => Promise<void> | void): Promise<void>;
    $backBrowserHistorySilently(): boolean;
    private loadApp;
    $getUDFs(objectType: string | string[]): Promise<any[]>;
    $makeUDF(options: any, mode?: ReportMode): Field | undefined;
    $showMenu(menu: Menu | NavigationScreenFactory<Menu>, params?: AppScreenParams, replaceHistory?: boolean): Promise<void>;
    $showLeftMenu(menu: MenuTarget, params?: AppScreenParams): Promise<void>;
    $showRightMenu(menu: MenuTarget, params?: AppScreenParams): Promise<void>;
    $hideLeftMenu(): void;
    $hideRightMenu(): void;
    $clearLeftMenu(): void;
    $clearRightMenu(): void;
    $refreshLeftMenu(): Promise<void>;
    $refreshRightMenu(): Promise<void>;
    $toggleLeftMenu(): Promise<void>;
    $toggleRightMenu(): Promise<void>;
    $showReport(report: Report | NavigationScreenFactory<Report>, params?: AppScreenParams, replace?: boolean): Promise<void>;
    $showCollection(collection: Collection | NavigationScreenFactory<Collection>, params?: AppScreenParams, replace?: boolean): Promise<void>;
    $showTrigger(trigger: Trigger | NavigationScreenFactory<Trigger>, params?: AppScreenParams, replace?: boolean): Promise<void>;
    $showUI(ui: UIBase | NavigationScreenFactory<UIBase>, params?: AppScreenParams, replace?: boolean): Promise<void>;
    $showSelector(selector: Selector, params?: any): Promise<void>;
    $showDialog(dialog: DialogForm, params?: any): Promise<void>;
    $back(): Promise<void>;
    $pop(count?: number, skipHistory?: boolean): Promise<void>;
    private onCancel;
    private onSelectorCancel;
    private onDialogCancel;
    private captureActiveElement;
    private restoreFocus;
    attachEventListeners(): void;
    removeEventListeners(): void;
    private syncShellLayoutBreakpoint;
    private attachShellLayoutBreakpoint;
    private detachShellLayoutBreakpoint;
    private setFooterElement;
    private updateFooterHeight;
    private disconnectFooterObserver;
}
export declare const $APP: (params?: AppParams, options?: AppOptions) => AppMain;
