import { VNode } from "vue";
import { ReportMode, UIBase } from "./base";
import { Master } from "../master";
import { Part, PartParams, PRefs } from "./part";
import { Button, ButtonParams } from "./button";
import { Report } from "./report";
import { Refs } from "./field";
import { OnHandler } from "./lib";
export interface FormParams {
    ref?: string;
    readonly?: boolean;
    invisible?: boolean;
    title?: string;
    subtitle?: string;
    mode?: ReportMode;
    auto?: boolean;
    sub?: boolean;
    hideMode?: boolean;
    saveButton?: ButtonParams;
    cancelButton?: ButtonParams;
    prevButton?: ButtonParams;
    showSaveInReadonly?: boolean;
    elevation?: number;
    maxWidth?: number | string | undefined;
    minWidth?: number | string | undefined;
    maxHeight?: number | string | undefined;
    minHeight?: number | string | undefined;
    width?: number | string | undefined;
    cardClass?: string | string[];
    defaultButtonPosition?: "top" | "bottom" | "both";
    alignContent?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    dense?: boolean | undefined;
    udf?: string | string[];
    justify?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    align?: "center" | "end" | "start" | "stretch" | "baseline" | undefined;
}
export interface FormOptions {
    master?: Master;
    topChildren?: (props: any, context: any) => Array<Part>;
    bottomChildren?: (props: any, context: any) => Array<Part>;
    children?: (props: any, context: any) => Array<Part>;
    buttons?: (props: any, context: any) => Array<Button>;
    bottomButtons?: (props: any, context: any) => Array<Button>;
    leftButtons?: (props: any, context: any) => Array<Button>;
    bottomLeftButtons?: (props: any, context: any) => Array<Button>;
    validate?: (form: Form) => Promise<string | true | undefined | void> | string | true | undefined | void;
    saved?: (form: Form) => Promise<void> | void;
    afterSaved?: (form: Form) => Promise<void> | void;
    onError?: (form: Form, error: any) => Promise<void> | void;
    cancel?: () => Promise<void> | void;
    canCancel?: (form: Form) => Promise<boolean | undefined> | boolean | undefined;
    access?: (form: Form, mode: any) => Promise<boolean> | boolean;
    processUDF?: (form: Form, udfs: any[]) => Promise<any[]>;
    setup?: (form: Form) => void;
    preUDFOptions?: PartParams;
    postUDFOptions?: PartParams;
    on?: (form: Form) => OnHandler;
    removeEventListeners?: (form: Form) => Promise<void> | void;
    attachEventListeners?: (form: Form) => Promise<void> | void;
}
export declare class Form extends UIBase {
    private params;
    private hasAccess;
    private options;
    private childrenInstances;
    private topButtonInstances;
    private bottomButtonInstances;
    private udfData;
    private formRef?;
    private cardRoot;
    private udfLoaded;
    private validationSummary;
    private listenersAttached;
    private shortcutHandler?;
    private static defaultParams;
    constructor(params?: FormParams, options?: FormOptions);
    static setDefault(value: FormParams, reset?: boolean): void;
    get $prefs(): PRefs;
    get $refs(): Refs;
    get $ref(): string | undefined;
    get $readonly(): any;
    get $parentReport(): Report | undefined;
    setParams(params: FormParams): void;
    get $params(): FormParams;
    get $access(): boolean;
    runAccess(): Promise<void>;
    validate(): Promise<string | true | undefined | void>;
    saved(): Promise<void>;
    afterSaved(): Promise<void>;
    cancel(): Promise<void>;
    access(mode: any): Promise<boolean>;
    processUDF(udfs: any[]): Promise<any[]>;
    props(): never[];
    topChildren(props: any, context: any): Array<Part>;
    bottomChildren(props: any, context: any): Array<Part>;
    children(props: any, context: any): Array<Part>;
    buttons(props: any, context: any): Array<Button>;
    bottomButtons(props: any, context: any): Array<Button>;
    leftButtons(props: any, context: any): Array<Button>;
    bottomLeftButtons(props: any, context: any): Array<Button>;
    render(props: any, context: any): VNode | undefined;
    private toCssSize;
    private clampToViewport;
    private cardSizeStyle;
    focusPrimaryInput(): Promise<void>;
    private setCardRoot;
    private focusSpecialFieldTarget;
    private fieldFocusBehavior;
    private findFocusTarget;
    private isVisibleFocusable;
    private waitForFocusFrame;
    private buildTitle;
    private buildSubTitle;
    private buildBody;
    private buildValidationSummary;
    private loadUDFData;
    private prepareBeforeUDFs;
    private prepareAfterUDFs;
    private buildTopActions;
    private buildBottomActions;
    private buildDefaultButtons;
    $save(): Promise<void>;
    $cancel(): Promise<void>;
    $prev(): Promise<void>;
    $handleEscapeShortcut(): Promise<void>;
    $handleSaveShortcut(): Promise<void>;
    private onFormKeydown;
    private isSaveShortcut;
    private canTriggerSaveShortcut;
    private getShortcutButtons;
    private triggerButtonShortcut;
    private shouldIgnoreSaveShortcut;
    private shouldIgnoreEscapeCancel;
    private onSaveClicked;
    private save;
    setup(props: any, context: any): void;
    private onCancelClicked;
    private onPrevClicked;
    private setValidationSummary;
    private clearValidationSummary;
    private collectRequiredFieldSummary;
    private collectFields;
    private isEmptyValue;
    private handleOn;
    attachEventListeners(): void;
    removeEventListeners(): void;
}
export declare const $FM: (params?: FormParams, options?: FormOptions) => Form;
