import { VNode, Ref } from "vue";
import { ReportMode, UIBase } from "./base";
import { Master } from "../master";
import { Form } from './form';
import { Button, ButtonParams } from "./button";
import { OnHandler } from "./lib";
import { PRefs } from "./part";
import { Refs } from "./field";
export type ReportButtonStyle = 'text' | 'outlined' | 'elevated';
export interface ReportParams {
    objectType?: any;
    objectId?: any;
    selected?: any;
    title?: string;
    confirmOnCancel?: boolean;
    hideMode?: boolean;
    cancelButton?: ButtonParams;
    cancelButtonStyle?: ReportButtonStyle;
    nextButton?: ButtonParams;
    nextButtonStyle?: ReportButtonStyle;
    prevButton?: ButtonParams;
    prevButtonStyle?: ReportButtonStyle;
    finishButton?: ButtonParams;
    finishButtonStyle?: ReportButtonStyle;
    sideButtonPosition?: 'left' | 'right';
    sideButtonWidth?: string | number;
    multiple?: boolean;
    setActionButtons?: boolean;
    forms?: number;
    mode?: 'create' | 'edit' | 'display';
    editAfterSave?: boolean;
    verticalAlign?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    horizontalAlign?: "left" | "center" | "right";
    fluid?: boolean;
    alignContent?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    justify?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    align?: "center" | "end" | "start" | "stretch" | "baseline" | undefined;
    printAfterSave?: boolean;
    canPrint?: boolean;
    canExport?: boolean;
    printTemplate?: string;
    exportTemplate?: string;
    exportFilename?: string;
}
export interface ReportOptions {
    master?: Master;
    form?: (props: any, context: any, index: number) => Promise<Form | undefined> | Form | undefined;
    hasForm?: (props: any, context: any, index: number) => Promise<boolean | undefined> | boolean | undefined;
    saved?: (report: Report) => Promise<void> | void;
    cancel?: (report: Report) => Promise<void> | void;
    access?: (report: Report, mode: any) => Promise<boolean> | boolean;
    setup?: (report: Report) => void;
    beforePrint?: (report: Report, mode?: ReportMode) => Promise<any | undefined> | any | undefined;
    printTemplate?: (report: Report, mode?: ReportMode) => Promise<any | undefined> | any | undefined;
    beforeExport?: (report: Report, mode?: ReportMode) => Promise<any | undefined> | any | undefined;
    exportTemplate?: (report: Report, mode?: ReportMode) => Promise<ExportTemplateInfo | undefined> | ExportTemplateInfo | undefined;
    on?: (report: Report) => OnHandler;
    loaded?: (report: Report) => void;
    hasNextForm?: (report: Report, index: number) => Promise<boolean | undefined> | boolean | undefined;
    hasPrevForm?: (report: Report, index: number) => Promise<boolean | undefined> | boolean | undefined;
    removeEventListeners?: (report: Report) => Promise<void> | void;
    attachEventListeners?: (report: Report) => Promise<void> | void;
    title?: (report: Report, index?: number) => string;
    sideButtons?: (props: any, context: any, report: Report) => Array<Button> | undefined;
}
export interface ExportTemplateInfo {
    template?: any;
    filename?: string;
}
export declare class Report extends UIBase {
    private params;
    private hasAccess;
    private hasPrintAccess;
    private hasExportAccess;
    private options;
    private loaded;
    private topButtonInstances;
    private bottomButtonInstances;
    private sideButtonInstances;
    private currentForm;
    private currentIndex;
    private currentFormRenderKey;
    private currentStepRefState;
    private hasNext;
    private hasPrev;
    private listenersAttached;
    private lastProps;
    private lastContext;
    private cleanSnapshot;
    private resolvedFormCount;
    private shortcutHandler?;
    private compactSideActions;
    private sideActionMediaQuery?;
    private sideActionMediaHandler?;
    private static defaultParams;
    constructor(params?: ReportParams, options?: ReportOptions);
    static setDefault(value: ReportParams, reset?: boolean): void;
    get $parentReport(): Report | undefined;
    get $prefs(): PRefs;
    get $currentForm(): Form | undefined;
    get $refs(): Refs;
    get objectType(): any;
    get objectId(): any;
    set objectType(v: any);
    set objectId(v: any);
    setParams(params: ReportParams): void;
    get $params(): ReportParams;
    get $access(): boolean;
    get currentStepRef(): Ref<number>;
    get totalStepsRef(): Ref<number>;
    private syncStepRefs;
    private initialize;
    private runAccess;
    loadObject(): Promise<void>;
    saved(): Promise<void>;
    cancel(): Promise<void>;
    access(mode: any): Promise<boolean>;
    form(props: any, context: any, index: number): Promise<Form | undefined>;
    hasForm(props: any, context: any, index: number): Promise<boolean>;
    hasPrevForm(props: any, context: any, index: number): Promise<boolean | undefined>;
    hasNextForm(props: any, context: any, index: number): Promise<boolean | undefined>;
    private resolveFormCount;
    props(): never[];
    render(props: any, context: any): VNode | undefined;
    private prepareForm;
    private buildTitle;
    private buildBody;
    private buildTopActions;
    private buildBottomActions;
    private buildSideButtons;
    private buildDesktopSideActions;
    private buildMobileSideActions;
    private wrapWithSideButtons;
    private buildProgressHeader;
    private buildDefaultButtons;
    getAdditionalButtons(): Button[];
    private save;
    private oncancel;
    private onprev;
    private focusCurrentForm;
    private applyStepSubtitle;
    private progressLabel;
    private snapshotMasterData;
    private captureCleanState;
    private hasUnsavedChanges;
    forceCancel(): Promise<void>;
    forceSave(): Promise<void>;
    private triggerButtonShortcut;
    private onReportKeydown;
    setup(props: any, context: any): void;
    print(): Promise<void>;
    beforePrint(): Promise<any | undefined>;
    printTemplate(): Promise<any | undefined>;
    private printAction;
    export(): Promise<void>;
    beforeExport(): Promise<any | undefined>;
    exportTemplate(): Promise<ExportTemplateInfo | undefined>;
    private exportAction;
    private syncSideActionBreakpoint;
    private toCssSize;
    private clampToViewport;
    private attachSideActionBreakpoint;
    private detachSideActionBreakpoint;
    private handleOn;
    attachEventListeners(): void;
    removeEventListeners(): void;
}
export declare const $RP: (params?: ReportParams, options?: ReportOptions) => Report;
