import { VNode } from "vue";
import { ReportMode, UIBase } from "./base";
import { Master } from "../master";
import { Form } from './form';
import { Button, ButtonParams } from "./button";
import { OnHandler } from "./lib";
export interface ReportParams {
    objectType?: any;
    objectId?: any;
    selected?: any;
    title?: string;
    hideMode?: boolean;
    cancelButton?: ButtonParams;
    multiple?: boolean;
    setActionButtons?: boolean;
    forms?: number;
    mode?: 'create' | 'edit' | 'display';
    editAfterSave?: boolean;
    verticalAlign?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    horizontalAlign?: "left" | "center" | "right";
    fluid?: boolean;
    alignContent?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    justify?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    align?: "center" | "end" | "start" | "stretch" | "baseline" | undefined;
    printAfterSave?: boolean;
    canPrint?: boolean;
    canExport?: boolean;
    printTemplate?: string;
    exportTemplate?: string;
    exportFilename?: string;
}
export interface ReportOptions {
    master?: Master;
    form?: (props: any, context: any, index: number) => Promise<Form | undefined> | Form | undefined;
    hasForm?: (props: any, context: any, index: number) => Promise<boolean | undefined> | boolean | undefined;
    saved?: () => Promise<void> | void;
    cancel?: () => Promise<void> | void;
    access?: (report: Report) => Promise<boolean> | boolean;
    setup?: (report: Report) => void;
    beforePrint?: (report: Report, mode?: ReportMode) => Promise<any | undefined> | any | undefined;
    printTemplate?: (report: Report, mode?: ReportMode) => Promise<any | undefined> | any | undefined;
    beforeExport?: (report: Report, mode?: ReportMode) => Promise<any | undefined> | any | undefined;
    exportTemplate?: (report: Report, mode?: ReportMode) => Promise<ExportTemplateInfo | undefined> | ExportTemplateInfo | undefined;
    on?: (report: Report) => OnHandler;
}
export interface ExportTemplateInfo {
    template?: any;
    filename?: string;
}
export declare class Report extends UIBase {
    private params;
    private hasAccess;
    private options;
    private loaded;
    private topButtonInstances;
    private bottomButtonInstances;
    private currentForm;
    private currentIndex;
    private hasNext;
    private hasPrev;
    constructor(params?: ReportParams, options?: ReportOptions);
    get $parentReport(): Report | undefined;
    get objectType(): any;
    get objectId(): any;
    set objectType(v: any);
    set objectId(v: any);
    setParams(params: ReportParams): void;
    get $params(): ReportParams;
    get $access(): boolean;
    private initialize;
    private runAccess;
    loadObject(): Promise<void>;
    saved(): Promise<void>;
    cancel(): Promise<void>;
    access(): Promise<boolean>;
    form(props: any, context: any, index: number): Promise<Form | undefined>;
    hasForm(props: any, context: any, index: number): Promise<boolean>;
    props(): never[];
    render(props: any, context: any): VNode | undefined;
    private prepareForm;
    private buildTitle;
    private buildBody;
    private buildTopActions;
    private buildBottomActions;
    private buildDefaultButtons;
    getAdditionalButtons(): Button[];
    private save;
    private oncancel;
    forceCancel(): Promise<void>;
    setup(props: any, context: any): void;
    print(): Promise<void>;
    beforePrint(): Promise<any | undefined>;
    printTemplate(): Promise<any | undefined>;
    private printAction;
    export(): Promise<void>;
    beforeExport(): Promise<any | undefined>;
    exportTemplate(): Promise<ExportTemplateInfo | undefined>;
    private exportAction;
    private handleOn;
}
export declare const $RP: (params?: ReportParams, options?: ReportOptions) => Report;
