import { VNode } from "vue";
import { UIBase } from "./base";
import { ButtonParams } from "./button";
import { OnHandler } from "./lib";
import { Part, PRefs } from "./part";
import { Field, Refs } from "./field";
export interface TriggerParams {
    ref?: string;
    invisible?: boolean;
    title?: string;
    subtitle?: string;
    mode?: 'create' | 'edit' | 'display';
    cancelButton?: ButtonParams;
    removeButton?: ButtonParams;
    viewButton?: ButtonParams;
    editButton?: ButtonParams;
    elevation?: number;
    maxWidth?: number | string | undefined;
    minWidth?: number | string | undefined;
    width?: number | string | undefined;
    headers?: any[];
    tableHeight?: number | string;
    queryFields?: any[];
    selectFields?: any;
    objectType?: any;
    idField?: any;
    multiple?: boolean;
    defaultButtonPosition?: "top" | "bottom" | "both";
    verticalAlign?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    horizontalAlign?: "left" | "center" | "right";
    fluid?: boolean;
    alignContent?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    dense?: boolean | undefined;
    justify?: "center" | "end" | "start" | "space-around" | "space-between" | "space-evenly" | "stretch" | undefined;
    align?: "center" | "end" | "start" | "stretch" | "baseline" | undefined;
    query?: any;
}
export interface TriggerOptions {
    searchFields?: (tigger: Trigger, mode?: 'create' | 'edit' | 'display') => any | Promise<any>;
    cancel?: () => Promise<void>;
    access?: (tigger: Trigger, mode?: 'create' | 'edit' | 'display') => Promise<boolean>;
    removeAccess?: (trigger: Trigger) => Promise<boolean>;
    canRemove?: (item: any, trigger: Trigger) => Promise<boolean>;
    headers?: (trigger: Trigger) => Promise<any[]>;
    load?: (searchText: string, trigger: Trigger, options: any) => Promise<any>;
    remove?: (item: any, trigger: Trigger) => Promise<boolean | string>;
    query?: (search: string, trigger: Trigger, mode?: 'create' | 'edit' | 'display', searchFields?: any[]) => Promise<any>;
    setup?: (trigger: Trigger) => void;
    on?: (trigger: Trigger) => OnHandler;
    format?: (trigger: Trigger, items: any[]) => Promise<any[] | undefined> | any[] | undefined;
    topChildren?: (props: any, context: any) => Array<Part | Field>;
    bottomChildren?: (props: any, context: any) => Array<Part | Field>;
    processQuery?: (query: any, trigger: Trigger, mode?: 'create' | 'edit' | 'display', search?: string, searchFields?: any[]) => Promise<any>;
}
export interface ServerTableOptions {
    page: number;
    itemsPerPage: any;
    total: number;
    selectedFilterFields?: any[];
}
export declare class Trigger extends UIBase {
    private params;
    private hasAccess;
    private hasRemoveAccess;
    private options;
    private topButtonInstances;
    private bottomButtonInstances;
    private items;
    private selected;
    private searchText;
    private selectedSearchFields;
    private childrenInstances;
    private searchFieldItems;
    private searchFieldData;
    private currentSearchText;
    private computedHeaders;
    private tableOptions;
    private loaded;
    private loading;
    constructor(params?: TriggerParams, options?: TriggerOptions);
    get $refs(): Refs;
    get $prefs(): PRefs;
    get $ref(): string | undefined;
    setParams(params: TriggerParams): void;
    get $params(): TriggerParams;
    get $access(): boolean;
    private runAccess;
    validate(): Promise<string | true | undefined | void>;
    saved(): Promise<void>;
    cancel(): Promise<void>;
    access(mode?: any): Promise<boolean>;
    removeAccess(): Promise<boolean>;
    canRemove(item: any): Promise<boolean>;
    remove(item: any): Promise<boolean | string>;
    load(searchText: string, options: ServerTableOptions): Promise<any>;
    query(search: string, mode?: 'create' | 'edit' | 'display'): Promise<any>;
    props(): never[];
    onTableOptionsChanged(options: any): Promise<void>;
    private loadItems;
    render(props: any, context: any): VNode | undefined;
    private buildTitle;
    private buildSubTitle;
    private buildBody;
    private buildSearchBar;
    private buildFilterBar;
    private buildResultTable;
    headers(): Promise<any[]>;
    searchFields(): Promise<any>;
    private initialize;
    private buildTopActions;
    private buildBottomActions;
    private buildDefaultButtons;
    topChildren(props: any, context: any): Array<Part | Field>;
    bottomChildren(props: any, context: any): Array<Part | Field>;
    private onProcessMultiple;
    private onCancelClicked;
    private onRemoveClicked;
    private onSearchClicked;
    private onTableItemClicked;
    private onSelectionChanged;
    setup(props: any, context: any): void;
    private handleOn;
}
export declare const $TG: (params?: TriggerParams, options?: TriggerOptions) => Trigger;
