// Generated by vuetify-ext create dashboard
import { watch } from 'vue';
import { $DB, $DLW, $DMW, $MI, Dialogs, type NavigationEntry } from 'vuetify-extended';
// vuetify-ext:dashboard-imports
import { $DCHW } from 'vuetify-extended';
import { themeModeRef } from '../../bootstrap/theme';

export function createOpsDashboard() {
  return (_entry?: NavigationEntry) => {
    const dashboard = $DB(
      {
        title: { key: "pages.ops.dashboard.title", fallback: "Operations Dashboard" },
        subtitle: { key: "pages.ops.dashboard.subtitle", fallback: "Starter dashboard generated by vuetify-ext." },
        fluid: true,
        theme: themeModeRef.value,
      },
      {
        menuItems: async () => [
          $MI(
            {
              action: 'function',
              text: { key: "pages.ops.dashboard.menu.action.text", fallback: "Dashboard Action" },
              subText: { key: "pages.ops.dashboard.menu.action.subText", fallback: "Starter dashboard menu item." },
              icon: 'mdi-dots-horizontal-circle-outline',
              color: 'primary',
            },
            {
              callback: async () => {
                Dialogs.$success({ key: "pages.ops.dashboard.menu.action.success", fallback: "Dashboard action clicked." });
              },
            },
          ),
        ],
        topChildren: () => [
          // vuetify-ext:dashboard-top-widgets
          $DMW({
            title: { key: "pages.ops.dashboard.widgets.activeUsers.title", fallback: "Active Users" },
            value: 128,
            caption: 'Last 24 hours',
            icon: 'mdi-account-group-outline',
            cols: 12,
            sm: 6,
            lg: 3,
          }),
          $DMW({
            title: { key: "pages.ops.dashboard.widgets.revenue.title", fallback: "Revenue" },
            value: '$12,450',
            caption: 'Starter metric',
            icon: 'mdi-cash-multiple',
            cols: 12,
            sm: 6,
            lg: 3,
          }),
        ],
        children: () => [
          // vuetify-ext:dashboard-widgets
        // vuetify-ext:dashboard-widget:main:chart:revenue-trend
        $DCHW({
          title: { key: "pages.ops.dashboard.widgets.revenue-trend.title", fallback: "Revenue Trend" },
          cols: 12,
          lg: 4,
          chartType: 'bar',
          chartHeight: 220,
          items: [
            { label: 'Jan', value: 12 },
            { label: 'Feb', value: 18 },
            { label: 'Mar', value: 9 },
          ],
        }),
          $DLW({
            title: { key: "pages.ops.dashboard.widgets.recentActivity.title", fallback: "Recent Activity" },
            cols: 12,
            lg: 6,
            items: [
              { title: 'Replace this widget', subtitle: 'Use "vuetify-ext create dashboard-widget" to add more cards.' },
              { title: 'Connect data', subtitle: 'Swap starter items for real API-backed values.' },
            ],
          }),
        ],
        bottomChildren: () => [
          // vuetify-ext:dashboard-bottom-widgets
        ],
      },
    );

    watch(themeModeRef, (mode) => {
      dashboard.setParams({ theme: mode });
      dashboard.forceRender();
    });

    return dashboard;
  };
}
