// Generated by vuetify-ext bootstrap app
import { $FD, $FM, $PT } from 'vuetify-extended';

export function createHomeForm() {
  return $FM(
    {
      title: { key: "pages.home.form.title", fallback: "Welcome" },
      mode: 'display',
      width: 860,
    },
    {
      children: () => [
        $PT(
          { cols: 12, dense: true },
          {
            children: () => [
              $FD({
                type: 'label',
                label: { key: "pages.home.form.intro.location", fallback: "This starter page is defined in src/pages/home/index." },
                cols: 12,
              }),
              $FD({
                type: 'label',
                label: { key: "pages.home.form.intro.pages", fallback: "Add future reports, triggers, collections, and dashboards under src/pages/<page-name>/." },
                cols: 12,
              }),
              $FD({
                type: 'label',
                label: { key: "pages.home.form.intro.structure", fallback: "Split larger pages into form.ts, report.ts, trigger.ts, collection.ts, fields.ts, or parts.ts as needed." },
                cols: 12,
              }),
            ],
          },
        ),
      ],
    },
  );
}
