// Generated by vuetify-ext bootstrap app
import { $MI, $MN } from 'vuetify-extended';
// vuetify-ext:menu-imports
import { createOpsDashboard } from '../pages/ops';
import { createOrdersCollection } from '../pages/orders';
import { createPeopleReport } from '../pages/people';
import { createFinderTrigger } from '../pages/finder';
import { createSettingsMenu } from "./settings";
import { createHomeReport } from '../pages/home';

export function createMainMenu() {
  return $MN(
    {
      title: { key: "bootstrap.menu.title", fallback: "Workspace" },
      cols: 12,
      width: 380,
    },
    {
      children: async () => [
        // vuetify-ext:menu-items
        // vuetify-ext:menu-item:dashboard:ops
        $MI(
          {
            action: 'ui',
            mode: "display",
            text: { key: "pages.ops.menu.dashboard.display.text", fallback: "Operations" },
            subText: { key: "pages.ops.menu.dashboard.display.subText", fallback: "Open the operations dashboard." },
            icon: "mdi-view-dashboard-outline",
            color: "secondary",
          },
          {
            ui: async () => createOpsDashboard(),
            navigation: () => ({
              key: "pages.ops.ui",
              persist: false,
            }),
          },
        ),
        // vuetify-ext:menu-item:collection:orders
        $MI(
          {
            action: 'collection',
            mode: "edit",
            text: { key: "pages.orders.menu.collection.edit.text", fallback: "Orders" },
            subText: { key: "pages.orders.menu.collection.edit.subText", fallback: "Open the orders workflow." },
            icon: "mdi-view-list",
            color: "deep-orange",
          },
          {
            collection: async (_menuItem, mode) => createOrdersCollection(mode || "edit"),
            navigation: () => ({
              key: "pages.orders.collection.edit",
              persist: false,
            }),
          },
        ),
        // vuetify-ext:menu-item:report:people
        $MI(
          {
            action: 'report',
            mode: "display",
            text: { key: "pages.people.menu.report.display.text", fallback: "People" },
            subText: { key: "pages.people.menu.report.display.subText", fallback: "Open the people report." },
            icon: "mdi-account-group",
            color: "primary",
          },
          {
            report: async (_menuItem, mode) => createPeopleReport(mode || "display"),
            navigation: () => ({
              key: "pages.people.report.display",
              persist: false,
            }),
          },
        ),
        // vuetify-ext:menu-item:trigger:finder
        $MI(
          {
            action: 'trigger',
            mode: "edit",
            text: { key: "pages.finder.menu.trigger.edit.text", fallback: "Finder" },
            subText: { key: "pages.finder.menu.trigger.edit.subText", fallback: "Search and act on records." },
            icon: "mdi-table-search",
            color: "brown",
          },
          {
            trigger: async (_menuItem, mode) => createFinderTrigger(mode || "edit"),
            navigation: () => ({
              key: "pages.finder.trigger.edit",
              persist: false,
            }),
          },
        ),
        // vuetify-ext:sub-menu:settings
        $MI(
          {
            action: 'menu',
            text: { key: "menus.settings.entry.text", fallback: "Settings" },
            subText: { key: "menus.settings.entry.subText", fallback: "Open workspace settings tools." },
            icon: "mdi-cog-outline",
            color: "secondary",
          },
          {
            menu: async () => createSettingsMenu(),
          },
        ),
        $MI(
          {
            action: 'report',
            mode: 'display',
            text: { key: "pages.home.menu.report.display.text", fallback: "Home" },
            subText: { key: "pages.home.menu.report.display.subText", fallback: "Starter page entry from src/pages/home." },
            icon: 'mdi-home-outline',
            color: 'primary',
          },
          {
            report: async (_menuItem, mode) => createHomeReport(mode || 'display'),
            navigation: () => ({
              key: 'pages.home.report.display',
              persist: true,
            }),
          },
        ),
      ],
    },
  );
}
