// Generated by vuetify-ext create sub-menu
import { $MN, $MI } from 'vuetify-extended';
// vuetify-ext:menu-imports
import { createPeopleReport } from '../pages/people';
import { createPreferencesMenu } from './preferences';

export function createSettingsMenu() {
  return $MN(
    {
      title: { key: "menus.settings.title", fallback: "Settings" },
      cols: 12,
      width: 380,
    },
    {
      children: async () => [
        // vuetify-ext:menu-items
        $MI(
          {
            action: 'menu',
            text: { key: 'menus.preferences.entry.text', fallback: 'Preferences' },
            subText: { key: 'menus.preferences.entry.subText', fallback: 'Open a nested submenu example.' },
            icon: 'mdi-tune',
            color: 'secondary',
          },
          {
            menu: async () => createPreferencesMenu(),
          },
        ),
        // vuetify-ext:menu-item:report:people
        $MI(
          {
            action: 'report',
            mode: "display",
            text: { key: "pages.people.menu.report.display.text", fallback: "People Settings" },
            subText: { key: "pages.people.menu.report.display.subText", fallback: "Open the People report." },
            icon: "mdi-file-document-outline",
            color: "primary",
          },
          {
            report: async (_menuItem, mode) => createPeopleReport(mode || "display"),
            navigation: () => ({
              key: "pages.people.report.display",
              persist: false,
            }),
          },
        ),
      ],
    },
  );
}
