// Generated by vuetify-ext create sub-menu
import { $MN } from 'vuetify-extended';
// vuetify-ext:menu-imports
import { createPeopleReport } from '../pages/people';
import { $MI } from 'vuetify-extended';

export function createSettingsMenu() {
  return $MN(
    {
      title: "Settings",
      cols: 12,
      width: 380,
    },
    {
      children: async () => [
        // vuetify-ext:menu-items
        // vuetify-ext:menu-item:report:people
        $MI(
          {
            action: 'report',
            mode: "display",
            text: "People Settings",
            subText: "Open the People report.",
            icon: "mdi-file-document-outline",
            color: "primary",
          },
          {
            report: async (_menuItem, mode) => createPeopleReport(mode || "display"),
            navigation: () => ({
              key: "pages.people.report.display",
              persist: false,
            }),
          },
        ),
      ],
    },
  );
}
