// Generated by vuetify-ext bootstrap app
import type { VuetifyExtendedApiConfig } from 'vuetify-extended';

export function createApiConfig(): VuetifyExtendedApiConfig | undefined {
  return undefined;
}
