// Generated by vuetify-ext bootstrap app
import { AppTitleBlock, UserArea, EnvironmentTag, StatusBadge, type AppMain, type AppShellContent, $BN, $SIA } from 'vuetify-extended';
import { Dialogs } from 'vuetify-extended';
import { toggleLocale, translate } from '../i18n';
import { getThemeMode, toggleThemeMode } from './theme';
// vuetify-ext:header-imports

export function buildHeaderStart(app: AppMain): AppShellContent[] {
  return [
    // vuetify-ext:header-start
    new AppTitleBlock({
      title: app.$params.title || { key: "bootstrap.header.title", fallback: "My Workspace" },
      subtitle: { key: "bootstrap.header.subtitle", fallback: "Built with vuetify-extended" },
      overline: { key: "bootstrap.header.overline", fallback: "Workspace" },
      icon: 'mdi-view-dashboard-outline',
      color: 'primary',
    }),
  ];
}

export function buildHeaderCenter(_app: AppMain): AppShellContent[] {
  return [
    // vuetify-ext:header-center
    new EnvironmentTag({
      text: { key: "bootstrap.header.environment", fallback: "Starter" },
      color: 'info',
      variant: 'outlined',
    }),
  ];
}

export function buildHeaderEnd(_app: AppMain): AppShellContent[] {
  const themeToggleButton = () => $BN(
    {
      icon: getThemeMode() === 'dark' ? 'mdi-weather-sunny' : 'mdi-weather-night',
      color: 'primary',
      text: () => getThemeMode() === 'dark'
        ? (translate('bootstrap.header.end.user.action.theme.light') || 'Switch to Light Mode')
        : (translate('bootstrap.header.end.user.action.theme.dark') || 'Switch to Dark Mode'),
      tooltip: () => getThemeMode() === 'dark'
        ? (translate('bootstrap.header.end.user.action.theme.light') || 'Switch to Light Mode')
        : (translate('bootstrap.header.end.user.action.theme.dark') || 'Switch to Dark Mode'),
    },
    {
      onClicked: () => {
        const nextMode = toggleThemeMode();
        Dialogs.$success({
          key: nextMode === 'dark'
            ? 'bootstrap.header.end.user.action.theme.changed.dark'
            : 'bootstrap.header.end.user.action.theme.changed.light',
          fallback: nextMode === 'dark' ? 'Dark mode enabled.' : 'Light mode enabled.',
        });
      },
    },
  );

  const languageToggleButton = () => $BN(
    {
      icon: 'mdi-translate',
      color: 'secondary',
      text: { key: 'bootstrap.header.end.user.action.language', fallback: 'Switch Language' },
      tooltip: { key: 'bootstrap.header.end.user.action.language', fallback: 'Switch Language' },
    },
    {
      onClicked: () => {
        toggleLocale();
        Dialogs.$success({ key: 'bootstrap.header.end.user.action.language.changed', fallback: 'Language switched.' });
      },
    },
  );

  return [
    // vuetify-ext:header-end
    // vuetify-ext:header-item:end:user:workspace-user
    new UserArea({
      name: { key: "bootstrap.header.end.user.name", fallback: "Workspace User" },
      subtitle: { key: "bootstrap.header.end.user.subtitle", fallback: "CLI Demo User" },
      email: { key: "bootstrap.header.end.user.email", fallback: "user@example.com" },
      avatarColor: "primary",
    }, {
      buttons: async () => [
        themeToggleButton(),
        languageToggleButton(),
      ],
    }),
    // vuetify-ext:header-item:end:action:toggle-language
    $SIA(
      {
        icon: "mdi-translate",
        title: { key: "bootstrap.header.end.action.title", fallback: "Toggle Language" },
        color: "secondary",
      },
      {
        onClicked: () => {
          toggleLocale();
          Dialogs.$success({ key: "bootstrap.header.end.action.changed", fallback: "Language switched." });
        },
      },
    ),
    new StatusBadge({
      text: { key: "bootstrap.header.status", fallback: "Ready" },
      icon: 'mdi-check-circle-outline',
      color: 'success',
      variant: 'tonal',
    }),
  ];
}
