// Generated by vuetify-ext bootstrap app
import { $MI, $MN, AppMain, createVuetifyExtendedApp, Dialogs, type VuetifyExtendedAppFactoryOptions } from 'vuetify-extended';
import { createApiConfig } from '../api';
import { demoI18n, toggleLocale, translate } from '../i18n';
import { createMainMenu } from '../menu';
import { registerDemoScreens } from '../navigation';
import { createHomeReport } from '../pages/home';
import { buildHeaderCenter, buildHeaderEnd, buildHeaderStart } from './header';
import { buildFooterCenter, buildFooterEnd, buildFooterStart } from './footer';
import { getThemeMode, toggleThemeMode } from './theme';

export interface InitializeBootstrapOptions {
  bootstrap?: Partial<VuetifyExtendedAppFactoryOptions>;
}

function createShellToolsMenu() {
  return $MN(
    {
      title: { key: 'bootstrap.sideNav.tools.title', fallback: 'Workspace Tools' },
      width: 320,
    },
    {
      children: async () => [
        $MI(
          {
            action: 'function',
            text: { key: 'bootstrap.sideNav.tools.theme.text', fallback: 'Toggle Theme' },
            subText: () => getThemeMode() === 'dark'
              ? (translate('bootstrap.header.end.user.action.theme.light') || 'Switch to Light Mode')
              : (translate('bootstrap.header.end.user.action.theme.dark') || 'Switch to Dark Mode'),
            icon: getThemeMode() === 'dark' ? 'mdi-weather-sunny' : 'mdi-weather-night',
            color: 'primary',
          },
          {
            callback: async () => {
              const nextMode = toggleThemeMode();
              Dialogs.$success({
                key: nextMode === 'dark'
                  ? 'bootstrap.header.end.user.action.theme.changed.dark'
                  : 'bootstrap.header.end.user.action.theme.changed.light',
                fallback: nextMode === 'dark' ? 'Dark mode enabled.' : 'Light mode enabled.',
              });
            },
          },
        ),
        $MI(
          {
            action: 'function',
            text: { key: 'bootstrap.sideNav.tools.language.text', fallback: 'Toggle Language' },
            subText: { key: 'bootstrap.sideNav.tools.language.subText', fallback: 'Switch the demo locale instantly.' },
            icon: 'mdi-translate',
            color: 'secondary',
          },
          {
            callback: async () => {
              toggleLocale();
              Dialogs.$success({ key: 'bootstrap.header.end.user.action.language.changed', fallback: 'Language switched.' });
            },
          },
        ),
      ],
    },
  );
}

function createRootMenu() {
  return $MN(
    {
      ref: 'root-menu',
      title: { key: 'bootstrap.rootMenu.title', fallback: 'Workspace' },
      hideTitle: true,
    },
    {
      children: async () => [
        $MI(
          {
            action: 'report',
            mode: 'display',
            text: { key: 'pages.home.menu.report.display.text', fallback: 'Home' },
            subText: { key: 'pages.home.menu.report.display.subText', fallback: 'Starter page entry from src/pages/home.' },
            icon: 'mdi-home-outline',
            color: 'primary',
          },
          {
            report: async (_menuItem, mode) => createHomeReport(mode || 'display'),
            navigation: () => ({
              key: 'pages.home.report.display',
              persist: true,
            }),
          },
        ),
      ],
    },
  );
}

export function createMainApp(): AppMain {
  return new AppMain(
    {
      ref: 'main-app',
      title: { key: "bootstrap.app.title", fallback: "My Workspace" },
      showHeader: true,
      showFooter: true,
      showFab: false,
    },
    {
      menu: async () => createRootMenu(),
      leftNav: async () => createMainMenu(),
      rightNav: async () => createShellToolsMenu(),
      leftNavOptions: {
        enabled: true,
        mode: 'temporary',
        width: 320,
        open: true,
      },
      rightNavOptions: {
        enabled: true,
        mode: 'temporary',
        width: 320,
        open: false,
      },
      headerStart: buildHeaderStart,
      headerCenter: buildHeaderCenter,
      headerEnd: buildHeaderEnd,
      footerStart: buildFooterStart,
      footerCenter: buildFooterCenter,
      footerEnd: buildFooterEnd,
    },
  );
}

export function initializeBootstrap(options: InitializeBootstrapOptions = {}) {
  const api = createApiConfig();
  registerDemoScreens();

  return createVuetifyExtendedApp({
    requireApi: false,
    ...(api ? { api } : {}),
    i18n: demoI18n,
    navigation: {
      enabled: true,
      history: false,
      persist: true,
      restoreOnLoad: true,
      storageKey: 'vuetify-extended-cli-demo-v2-navigation',
    },
    app: createMainApp(),
    dialogs: {
      progressSize: 96,
      progressWidth: 10,
      successTimeout: 2400,
      warningTimeout: 3200,
      errorTimeout: 4200,
    },
    notifications: {
      location: 'top-right',
      maxVisible: 4,
      defaultTimeout: 3600,
    },
    ...(options.bootstrap || {}),
  });
}
