// Generated by vuetify-ext bootstrap app
import { $MI, $MN, AppMain, AppManager, createVuetifyExtendedApp, Dialogs, type ReportMode, type TriggerMode, type VuetifyExtendedAppFactoryOptions } from 'vuetify-extended';
import { createApiConfig } from '../api';
import { demoI18n, toggleLocale, translate } from '../i18n';
import { createMainMenu } from '../menu';
import { registerDemoScreens } from '../navigation';
import { createHomeReport } from '../pages/home';
import { createPeopleReport } from '../pages/people';
import { createFinderTrigger } from '../pages/finder';
import { createOrdersCollection } from '../pages/orders';
import { createOpsDashboard } from '../pages/ops';
import { buildHeaderCenter, buildHeaderEnd, buildHeaderStart } from './header';
import { buildFooterCenter, buildFooterEnd, buildFooterStart } from './footer';
import { getThemeMode, toggleThemeMode } from './theme';

export interface InitializeBootstrapOptions {
  bootstrap?: Partial<VuetifyExtendedAppFactoryOptions>;
}

type DemoDeepLinkScreen = 'home' | 'people' | 'finder' | 'orders' | 'ops';
type DemoDeepLinkMode = 'create' | 'edit' | 'display';

interface DemoDeepLinkIntent {
  screen: DemoDeepLinkScreen;
  mode: DemoDeepLinkMode;
}

const DEMO_LIFECYCLE_REF = 'cli-demo-v2:lifecycle';
let pendingDeepLinkIntent: DemoDeepLinkIntent | undefined;

function resolveDemoDeepLinkMode(value: string | null | undefined, fallback: DemoDeepLinkMode): DemoDeepLinkMode {
  if (value === 'create' || value === 'edit' || value === 'display') {
    return value;
  }

  return fallback;
}

function readDemoDeepLinkIntent(): DemoDeepLinkIntent | undefined {
  if (typeof window === 'undefined') {
    return undefined;
  }

  const params = new URLSearchParams(window.location.search);
  const screen = params.get('demoScreen');
  if (screen !== 'home' && screen !== 'people' && screen !== 'finder' && screen !== 'orders' && screen !== 'ops') {
    return undefined;
  }

  const fallbackMode: DemoDeepLinkMode = screen === 'finder' || screen === 'orders' ? 'edit' : 'display';

  return {
    screen,
    mode: resolveDemoDeepLinkMode(params.get('demoMode'), fallbackMode),
  };
}

async function executeDemoDeepLink(intent: DemoDeepLinkIntent) {
  if (intent.screen === 'home') {
    await AppManager.showReport(createHomeReport(intent.mode as ReportMode), {
      navigation: {
        key: 'pages.home.report.display',
        persist: true,
      },
    }, true);
    return;
  }

  if (intent.screen === 'people') {
    await AppManager.showReport(createPeopleReport(intent.mode as ReportMode), {
      navigation: {
        key: 'pages.people.report.display',
        persist: false,
      },
    }, true);
    return;
  }

  if (intent.screen === 'finder') {
    await AppManager.showTrigger(createFinderTrigger(intent.mode as TriggerMode), {
      navigation: {
        key: 'pages.finder.trigger.edit',
        persist: false,
      },
    }, true);
    return;
  }

  if (intent.screen === 'orders') {
    await AppManager.showCollection(createOrdersCollection(intent.mode as ReportMode), {
      navigation: {
        key: 'pages.orders.collection.edit',
        persist: false,
      },
    }, true);
    return;
  }

  await AppManager.showUI(createOpsDashboard(), {
    navigation: {
      key: 'pages.ops.ui',
      persist: false,
    },
  }, true);
}

function registerDemoLifecycleHandlers() {
  AppManager.clearListeners(DEMO_LIFECYCLE_REF);

  AppManager.on('beforeLoad', () => {
    console.info('[vuetify-extended demo] AppManager beforeLoad fired');
  }, DEMO_LIFECYCLE_REF);

  AppManager.on('loaded', () => {
    console.info('[vuetify-extended demo] AppManager loaded fired');
  }, DEMO_LIFECYCLE_REF);

  AppManager.on('ready', async () => {
    console.info('[vuetify-extended demo] AppManager ready fired');

    if (pendingDeepLinkIntent) {
      const deepLink = pendingDeepLinkIntent;
      pendingDeepLinkIntent = undefined;
      await executeDemoDeepLink(deepLink);
      Dialogs.$success({
        key: 'bootstrap.lifecycle.deepLink.executed',
        fallback: `Lifecycle demo deep link executed for "${deepLink.screen}".`,
      });
      return;
    }

    Dialogs.$success({
      key: 'bootstrap.lifecycle.ready',
      fallback: 'Lifecycle demo: app ready.',
    });
  }, DEMO_LIFECYCLE_REF);
}

function createShellToolsMenu() {
  return $MN(
    {
      title: { key: 'bootstrap.sideNav.tools.title', fallback: 'Workspace Tools' },
      width: 320,
    },
    {
      children: async () => [
        $MI(
          {
            action: 'function',
            text: { key: 'bootstrap.sideNav.tools.theme.text', fallback: 'Toggle Theme' },
            subText: () => getThemeMode() === 'dark'
              ? (translate('bootstrap.header.end.user.action.theme.light') || 'Switch to Light Mode')
              : (translate('bootstrap.header.end.user.action.theme.dark') || 'Switch to Dark Mode'),
            icon: getThemeMode() === 'dark' ? 'mdi-weather-sunny' : 'mdi-weather-night',
            color: 'primary',
          },
          {
            callback: async () => {
              const nextMode = toggleThemeMode();
              Dialogs.$success({
                key: nextMode === 'dark'
                  ? 'bootstrap.header.end.user.action.theme.changed.dark'
                  : 'bootstrap.header.end.user.action.theme.changed.light',
                fallback: nextMode === 'dark' ? 'Dark mode enabled.' : 'Light mode enabled.',
              });
            },
          },
        ),
        $MI(
          {
            action: 'function',
            text: { key: 'bootstrap.sideNav.tools.language.text', fallback: 'Toggle Language' },
            subText: { key: 'bootstrap.sideNav.tools.language.subText', fallback: 'Switch the demo locale instantly.' },
            icon: 'mdi-translate',
            color: 'secondary',
          },
          {
            callback: async () => {
              toggleLocale();
              Dialogs.$success({ key: 'bootstrap.header.end.user.action.language.changed', fallback: 'Language switched.' });
            },
          },
        ),
      ],
    },
  );
}

function createRootMenu() {
  return $MN(
    {
      ref: 'root-menu',
      title: { key: 'bootstrap.rootMenu.title', fallback: 'Workspace' },
      hideTitle: true,
    },
    {
      children: async () => [
        $MI(
          {
            action: 'report',
            mode: 'display',
            text: { key: 'pages.home.menu.report.display.text', fallback: 'Home' },
            subText: { key: 'pages.home.menu.report.display.subText', fallback: 'Starter page entry from src/pages/home.' },
            icon: 'mdi-home-outline',
            color: 'primary',
          },
          {
            report: async (_menuItem, mode) => createHomeReport(mode || 'display'),
            navigation: () => ({
              key: 'pages.home.report.display',
              persist: true,
            }),
          },
        ),
      ],
    },
  );
}

export function createMainApp(): AppMain {
  return new AppMain(
    {
      ref: 'main-app',
      title: { key: "bootstrap.app.title", fallback: "My Workspace" },
      showHeader: true,
      showFooter: true,
      showFab: false,
    },
    {
      beforeLoad: async () => {
        pendingDeepLinkIntent = readDemoDeepLinkIntent();
        console.info('[vuetify-extended demo] AppOptions.beforeLoad fired', pendingDeepLinkIntent);
      },
      loaded: async () => {
        console.info('[vuetify-extended demo] AppOptions.loaded fired');
      },
      ready: async () => {
        console.info('[vuetify-extended demo] AppOptions.ready fired');
      },
      home: async () => ({
        type: 'report',
        target: createHomeReport('display'),
        params: {
          navigation: {
            key: 'pages.home.report.display',
            persist: true,
          },
        },
      }),
      menu: async () => createRootMenu(),
      leftNav: async () => createMainMenu(),
      rightNav: async () => createShellToolsMenu(),
      leftNavOptions: {
        enabled: true,
        mode: 'temporary',
        width: 320,
        open: true,
        submenuMode: 'inline',
        accordion: true,
      },
      rightNavOptions: {
        enabled: true,
        mode: 'temporary',
        width: 320,
        open: false,
      },
      headerStart: buildHeaderStart,
      headerCenter: buildHeaderCenter,
      headerEnd: buildHeaderEnd,
      footerStart: buildFooterStart,
      footerCenter: buildFooterCenter,
      footerEnd: buildFooterEnd,
    },
  );
}

export function initializeBootstrap(options: InitializeBootstrapOptions = {}) {
  const api = createApiConfig();
  registerDemoScreens();
  const bootstrap = createVuetifyExtendedApp({
    requireApi: false,
    ...(api ? { api } : {}),
    i18n: demoI18n,
    navigation: {
      enabled: true,
      history: false,
      persist: true,
      restoreOnLoad: true,
      storageKey: 'vuetify-extended-cli-demo-v2-navigation',
    },
    app: createMainApp(),
    dialogs: {
      progressSize: 96,
      progressWidth: 10,
      successTimeout: 2400,
      warningTimeout: 3200,
      errorTimeout: 4200,
    },
    notifications: {
      location: 'top-right',
      maxVisible: 4,
      defaultTimeout: 3600,
    },
    ...(options.bootstrap || {}),
  });

  registerDemoLifecycleHandlers();

  return bootstrap;
}
