// Generated by vuetify-ext create dashboard
import { $DB, $DLW, $DMW, $MI, Dialogs, type NavigationEntry } from 'vuetify-extended';
// vuetify-ext:dashboard-imports
import { $DCHW } from 'vuetify-extended';

export function createOpsDashboard() {
  return (_entry?: NavigationEntry) =>
    $DB(
      {
        title: "Operations Dashboard",
        subtitle: 'Starter dashboard generated by vuetify-ext.',
        fluid: true,
        theme: "dark",
      },
      {
        menuItems: async () => [
          $MI(
            {
              action: 'function',
              text: 'Dashboard Action',
              subText: 'Starter dashboard menu item.',
              icon: 'mdi-dots-horizontal-circle-outline',
              color: 'primary',
            },
            {
              callback: async () => {
                Dialogs.$success('Dashboard action clicked.');
              },
            },
          ),
        ],
        topChildren: () => [
          // vuetify-ext:dashboard-top-widgets
          $DMW({
            title: 'Active Users',
            value: 128,
            caption: 'Last 24 hours',
            icon: 'mdi-account-group-outline',
            cols: 12,
            sm: 6,
            lg: 3,
          }),
          $DMW({
            title: 'Revenue',
            value: '$12,450',
            caption: 'Starter metric',
            icon: 'mdi-cash-multiple',
            cols: 12,
            sm: 6,
            lg: 3,
          }),
        ],
        children: () => [
          // vuetify-ext:dashboard-widgets
        // vuetify-ext:dashboard-widget:main:chart:revenue-trend
        $DCHW({
          title: "Revenue Trend",
          cols: 12,
          lg: 4,
          chartType: 'bar',
          chartHeight: 220,
          items: [
            { label: 'Jan', value: 12 },
            { label: 'Feb', value: 18 },
            { label: 'Mar', value: 9 },
          ],
        }),
          $DLW({
            title: 'Recent Activity',
            cols: 12,
            lg: 6,
            items: [
              { title: 'Replace this widget', subtitle: 'Use "vuetify-ext create dashboard-widget" to add more cards.' },
              { title: 'Connect data', subtitle: 'Swap starter items for real API-backed values.' },
            ],
          }),
        ],
        bottomChildren: () => [
          // vuetify-ext:dashboard-bottom-widgets
        ],
      },
    );
}
