// Generated by vuetify-ext create form
import { $FD, $FM, $MI, $MN, $PT, Dialogs, type ReportMode } from 'vuetify-extended';

function createPeopleStepTwoTools() {
  return $MN(
    {
      title: { key: 'pages.people.forms.step2.tools.title', fallback: 'Contact Step Tools' },
      width: 300,
    },
    {
      children: async () => [
        $MI(
          {
            action: 'function',
            text: { key: 'pages.people.forms.step2.tools.review.text', fallback: 'Review Step 2' },
            subText: { key: 'pages.people.forms.step2.tools.review.subText', fallback: 'Form-level tools override the report tools while this step is active.' },
            icon: 'mdi-form-select',
            color: 'secondary',
          },
          {
            callback: async () => {
              Dialogs.$success({ key: 'pages.people.forms.step2.tools.review.success', fallback: 'Step 2 contextual tools are active.' });
            },
          },
        ),
      ],
    },
  );
}

export function createPeopleForm2(mode: ReportMode = 'display') {
  return $FM(
    {
      title: { key: "pages.people.forms.step2.title", fallback: "People Contact Details" },
      mode,
      width: 920,
    },
    {
      rightMenu: async () => createPeopleStepTwoTools(),
      children: () => [
        // vuetify-ext:form-parts
        $PT(
          { cols: 12, dense: true },
          {
            children: () => [
              // vuetify-ext:part:1:fields
              $FD({
                label: { key: "pages.people.forms.step2.fields.name.label", fallback: "Name" },
                storage: 'name',
                cols: 6,
                required: true,
              }),
              $FD({
                label: { key: "pages.people.forms.step2.fields.code.label", fallback: "Code" },
                storage: 'code',
                cols: 6,
              }),
              $FD({
                label: { key: "pages.people.forms.step2.fields.description.label", fallback: "Description" },
                storage: 'description',
                type: 'textarea',
                cols: 12,
              }),
              $FD({
                type: 'label',
                label: { key: "pages.people.forms.step2.hints.replaceSchema", fallback: "Replace these starter fields with the real form schema for this page." },
                cols: 12,
              }),
            ],
          },
        ),
      ],
    },
  );
}
