// Generated by vuetify-ext create report
import { $RP, type NavigationEntry, type ReportMode, $BN, Dialogs } from 'vuetify-extended';
import { createPeopleForm } from './form';
// vuetify-ext:report-form-imports
import { createPeopleForm2 } from './form-2';

export function createPeopleReport(mode: ReportMode = "display") {
  return (entry?: NavigationEntry) => {
    const resolvedMode = (entry?.mode as ReportMode | undefined) || mode;
    return $RP(
      {
        title: { key: "pages.people.report.title", fallback: "People Workspace" },
        objectType: "people",
        forms: 2,
        mode: resolvedMode,
        horizontalAlign: 'center',
        verticalAlign: 'start',
        fluid: true,
      },
      {
        form: async (_props, _context, index) => {
          // vuetify-ext:report-form-resolver
          if (index === 0) return createPeopleForm(resolvedMode);
          if (index === 1) return createPeopleForm2(resolvedMode);
        return undefined;
        },
      sideButtons: (_props, _context, report) => [
        // vuetify-ext:report-side-actions
        // vuetify-ext:report-action:summary
        $BN(
          {
            text: { key: "pages.people.report.actions.summary.text", fallback: "Summary" },
            icon: "mdi-information-outline",
            color: "primary",
            variant: "outlined",
          },
          {
            onClicked: () => {
              report.emit('side-action', "summary");
              Dialogs.$success({ key: "pages.people.report.actions.summary.success", fallback: "Summary clicked." });
            },
          },
        ),
      ],
      },
    );
  };
}
