"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createFinderTrigger = void 0;
// Generated by vuetify-ext page index
var trigger_1 = require("./trigger");
Object.defineProperty(exports, "createFinderTrigger", { enumerable: true, get: function () { return trigger_1.createFinderTrigger; } });
