// Generated by vuetify-ext create collection
import { $COL, type NavigationEntry, type ReportMode } from 'vuetify-extended';
import { createOrdersReport } from './report';
import { createOrdersTrigger } from './trigger';

export function createOrdersCollection(mode: ReportMode = "edit") {
  return (entry?: NavigationEntry) => {
    const resolvedMode = (entry?.mode as ReportMode | undefined) || mode;
    return $COL(
      {
        objectType: "orders",
        idField: "_id",
        multiple: false,
        mode: resolvedMode,
      },
      {
        trigger: async () => {
          const triggerFactory = createOrdersTrigger(resolvedMode);
          return triggerFactory();
        },
        report: async () => {
          const reportFactory = createOrdersReport(resolvedMode);
          return reportFactory();
        },
      },
    );
  };
}
