// Generated by vuetify-ext create report
import { $FD, $FM, $PT, type ReportMode } from 'vuetify-extended';

export function createOrdersForm(mode: ReportMode = 'display') {
  return $FM(
    {
      title: { key: "pages.orders.form.title", fallback: "Orders Collection Form" },
      mode,
      width: 920,
    },
    {
      children: () => [
        // vuetify-ext:form-parts
        $PT(
          { cols: 12, dense: true },
          {
            children: () => [
              // vuetify-ext:part:1:fields
              $FD({
                label: { key: "pages.orders.form.fields.name.label", fallback: "Name" },
                storage: 'name',
                cols: 6,
                required: true,
              }),
              $FD({
                label: { key: "pages.orders.form.fields.code.label", fallback: "Code" },
                storage: 'code',
                cols: 6,
              }),
              $FD({
                label: { key: "pages.orders.form.fields.description.label", fallback: "Description" },
                storage: 'description',
                type: 'textarea',
                cols: 12,
              }),
              $FD({
                type: 'label',
                label: { key: "pages.orders.form.hints.replaceSchema", fallback: "Replace these starter fields with the real form schema for this page." },
                cols: 12,
              }),
            ],
          },
        ),
      ],
    },
  );
}
