// Generated by vuetify-ext create report
import { $RP, type NavigationEntry, type ReportMode } from 'vuetify-extended';
import { createOrdersForm } from './form';
// vuetify-ext:report-form-imports

export function createOrdersReport(mode: ReportMode = "edit") {
  return (entry?: NavigationEntry) => {
    const resolvedMode = (entry?.mode as ReportMode | undefined) || mode;
    return $RP(
      {
        title: { key: "pages.orders.report.title", fallback: "Orders Collection" },
        objectType: "orders",
        forms: 1,
        mode: resolvedMode,
        horizontalAlign: 'center',
        verticalAlign: 'start',
        fluid: true,
      },
      {
        form: async (_props, _context, index) => {
          // vuetify-ext:report-form-resolver
          if (index === 0) return createOrdersForm(resolvedMode);
          return undefined;
        },
      },
    );
  };
}
