// Generated by vuetify-ext create trigger
import { $FD, $TG, type NavigationEntry, type ReportMode } from 'vuetify-extended';

const ORDERS_HEADERS = [
  { title: 'Name', key: 'name' },
  { title: 'Description', key: 'description' },
  { title: 'Status', key: 'status' },
];

const ORDERS_ROWS = [
  { _id: 'orders-1', name: 'Orders Example 1', description: 'Starter row one', status: 'active' },
  { _id: 'orders-2', name: 'Orders Example 2', description: 'Starter row two', status: 'draft' },
  { _id: 'orders-3', name: 'Orders Example 3', description: 'Starter row three', status: 'archived' },
];

export function createOrdersTrigger(mode: ReportMode = "edit") {
  return (entry?: NavigationEntry) => {
    const resolvedMode = (entry?.mode as ReportMode | undefined) || mode;
    return $TG(
      {
        title: { key: "pages.orders.trigger.title", fallback: "Orders Collection Trigger" },
        subtitle: { key: "pages.orders.trigger.subtitle", fallback: "Starter trigger generated by vuetify-ext." },
        objectType: "orders",
        idField: "_id",
        multiple: false,
        mode: resolvedMode,
        queryFields: ['name', 'description', 'status'],
        headers: ORDERS_HEADERS,
        fluid: true,
        canPrint: false,
        canExport: false,
      },
      {
        headers: async () => ORDERS_HEADERS,
        load: async (searchText) => {
          const search = String(searchText || '').trim().toLowerCase();
          if (!search) {
            return ORDERS_ROWS;
          }

          return ORDERS_ROWS.filter((item) =>
            ['name', 'description', 'status'].some((key) =>
              String((item as Record<string, any>)[key] || '').toLowerCase().includes(search),
            ),
          );
        },
        topChildren: () => [
          $FD({
            type: 'label',
            label: { key: "pages.orders.trigger.hints.replaceLoad", fallback: "Replace the in-memory load() function with your API-backed query when ready." },
            cols: 12,
          }),
        ],
      },
    );
  };
}
